Adds an execution environment step to the ad hoc commands
ansible/awx pull request #10004
Opened 2021-04-23 14:48 UTC by AlexSCorey

##### SUMMARY
This addresses some of #9864 by adding a step to select an execution environment to the ad hoc commands wizard

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2021-04-23 at 10 48 34 AM](https://user-images.githubusercontent.com/39280967/115888947-7b091180-a421-11eb-98a3-c21358eb8dff.png)

2021-04-23 16:05 UTC, nixocio commented
Hey @AlexSCorey, 

1 - Advanced Search is not working on the EE step.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9053044/115897790-ce339200-a42a-11eb-8b10-3e30a7cad6f1.png">

2 - We will need to filter EE by the Organization associated with the Inventory and the Globally Available ones.

For example

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/9053044/115898666-d04a2080-a42b-11eb-8fb3-5e63a9beda37.png">

This group is part of demo inventory, and demo inventory is associated to Default Org.

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/9053044/115898942-29b24f80-a42c-11eb-9d52-a73f58e598ac.png">

EE Test should not be a choice here.

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/9053044/115898787-f079df80-a42b-11eb-8f61-0a9b023956ee.png">

2021-04-23 16:07 UTC, nixocio requested changes
Hey @AlexSCorey, 

Just a few points that I noticed.

1 - Advanced Search is not working on the EE step.

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9053044/115897790-ce339200-a42a-11eb-8b10-3e30a7cad6f1.png">

2 - We will need to filter EE by the Organization associated with the Inventory and the Globally Available ones.

For example

<img width="1449" alt="image" src="https://user-images.githubusercontent.com/9053044/115898666-d04a2080-a42b-11eb-8fb3-5e63a9beda37.png">

This group is part of demo inventory, and demo inventory is associated to Default Org.

<img width="1460" alt="image" src="https://user-images.githubusercontent.com/9053044/115898942-29b24f80-a42c-11eb-9d52-a73f58e598ac.png">

EE Test should not be a choice here.

<img width="1231" alt="image" src="https://user-images.githubusercontent.com/9053044/115898787-f079df80-a42b-11eb-8f61-0a9b023956ee.png">

2021-04-27 14:28 UTC, nixocio commented on awx/ui_next/src/components/AdHocCommands/AdHocCommands.test.jsx
> +    // InventoriesAPI.readAdHocOptions.mockResolvedValue({
Remove comments.

2021-04-27 15:55 UTC, nixocio reviewed
Goob job @AlexSCorey.

2021-04-27 15:55 UTC, nixocio commented on awx/ui_next/src/components/AdHocCommands/AdHocCommands.jsx
> +function AdHocCommands({ adHocItems, i18n, hasListItems, onLaunchLoading }) {
onLaunchLoading could be added as part of the `AdHocCommands.propTypes`

2021-04-27 15:55 UTC, nixocio commented on awx/ui_next/src/components/AdHocCommands/AdHocCommands.jsx
> +      organizationId,
👍

2021-04-27 15:55 UTC, nixocio commented on awx/ui_next/src/components/AdHocCommands/AdHocExecutionEnvironmentStep.jsx
> +      const organizationIdParams = organizationId
👍

2021-04-27 15:56 UTC, nixocio commented
I triggered an e2e test run.

2021-04-27 17:29 UTC, nixocio approved these changes

2021-04-28 21:16 UTC, tiagodread commented
@AlexSCorey I've found some items so far:

- The `Execution Environment` word only in the second step is breaking the line
- In the step 3 if you click back to the second step, we are showing `Launch` instead of `Next`
![chrome-capture (7)](https://user-images.githubusercontent.com/12464858/116472593-75aa2d80-a84c-11eb-8bc8-d264ab357132.gif)

- Doing any action with the toolbar component in the second step like sort, search is updating the hosts list behind the modal
![chrome-capture (8)](https://user-images.githubusercontent.com/12464858/116473210-49db7780-a84d-11eb-839f-72e158f4706c.gif)

2021-04-29 17:57 UTC, AlexSCorey commented
Tiago and I spoke offline.  I feel like the side nav issue should be addressed by PF so I filed an issue with them.  I will also have a temporary fix in place for our work

2021-04-29 20:23 UTC, tiagodread approved these changes

2021-04-29 20:43 UTC, merged