Assorted renaming and string changes
ansible/awx pull request #10031
Opened 2021-04-27 17:43 UTC by wenottingham

##### SUMMARY

Goal was to hit user-facing strings and docs.

Didn't try and catch all comments, although did a few when in those files.

2021-04-27 17:44 UTC, wenottingham commented on awx/main/notifications/webhook_backend.py
> +                headers=get_awx_http_client_headers(),
Actual code change, but should do the right thing here (didn't want to cut & paste the user agent templating)

2021-04-27 17:47 UTC, shanemcd commented
![](https://media.giphy.com/media/PUBxelwT57jsQ/giphy.gif)

2021-04-27 17:52 UTC, wenottingham commented
Note: this does not do anything with the inventory source. That requires more thought.

2021-04-27 18:18 UTC, AlexSCorey requested changes
I pulled down this code locally.  The strings themselves seem to be fine, but you have 1 unit test failure that needs to be addressed `MiscSystemDetail.test.jsx`

2021-04-27 18:32 UTC, wenottingham commented
> I pulled down this code locally. The strings themselves seem to be fine, but you have 1 unit test failure that needs to be addressed `MiscSystemDetail.test.jsx`

Fixed, I think. (Also fixed prettier lint failure.)

2021-04-30 16:49 UTC, AlexSCorey approved these changes
Looks good!

2021-04-30 19:24 UTC, merged