Convert user sub-lists to tables
ansible/awx pull request #10056
Opened 2021-04-29 23:10 UTC by keithjgrant

##### SUMMARY

Converts User Organizations, Teams, and Roles lists to tables

Addresses #6189

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2021-04-30 15:35 UTC, AlexSCorey commented
@keithjgrant noticed this went sorting by name on User --> Roles
![Screen Shot 2021-04-30 at 11 34 20 AM](https://user-images.githubusercontent.com/39280967/116718560-17925d00-a9a8-11eb-856f-532269ad07fd.png)

2021-04-30 15:42 UTC, AlexSCorey commented
On User --> Organizations if I have an organization named `New Org` and search for `New` nothing is returned.  However, adding``` toolbarSearchColumns={[
        {
          name: t`Name`,
          key: 'name__icontains',
          isDefault: true,
        },
      ]} ```
to the `<PaginatedTable>` inside `UserOrgnaizationList.jsx` solves this problem.

2021-04-30 15:59 UTC, AlexSCorey commented
The User --> Roles list is confusing to me.  I think this has been discussed and IIRC we have to lay it out this way due to limitations from from the api/pagination.  However, it would be great if the Roles and Name column were switched because it seems that the roles are actually the subject of this list instead of the name of the resource the roles are applied to.

2021-04-30 16:31 UTC, AlexSCorey requested changes
Just a few comments and some commented out code to be removed.

2021-04-30 16:31 UTC, AlexSCorey commented on awx/ui_next/src/screens/User/UserRoles/UserRolesListItem.test.jsx
> +      // wrapper.find('PFDataListCell[aria-label="Resource type"]').text()
Can this be removed?

2021-04-30 16:31 UTC, AlexSCorey commented on awx/ui_next/src/screens/User/UserRoles/UserRolesListItem.test.jsx
> +      // wrapper.find('PFDataListCell[aria-label="Resource role"]').text()
Can this be removed?

2021-04-30 16:31 UTC, AlexSCorey commented on awx/ui_next/src/screens/User/UserRoles/UserRolesListItem.test.jsx
> +      // wrapper.find('PFDataListCell[aria-label="Resource name"]').text()
Can this be removed?

2021-04-30 16:31 UTC, AlexSCorey commented on awx/ui_next/src/screens/User/UserRoles/UserRolesList.jsx
> +            name: t`ID`,
I wonder if this translates accurately.  I also can't tell that it does anything.  It probably can be removed.

2021-04-30 17:21 UTC, keithjgrant commented
> The User --> Roles list is confusing to me. I think this has been discussed and IIRC we have to lay it out this way due to limitations from from the api/pagination. However, it would be great if the Roles and Name column were switched because it seems that the roles are actually the subject of this list instead of the name of the resource the roles are applied to.

Yeah, this needs some thinking to (at the very least) line up with the current mockups better... but this matches prior behavior with the DataList, so that's something to tackle in another PR eventually

2021-04-30 19:21 UTC, AlexSCorey approved these changes
Looks good to me

2021-05-03 15:23 UTC, tiagodread commented
@keithjgrant The user logged can see the tab `Token` when he clicks on his username, looks like we are missing this list

![image](https://user-images.githubusercontent.com/12464858/116895746-e5803580-ac09-11eb-9223-4385ba30e1a5.png)

When the user click on `Tokens` the `Tab` is not being displayed
![image](https://user-images.githubusercontent.com/12464858/116896141-4e67ad80-ac0a-11eb-8ad9-8eae5d34273c.png)

![image](https://user-images.githubusercontent.com/12464858/116895804-f0d36100-ac09-11eb-8f06-903eea0ca591.png)

2021-05-03 19:19 UTC, tiagodread commented
recheck

2021-05-03 19:45 UTC, tiagodread commented
> @keithjgrant The user logged can see the tab `Token` when he clicks on his username, looks like we are missing this list
> 
> ![image](https://user-images.githubusercontent.com/12464858/116895746-e5803580-ac09-11eb-9223-4385ba30e1a5.png)
> 
> When the user click on `Tokens` the `Tab` is not being displayed
> ![image](https://user-images.githubusercontent.com/12464858/116896141-4e67ad80-ac0a-11eb-8ad9-8eae5d34273c.png)
> 
> ![image](https://user-images.githubusercontent.com/12464858/116895804-f0d36100-ac09-11eb-8f06-903eea0ca591.png)

@keithjgrant and I decided file a new issue for this problem here https://github.com/ansible/awx/issues/10092

2021-05-03 19:59 UTC, tiagodread approved these changes
Fixed broken e2e tests in 6299

2021-05-03 20:20 UTC, merged