[WIP] Converts Options lists and other modal lists to tables
ansible/awx pull request #10180
Opened 2021-05-12 14:04 UTC by AlexSCorey

##### SUMMARY
This addresses #10162 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION

2021-05-12 19:52 UTC, jakemcdermott approved these changes

2021-05-12 22:18 UTC, keithjgrant commented on awx/ui_next/src/components/CheckboxListItem/CheckboxListItem.jsx
> +    <Tr aria-labelledby={itemId} id={`options-listItem-${label}`}>
`<Tr>` doesn't need an aria-labelledby (this one would be invalid anyway since that's not the id of an element on the page)

2021-05-12 22:20 UTC, keithjgrant requested changes
just a few tweaks

2021-05-12 22:20 UTC, keithjgrant commented on awx/ui_next/src/screens/Credential/shared/CredentialPlugins/CredentialPluginPrompt/CredentialsStep.jsx
>            key={credential.id}
delete `toolbarSortColumns` prop, since the HeaderRow takes care of that now

2021-05-12 22:20 UTC, keithjgrant commented on awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/InventorySourcesList.jsx
>            key={item.id}
delete toolbarSortColumns here as well

2021-05-12 22:21 UTC, keithjgrant commented on awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.jsx
>            key={`${item.id}-listItem`}
delete `toolbarSortColumns` prop

2021-05-12 22:21 UTC, keithjgrant commented on awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/ProjectsList.jsx
>            key={item.id}
...and here

2021-05-12 22:22 UTC, keithjgrant commented on awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/WorkflowJobTemplatesList.jsx
>            key={item.id}
...last one :)

2021-05-13 16:16 UTC, keithjgrant approved these changes

2021-05-25 13:38 UTC, tiagodread commented
@AlexSCorey for the access and roles tab across different resources like inventory, organization teams etc the modal is displaying the items without style, I could find these places so far, would be interesting search for any other place that could affect

![image](https://user-images.githubusercontent.com/12464858/119506810-a6468f80-bd44-11eb-8f6d-9dfe01cf14fe.png)

![image](https://user-images.githubusercontent.com/12464858/119506854-b199bb00-bd44-11eb-8f56-73df7d4a9f69.png)

2021-05-26 14:51 UTC, tiagodread approved these changes
I've fixed all broken tests in 6344

2021-05-26 15:11 UTC, merged