prevent delete of instance groups list item controlplane and default
ansible/awx pull request #10410
Opened 2021-06-10 14:12 UTC by AlexSCorey

##### SUMMARY
This addresses #10396. `controlplane` instance group is part of every build where as the `default` instance group is part of Openshit/Kubernetes install.
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2021-06-10 at 10 06 42 AM](https://user-images.githubusercontent.com/39280967/121539458-b3fe4500-c9d3-11eb-862a-6dd8edc35220.png)

2021-06-10 15:38 UTC, jakemcdermott requested changes
lgtm, but we'll want to rename the variable from `plan` -> `plane`

2021-06-10 15:38 UTC, jakemcdermott commented on awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
> +  defaultControlPlan,
```suggestion
  defaultControlPlane,
```

2021-06-10 15:38 UTC, jakemcdermott commented on awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
> +    if (clonedItem.name === (defaultControlPlan || defaultExecution)) {
```suggestion
    if (clonedItem.name === (defaultControlPlane || defaultExecution)) {
```

2021-06-10 15:38 UTC, jakemcdermott commented on awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
> +    if (clonedItem.name === (defaultControlPlan || defaultExecution)) {
(and a few other places)

2021-06-10 15:43 UTC, jakemcdermott commented on awx/ui_next/src/screens/InstanceGroup/InstanceGroupList/InstanceGroupList.jsx
> +      const [
@AlexSCorey Will the new settings request run once on initialization or every time the user applies a search filter? If it's running for every search, we'll want to put this into it's own `useRequest` hook and make sure we only call it once.

2021-06-11 12:58 UTC, jakemcdermott approved these changes

2021-06-11 13:11 UTC, nixocio commented
@AlexSCorey the changes look great.

However on this branch I tried to create a new instance group and the following error was raised.

![image](https://user-images.githubusercontent.com/9053044/121691422-f9367b80-ca94-11eb-9eda-4f5efb8d1bc4.png)

I did not see the error on devel.

2021-06-11 14:04 UTC, akus062381 commented
@AlexSCorey - I saw the comment @jakemcdermott made, so I checked- and when I tried to create a new instance group, I saw the following error:
![image](https://user-images.githubusercontent.com/63685497/121698759-51bd4700-ca9c-11eb-92e2-8b32105150b4.png)

The feature of not being able to delete these two instance groups works great!

2021-06-11 15:00 UTC, AlexSCorey commented
recheck

2021-06-11 15:33 UTC, nixocio approved these changes
Last issue reported was fixed.

2021-06-11 15:34 UTC, nixocio commented
I triggered an e2e test run.

2021-06-11 15:48 UTC, akus062381 approved these changes
great!

2021-06-11 16:54 UTC, AlexSCorey commented
regate

2021-06-11 17:07 UTC, AlexSCorey commented
recheck

2021-06-11 18:45 UTC, closed without merging