Add UI support for management jobs in workflows
ansible/awx pull request #10572
Opened 2021-07-01 15:24 UTC by mabashian

##### SUMMARY
link https://github.com/ansible/awx/issues/790

This has been supported via the API for a long time.  The tricky part was handling the `days` (days to keep) for some of the management jobs.  That value needs to flow in/out of extra_data so it's a bit different from other workflow node fields.

Here it is in action:

![mgt_job_wf](https://user-images.githubusercontent.com/9889020/124146558-e1329600-da5b-11eb-8a42-b7b5036ebc37.gif)

I elected to just show the variables in the details view for simplicity.  If it's important we could pull `days` out of the object but more code brings added risk of bugs 🤷 .

<img width="1675" alt="Screen Shot 2021-07-01 at 11 23 33 AM" src="https://user-images.githubusercontent.com/9889020/124149645-c9a8dc80-da5e-11eb-96b8-835b3eb91bf2.png">

@wenottingham if you're not really into this as a feature that's fine - we can close this and reference it later.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2021-07-06 14:31 UTC, AlexSCorey requested changes
Some things I found:
1) if you type/edit the days field it then shows up as a string in the variable details view after clicking on the `i` icon when hovering a node.  However, when you edit that same node, but don't edit the days field the number appears as an integer  in the variables detail after clicking on the `i` icon.  There doesn't seem to be any negative impact on functionality, just some ux inconsistency.

2) We don't seem to show the convergence data in the detail modal.  Should we?

3) `Days` vs `Days to keep`
![Screen Shot 2021-07-06 at 10 19 09 AM](https://user-images.githubusercontent.com/39280967/124615970-b70a1b00-de43-11eb-847b-2a1710675ffa.png)
![Screen Shot 2021-07-06 at 10 19 20 AM](https://user-images.githubusercontent.com/39280967/124615972-b7a2b180-de43-11eb-8d26-eeeadad65709.png)

4) Create a `Clean up job details` node and connect it to a `Cleanup expired sessions` node.  Then click on the `Cleanup expired sessions` node `i` icon.  Page crashes.
![Screen Shot 2021-07-06 at 10 22 57 AM](https://user-images.githubusercontent.com/39280967/124616599-38fa4400-de44-11eb-844c-ce1b6654704f.png)
![Screen Shot 2021-07-06 at 10 23 08 AM](https://user-images.githubusercontent.com/39280967/124616601-3992da80-de44-11eb-83b8-1afe50b82a79.png)

2021-07-12 16:04 UTC, mabashian commented
> if you type/edit the days field it then shows up as a string in the variable details view after clicking on the i icon when hovering a node. However, when you edit that same node, but don't edit the days field the number appears as an integer in the variables detail after clicking on the i icon. There doesn't seem to be any negative impact on functionality, just some ux inconsistency.

Will include a fix for this

> We don't seem to show the convergence data in the detail modal. Should we?

Was probably just missed when we did the initial work.  Let's file an issue for this.

> Days vs Days to keep

The api expects the key to be `days` in `extra_data` so that can't change.  Labelling the field `Days` is ambiguous to me so I don't think we should change it to that.  Here's what the field looks like when you launch a management job:

<img width="1107" alt="Screen Shot 2021-07-12 at 12 01 24 PM" src="https://user-images.githubusercontent.com/9889020/125319664-f5527f00-e308-11eb-9d46-669c6b1cb358.png">

I'd propose changing the string to something like:

<img width="1459" alt="Screen Shot 2021-07-12 at 12 03 23 PM" src="https://user-images.githubusercontent.com/9889020/125319913-33e83980-e309-11eb-8dd7-a98773974d63.png">

so that it more closely matches the other interface.

> Create a Clean up job details node and connect it to a Cleanup expired sessions node. Then click on the Cleanup expired sessions node i icon. Page crashes.

I'll look at this

2021-07-12 19:28 UTC, AlexSCorey approved these changes
This looks good to me.  The unit tests pass, and the issues described earlier are resolved.  I'm triggering e2e tests now.

2021-07-19 22:09 UTC, tiagodread commented
@mabashian could you rebase this one?

2021-07-27 18:52 UTC, tiagodread commented on awx/ui_next/src/util/validators.js
> +      return t`This field must be a number and have a value greater than ${min}`;
This is how the ${min} is being displayed.
 
![image](https://user-images.githubusercontent.com/12464858/127211211-4a153f9b-ce8c-47bc-8600-27d3c885de25.png)

2021-07-28 19:09 UTC, tiagodread approved these changes
Verified that mgmt jobs can be added as nodes to a workflows and run it, also tested the scheduled workflow with mgmt jobs.

2021-07-28 19:15 UTC, merged