Allow requirements.yml/yaml files to be anywhere in project_path related #5000
ansible/awx pull request #10626
Opened 2021-07-12 16:05 UTC by dsglaser

##### SUMMARY

This change searches the project_path for all instances of requirements.yml/yaml and adds them to a list. This list is then used to select which roles/requirements.yml/yaml or collections/requirements.yml/yaml are added. This removes the hardcoding of the requirements.yml/yaml in project_update.yml and allows users to have them in multiple locations.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API
 - UI - project.update.yml

##### AWX VERSION

```
19.2.2
```

##### ADDITIONAL INFORMATION

```

```

2021-07-12 18:25 UTC, wenottingham requested changes
This breaks caching as soon as any two paths have conflicting requirements.

2021-07-12 18:31 UTC, wenottingham commented
See also https://github.com/ansible/awx/issues/106#issuecomment-878289010 (cc @AlanCoding).

Given the move to execution environments, there is some level of diminishing returns to supporting arbitrary project layout.

2021-07-13 16:28 UTC, dsglaser commented
@wenottingham A way of prioritizing requirements would have to be built in then, yes? 

Even with execution environments, a project could have requirements in a different location in a project, right? Is the processing of requirements.yml being handled differently when execution environments are being used?

This PR came from a customer and we were requested to submit it.

2021-07-13 16:36 UTC, wenottingham commented
> @wenottingham A way of prioritizing requirements would have to be built in then, yes?

The caching code would need rewritten to cache differently, or ansible-galaxy would need to be smarter.

> Even with execution environments, a project could have requirements in a different location in a project, right? Is the processing of requirements.yml being handled differently when execution environments are being used?

Downloaded-at-runtime requirements would be done the same way. Built-in collections in an execution environment would be installe globally.

> This PR came from a customer and we were requested to submit it.

Yes but that doesn't mean we will take it if it breaks use cases of the platform, and it does.

Take an example project:

- a/requirements.yml - specifies collection foo-1.2.3
- a/b/c/requirements.yml - specifies foo-2.4.5
- a/d/requirements.yml - specifies foo-0.9.7

This patch would populate the cache with foo-1.2.3, which would be used for *all* runs from the project. Things in a/b/c and /a/d would run with the wrong version of the collection.

2021-07-13 17:42 UTC, dsglaser commented
@wenottingham Understood. I've invited the actual contacts to contribute to this discussion. Obviously the PR as written won't work, but perhaps it is a discussion point for further development. 

In the current code, there is a fileglob for requirements.yml and requirements.yaml. I didn't see a check to make sure that both of these didn't exist or the same issue could be run into. Or perhaps it's somewhere else.

2021-07-14 13:41 UTC, AlanCoding commented
> In the current code, there is a fileglob for requirements.yml and requirements.yaml. I didn't see a check to make sure that both of these didn't exist or the same issue could be run into. Or perhaps it's somewhere else.

What's the concern with this? The fileglob is a means of looping, and if no matching files are found then it's like looping over an empty list - it doesn't do anything and that's the intended behavior for projects with no requirement files.

2021-08-04 15:25 UTC, dsglaser commented
Removing this PR after discussing with PM

2021-08-04 15:25 UTC, closed without merging