Add Thycotic SecretServer support
ansible/awx pull request #10632
Opened 2021-07-13 17:29 UTC by EndlessTrax

##### SUMMARY

Add a Credential Plugin for Thycotic SecretServer (TSS)

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API
 - UI

##### AWX VERSION

```
awx: 19.2.1
```

2021-07-14 17:55 UTC, EndlessTrax commented
Sorry for the additional commits. This PR should be good now.

2021-07-21 14:37 UTC, shanemcd commented
Hello. We recently switched to using GitHub Actions. Can you please rebase on top of the devel branch so tests run here?

2021-07-21 15:43 UTC, jbradberry approved these changes

2021-07-21 17:57 UTC, jakemcdermott requested changes

2021-07-21 17:57 UTC, jakemcdermott commented on awx/main/credential_plugins/tss.py
> +)
I don't see a `lambda` as necessary here. In my opinion, readability would be improved by moving the callable to its own function.

More importantly, I have concerns about debugging or modifying the code. A common thing for developers to do with these plugins is to embed a [breakpoint](https://docs.python.org/3/library/pdb.html#pdb.set_trace) within the secret request logic and inlining the whole backend as a lambda precludes that. 

```suggestion
def tss_backend(**kwargs):
    tss_authorizer = PasswordGrantAuthorizer(
        kwargs['server_url'],
        kwargs['username'],
        kwargs['password']
    )
    tss_server = SecretServer(kwargs['server_url'], tss_authorizer)
    secret_data = tss_server.get_secret(kwargs['secret_id'])

    return ServerSecret(**secret_data).fields[kwargs['secret_field']]


tss_plugin = CredentialPlugin(
    'Thycotic Secret Server',
    tss_inputs,
    tss_backend,
)
```

2021-07-21 19:06 UTC, amigus commented
I generally only create functions (or variables) when I need them because my brain has been damaged from too much functional programming. Given that and the fact that the function is one line and delegates to the SDK API, which is what you end up debugging anyway, I figured a lambda was fine.

That said, regardless of my reasoning, I concede that it's harder to debug, so I'm just going to follow the convention and push the change you requested momentarily.

2021-07-21 22:56 UTC, jakemcdermott commented
@amigus Sounds good. You'll want to rebase the branch with latest devel (and force-push), then we'll be ready to merge.

2021-07-22 02:01 UTC, amigus commented
Could someone else us understand how our change (adding a credential plugin) can break the UI? I have no idea how to debug this. Sorry. 😞

2021-07-22 02:05 UTC, amigus commented
My bad. My repo didn't have the latest upstream. I just rebased and force-pushed. Hopefully gtg now.

2021-07-22 12:57 UTC, jakemcdermott approved these changes

2021-07-22 12:57 UTC, merged

2021-07-22 15:18 UTC, amigus commented
Thanks for your support everyone.