Updates product name in About modal
ansible/awx pull request #10634
Opened 2021-07-13 18:45 UTC by AlexSCorey

##### SUMMARY
Resolves #5200

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION

2021-07-14 19:08 UTC, nixocio requested changes
@AlexSCorey I got this code locally, and there is a duplication.

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/9053044/125678734-4c905cbd-4014-4614-b6e2-8cb8a0299c56.png">

2021-07-19 16:41 UTC, keithjgrant commented on awx/ui_next/src/components/About/About.jsx
> +      productName={`${brandName}`}
Should this just be `productName={brandName}` ?

2021-07-19 20:46 UTC, nixocio approved these changes
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/9053044/126225182-44c0d0fc-94b3-4b45-a14a-194b4d50a006.png">

2021-07-19 22:09 UTC, tiagodread commented
@AlexSCorey could you rebase this one?

2021-07-21 16:36 UTC, keithjgrant approved these changes

2021-07-23 17:19 UTC, tiagodread approved these changes

2021-07-23 17:20 UTC, merged