Ensures that field is on screen behind the confirmation modal
ansible/awx pull request #10722
Opened 2021-07-22 16:32 UTC by AlexSCorey

##### SUMMARY
This addresses #10706 

##### ISSUE TYPE
 - Bugfix Pull Request
 - 
##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2021-07-22 at 12 32 09 PM](https://user-images.githubusercontent.com/39280967/126675140-e5bb5add-eec7-49c6-9792-bdbb169776ac.png)

2021-07-23 13:02 UTC, nixocio commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
> +            onAddToach={jest.fn()}
Hey @AlexSCorey was this change supposed to be part of this PR?
```suggestion
            onAddToast={jest.fn()}
```

2021-07-23 13:47 UTC, nixocio requested changes

2021-07-23 13:47 UTC, nixocio commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
> +            onAddToach={jest.fn()}
onAddToast
```suggestion
            onAddToast={jest.fn()}
```

2021-07-23 13:47 UTC, nixocio commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
> +            onAddToach={jest.fn()}
```suggestion
            onAddToast={jest.fn()}
```

2021-07-23 13:47 UTC, nixocio commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
> +            onAddToach={jest.fn()}
```suggestion
            onAddToast={jest.fn()}
```

2021-07-23 13:47 UTC, nixocio commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateList/NotificationTemplateListItem.test.js
> +            onAddToach={jest.fn()}
```suggestion
            onAddToast={jest.fn()}
```

2021-08-02 15:19 UTC, nixocio approved these changes

2021-08-04 14:37 UTC, tiagodread approved these changes

2021-08-04 17:21 UTC, merged