10654 10739 10740 fix
ansible/awx pull request #10820
Opened 2021-08-05 17:56 UTC by AlexSCorey

##### SUMMARY
This PR addresses #10654 #10739 and #10740.  The biggest change here is the way the use will edit the Survey question order.  We wanted to add drag functionality and @trahman73 decided that the best way to do it was to repurpose the Preview modal(which had the same data on it as the list itself) to be a order edit modal that allows the user to drag their questions where they want.  This also means that the user does not have to wait for the UI to POST the new order and fetch the new order from the API every time they change a single question.  They can do all of there changes at 1 time and then save those changes.
##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![host expand](https://user-images.githubusercontent.com/39280967/128398106-3c8d9527-6c16-4dcd-a2eb-b21ddd1fdbf4.gif)
![SurveyChanges](https://user-images.githubusercontent.com/39280967/128398118-199ba1ab-c55d-4907-84cb-c12d257d3632.gif)

2021-08-06 14:27 UTC, nixocio commented on awx/ui/src/screens/Template/Survey/SurveyList.js
> +        <TableComposable>
Add datalabel, ids, or ouiaId to help with testing.

2021-08-06 15:35 UTC, nixocio requested changes
This is a nice UX improvement.

A few suggestions.

1. Add a note about drag and drop here.
<img width="976" alt="image" src="https://user-images.githubusercontent.com/9053044/128532471-9da2ee11-ceb4-47db-9ef9-633e9a6a04ae.png">

Something like:

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/9053044/128532587-a50af752-34bf-49f5-8517-3e093fddd97f.png">

2. Disable Edit Order button if there is just one survey

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/9053044/128533180-a0395a8a-fd78-415b-af8d-6e7f496afcc2.png">

<img width="1494" alt="image" src="https://user-images.githubusercontent.com/9053044/128533458-c9ece032-a497-4f0e-abf6-b3eea86c86af.png">

3. Add a tooltip to `Edit Order` button.
4. Add a `Answer variable name` `blah` and use the drag and drop - click on the survey, and it will redirect away from the app.

2021-08-09 15:44 UTC, nixocio approved these changes
This a great UX improvement. Good job @AlexSCorey.

2021-08-09 18:55 UTC, akus062381 commented
@AlexSCorey

Would you please add better locators (OUIAID, data-cy, ID) to the expanded list items in the Host table, as shown below?
![image](https://user-images.githubusercontent.com/63685497/128757978-d6e2ca25-7751-42da-9d37-5fe2873e74dd.png)

Can you please add better locators for the places I have circled?
![image](https://user-images.githubusercontent.com/63685497/128758971-9d4cfd7b-20f8-4eba-bf21-dbf2502cce8f.png)

Thank you!

2021-08-10 14:38 UTC, akus062381 approved these changes

2021-08-10 15:18 UTC, nixocio commented
Since there were more change since we ran the e2e tests, I will apply this label again.

2021-08-11 13:58 UTC, merged