Fixes validation issues associated with the Notification Form
ansible/awx pull request #10958
Opened 2021-08-27 18:23 UTC by AlexSCorey

##### SUMMARY
This addresses #10557 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
Email validation
![Email Edit](https://user-images.githubusercontent.com/39280967/131172128-a34cf879-4759-4a38-be63-f2c125fd253c.gif)

Twilio phone number validation
![twilio phone number](https://user-images.githubusercontent.com/39280967/131172124-768388d0-627c-481a-adc6-a779afd22487.gif)

2021-08-27 20:09 UTC, nixocio reviewed
Good job @AlexSCorey . Just to confirm details with you.

2021-08-27 20:09 UTC, nixocio commented on awx/ui/src/util/validators.js
> +          error = t`Please enter a valid phone number.  Phone numbers must begin with + and contain the country code, area code and subscriber number with no spaces, dashes or other characters. For e
This error message is really helpful, but long. What about we move some of this text to the tooltip? We could show the expected number format there, for example.
![image](https://user-images.githubusercontent.com/9053044/131182810-d87ffc93-6810-4338-8655-c71b18d4bda5.png)

2021-08-27 20:09 UTC, nixocio commented on awx/ui/src/util/validators.js
> +        if (!/^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})(\d{3})(\d{4})/.test(v)) {
I looked at twilio docs about phone number validations, and I found.

https://www.twilio.com/docs/glossary/what-e164#regex-matching-for-e164

What are we taking in consideration international numbers as well?

```

RegEx Matching for E.164

According to the official ITU E.164 recommendation the format must be a number up to fifteen digits in length starting with a ‘+’. You can also exclude 0 as the first character since there are no country codes that start with 0. Here is a sample regular expression:

^\+[1-9]\d{1,14}$```

2021-08-30 14:21 UTC, AlexSCorey commented on awx/ui/src/util/validators.js
> +        if (!/^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})(\d{3})(\d{4})/.test(v)) {
es, the regex does take international numbers into consideration.

2021-08-31 14:38 UTC, nixocio requested changes

2021-08-31 14:38 UTC, nixocio commented on awx/ui/src/screens/NotificationTemplate/shared/TypeInputsSubForm.js
> +          route SMS messages. Phone numbers should be formatted +11231231234. For more information see `}
This message is very clear. 👍

2021-08-31 14:38 UTC, nixocio commented on awx/ui/src/screens/NotificationTemplate/shared/TypeInputsSubForm.js
> +              href="https://www.twilio.com/docs/verify/migrating-1x-2x#e164-phone-number-formatting-for-sms-and-voice"
If the third party docs link changes, we will have a broken link in our application - I would suggest not adding a link to a certain URL.

2021-08-31 14:38 UTC, nixocio commented on awx/ui/src/util/validators.js
> +        if (!/^\s*(?:\+?(\d{1,3}))?[-. (]*(\d{3})(\d{3})(\d{4})/.test(v)) {
@AlexSCorey thanks.

I noticed that when I press `enter` after entering a valid number the validation is being triggered.

<img width="563" alt="image" src="https://user-images.githubusercontent.com/9053044/131522778-7a019364-670d-4cb1-9277-be7e41907c59.png">

2021-08-31 17:16 UTC, akus062381 commented
@AlexSCorey - I am still seeing that these two fields in Twilio accept alpha characters....
![image](https://user-images.githubusercontent.com/63685497/131547209-f8cb757c-c959-4574-a1e7-b5b17cace933.png)

2021-08-31 20:38 UTC, nixocio commented on awx/ui/src/util/validators.js
> +import { plural, t } from '@lingui/macro';
Hey @AlexSCorey do you want to import lower case plural, instead of Plural component?

2021-09-01 17:31 UTC, akus062381 approved these changes
Looks good from a QE standpoint.

2021-09-01 21:06 UTC, nixocio approved these changes

2021-09-02 13:49 UTC, merged