Add ability to select to prefer IPv4 addresses for ansible_ssh_host
ansible/awx pull request #1097
Opened 2018-02-01 02:38 UTC by rbywater

##### SUMMARY

Currently Cloudforms can return a mix of IPv4 and IPv6 addresses in the
ipaddresses field and this mix comes in a "random" order (that is the
first entry may be IPv4 sometimes but IPv6 other times). If you wish to
always use IPv4 for the ansible_ssh_host value then this is problematic.

This change adds a new prefer_ipv4 flag which will look for the first
IPv4 address in the ipaddresses list and uses that instead of just the
first entry.

Upstream PR has been made to Ansible repo as https://github.com/ansible/ansible/pull/35584

##### ISSUE TYPE

 - Feature Pull Request
 
##### COMPONENT NAME

 - API
 
##### AWX VERSION

```
N/A - cloudforms.py tested manually
```

##### ADDITIONAL INFORMATION

```

```

2018-02-01 13:05 UTC, ryanpetrello commented
@rbywater thanks for submitting this upstream to core - if they merge this (or some version of it), we'll merge this into awx

2018-02-01 15:34 UTC, samdoran commented
@ryanpetrello This was merged into Ansible.

2018-02-01 15:55 UTC, ryanpetrello commented
@rbywater did you test this in awx?  I'd expect that you probably need to whitelist `prefer_ipv4` here:

https://github.com/ansible/awx/blob/e642af82ccb7dcea942532dff2133e6e49dbebd9/awx/main/tasks.py#L1726

...for this to actually work.

2018-02-01 15:59 UTC, ryanpetrello commented
Additionally, could you improve this test to add additional checks to ensure this works?

https://github.com/ansible/awx/blob/e642af82ccb7dcea942532dff2133e6e49dbebd9/awx/main/tests/unit/test_tasks.py#L1703

Something like this is probably pretty close to what you need:

```diff
diff --git a/awx/main/tests/unit/test_tasks.py b/awx/main/tests/unit/test_tasks.py
index 2c42df6..dd16c9f 100644
--- a/awx/main/tests/unit/test_tasks.py
+++ b/awx/main/tests/unit/test_tasks.py
@@ -1712,6 +1712,7 @@ class TestInventoryUpdateCredentials(TestJobExecution):
         self.instance.credential.inputs['password'] = encrypt_field(
             self.instance.credential, 'password'
         )
+        self.instance.source_vars_dict['prefer_ipv4'] = True
 
         def run_pexpect_side_effect(*args, **kwargs):
             args, cwd, env, stdout = args
@@ -1721,6 +1722,7 @@ class TestInventoryUpdateCredentials(TestJobExecution):
             assert config.get('cloudforms', 'username') == 'bob'
             assert config.get('cloudforms', 'password') == 'secret'
             assert config.get('cloudforms', 'ssl_verify') == 'false'
+            assert config.get('cloudforms', 'prefer_ipv4') == 'true'
 
             cache_path = config.get('cache', 'path')
             assert cache_path.startswith(env['AWX_PRIVATE_DATA_DIR'])
```

2018-02-01 16:33 UTC, ryanpetrello requested changes
@rbywater did you test this in awx?  I'd expect that you probably need to whitelist `prefer_ipv4` here:

https://github.com/ansible/awx/blob/e642af82ccb7dcea942532dff2133e6e49dbebd9/awx/main/tasks.py#L1726

...for this to actually work.

Additionally, could you improve this test to add additional checks to ensure this patch works?

https://github.com/ansible/awx/blob/e642af82ccb7dcea942532dff2133e6e49dbebd9/awx/main/tests/unit/test_tasks.py#L1703

Something like this is probably pretty close to what you need:

```diff
diff --git a/awx/main/tests/unit/test_tasks.py b/awx/main/tests/unit/test_tasks.py
index 2c42df6..dd16c9f 100644
--- a/awx/main/tests/unit/test_tasks.py
+++ b/awx/main/tests/unit/test_tasks.py
@@ -1712,6 +1712,7 @@ class TestInventoryUpdateCredentials(TestJobExecution):
         self.instance.credential.inputs['password'] = encrypt_field(
             self.instance.credential, 'password'
         )
+        self.instance.source_vars_dict['prefer_ipv4'] = True
 
         def run_pexpect_side_effect(*args, **kwargs):
             args, cwd, env, stdout = args
@@ -1721,6 +1722,7 @@ class TestInventoryUpdateCredentials(TestJobExecution):
             assert config.get('cloudforms', 'username') == 'bob'
             assert config.get('cloudforms', 'password') == 'secret'
             assert config.get('cloudforms', 'ssl_verify') == 'false'
+            assert config.get('cloudforms', 'prefer_ipv4') == 'true'
 
             cache_path = config.get('cache', 'path')
             assert cache_path.startswith(env['AWX_PRIVATE_DATA_DIR'])
```

2018-02-01 17:59 UTC, rbywater commented
I tested it mostly via the python file directly and I thought I'd given it
a poke in AWX too but perhaps I got confused with another change I was
looking at :/

Thanks for the pointers - will fix up the relevant bits of code and enhance
the tests as well.

On Fri, 2 Feb 2018, 4:55 AM Ryan Petrello, <notifications@github.com> wrote:

> @rbywater <https://github.com/rbywater> did you test this in awx? I'd
> expect that you probably need to whitelist prefer_ipv4 here:
>
>
> https://github.com/ansible/awx/blob/e642af82ccb7dcea942532dff2133e6e49dbebd9/awx/main/tasks.py#L1726
>
> ...for this to actually work.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/awx/pull/1097#issuecomment-362309873>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAXfw5LSOBrwCflHsahLVSfiiTQKEvIbks5tQd6EgaJpZM4R094m>
> .
>

2018-02-01 18:47 UTC, ryanpetrello commented
Sounds good - thanks for contributing :)!

2018-02-01 20:43 UTC, ryanpetrello commented
@rbywater the latest shippable test failures look unrelated to your tests, and more like issues on shippable's end (the tests are timing out).  I'll take a look at this shortly.

2018-02-02 14:34 UTC, ryanpetrello commented
@rbywater I can't get our CI to re-run against this change.  Do you mind rebasing and uploading again?  Something like this:

```shell
$ git remote add upstream https://github.com/ansible/awx.git
$ git fetch upstream
$ git rebase upstream/devel
$ git push origin feature/preferipv4
```

2018-02-04 20:28 UTC, rbywater commented
Have had to rely on Shippable for test results at the moment as I couldn't get my local dev instance of AWX working. However given another error looks like I need to try and get it up and running!

2018-02-05 19:57 UTC, ryanpetrello approved these changes

2018-02-05 19:57 UTC, merged

2018-02-05 19:57 UTC, ryanpetrello commented
Thanks @rbywater!