Add wording about expectations for enabled status and default group
ansible/awx pull request #10993
Opened 2021-08-31 20:37 UTC by AlanCoding

2021-09-01 20:33 UTC, AlexSCorey requested changes

2021-09-01 20:33 UTC, AlexSCorey commented on docs/receptor_mesh.md
> +Fields like `cpu`, `memory`, and `version` will obtain a non-default values through this process.
```suggestion
Fields like `cpu`, `memory`, and `version` will obtain a non-default value through this process.
```

2021-09-02 13:26 UTC, AlexSCorey approved these changes
Looks good.

2021-09-03 12:33 UTC, thenets approved these changes

2021-09-03 14:35 UTC, merged