Show button to cancel inventory source sync
ansible/awx pull request #11023
Opened 2021-09-03 19:27 UTC by nixocio

Show button to cancel inventory source sync.

See: https://github.com/ansible/awx/issues/10933

2021-09-07 15:22 UTC, AlexSCorey requested changes
I pull the code down and ran through it.  It operates as expected.  Just 1 small change with the Plural component in the tooltip.

2021-09-07 15:22 UTC, AlexSCorey commented on awx/ui/src/screens/Inventory/InventoryList/InventoryListItem.js
> +      tooltipContent =
Use lingui [`<Plural>`](https://lingui.js.org/ref/macro.html?highlight=plural#jsxmacro-Plural) or [`plural()`](https://lingui.js.org/ref/macro.html?highlight=plural#jsmacro-plural)

2021-09-08 20:46 UTC, AlexSCorey approved these changes
Looks good.  Well done!

2021-09-09 13:41 UTC, akus062381 approved these changes

2021-09-09 18:16 UTC, merged