[WIP]This adds Instance Details view
ansible/awx pull request #11069
Opened 2021-09-10 20:20 UTC by AlexSCorey

##### SUMMARY
This addresses #10951 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION

2021-09-14 14:03 UTC, akus062381 approved these changes
looks good!

2021-09-15 16:41 UTC, kialam requested changes
This looks really good so far! Aside from some variable naming nitpicks, my only two requests are to handle health check error message rendering in the UI and adding a unit test for the new Health Check button.

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +              <StatusLabel status={healthCheck?.errors ? 'error' : 'healthy'} />
I think we want to show the health check errors here if an API query returns any. @AlanCoding do you know the format of the `errors` field or have a sample error message we could use to format for display in the UI?

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +      let instDetails;
```suggestion
      let instanceDetails;
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +        const [{ data: instanceDetails }, { data: healthCheckData }] =
```suggestion
        const [{ data: details }, { data: healthCheckData }] =
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +        instDetails = instanceDetails;
```suggestion
        instanceDetails = details;
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +      setBreadcrumb(instanceGroup, instDetails);
```suggestion
      setBreadcrumb(instanceGroup, instanceDetails);
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +          instDetails.mem_capacity,
```suggestion
          instanceDetails.mem_capacity,
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +          instDetails.cpu_capacity,
```suggestion
          instanceDetails.cpu_capacity,
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +          instDetails.capacity_adjustment
```suggestion
          instanceDetails.capacity_adjustment
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +      return { instance: instDetails };
```suggestion
      return { instance: instanceDetails };
```

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +              onClick={() => fetchHealthCheck()}
```suggestion
              onClick={fetchHealthCheck}
```
For SyntheticEvents you can pass the function name. I would only use arrow functions if you need to pass in parameters.

2021-09-15 16:41 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
> +  test('Should call disassociate', async () => {
Can we also add a test for the Health Check button here?

2021-09-15 17:10 UTC, AlanCoding commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +              <StatusLabel status={healthCheck?.errors ? 'error' : 'healthy'} />
example

```
Receptor error getting worker info from receptor-2, detail:
exec: "ansible-runner": executable file not found in $PATH
```

From API

```
"errors": "Receptor error getting worker info from receptor-2, detail:\nexec: \"ansible-runner\": executable file not found in $PATH",
```

2021-09-15 17:52 UTC, AlexSCorey commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +              <StatusLabel status={healthCheck?.errors ? 'error' : 'healthy'} />
@kialam the Health Check errors are rendered [here](https://github.com/ansible/awx/pull/11069/files#diff-bd47c736dddf4c8b375895668ba9e3a8143af17a8aaf32c48536a3a25d322de1R253).  This is just rendering the status of the instance.

2021-09-15 18:06 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.js
> +              <StatusLabel status={healthCheck?.errors ? 'error' : 'healthy'} />
Ah excellent. Confirmed errors look good in the UI:
<img width="1296" alt="Screen Shot 2021-09-15 at 11 05 25 AM" src="https://user-images.githubusercontent.com/2293210/133486211-e518a53f-c988-4c32-a2e9-94ff10981395.png">

2021-09-15 21:48 UTC, kialam commented on awx/ui/src/screens/InstanceGroup/InstanceDetails/InstanceDetails.test.js
> +  test('Should handle api error for health check', async () => {
nice

2021-09-15 21:49 UTC, kialam approved these changes
LGTM. Great job Alex!

2021-09-16 13:38 UTC, merged