Fixes convergence data value on node edit mode
ansible/awx pull request #11096
Opened 2021-09-20 19:14 UTC by AlexSCorey

##### SUMMARY
This addresses #10945 
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![convergence](https://user-images.githubusercontent.com/39280967/134060884-1f8d37a6-507c-4eb8-b353-5425b9d45a4f.gif)
N

2021-09-20 19:45 UTC, nixocio requested changes

2021-09-20 19:45 UTC, nixocio commented on awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/useWorkflowNodeSteps.js
> +        console.log({ initialValues }, nodeToEdit);
```suggestion

```

2021-09-20 20:58 UTC, nixocio approved these changes

2021-09-21 15:20 UTC, InnocentK approved these changes
Looks good so far. I'll check on a few more things first

2021-09-21 18:38 UTC, InnocentK commented
Need to verify this will work with changes introduced in (#11097) before approving

2021-09-21 20:04 UTC, InnocentK approved these changes

2021-09-21 20:26 UTC, merged