Groups Advanced Search Keys
ansible/awx pull request #11208
Opened 2021-10-05 19:59 UTC by AlexSCorey

##### SUMMARY
This addresses #7741 and it also addresses a bug that I don't think has an issue, where the Clear all filters button was not being removed, when there were no search filters.  
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![searchClear](https://user-images.githubusercontent.com/39280967/136093988-d1a4b0c2-e68c-4962-a625-546d62a72663.gif)
![Screen Shot 2021-10-05 at 3 57 26 PM](https://user-images.githubusercontent.com/39280967/136093998-4a6893ba-260d-4f93-9bbf-90ebd5feb503.png)
![Screen Shot 2021-10-05 at 3 57 21 PM](https://user-images.githubusercontent.com/39280967/136094000-6f1b5845-a8ae-4d9c-9317-b2fc0c59e94b.png)

2021-10-05 21:01 UTC, nixocio commented on awx/ui/src/components/Search/AdvancedSearch.js
> +  );
This a nice function to remove duplicate keys.

2021-10-05 21:05 UTC, nixocio requested changes
Hey @AlexSCorey, good job.

Overall those changes look good, I just noticed from time to time it will display a division without populate the select groups.

Like:

![image](https://user-images.githubusercontent.com/9053044/136102421-f1ac37fb-04aa-4896-8426-6c6f3af7432d.png)

Next update the keys were shown. It seems that we could hide the divider and groups if we do not have keys. To be explored.

2021-10-06 17:25 UTC, nixocio approved these changes

2021-10-07 18:53 UTC, tiagodread requested changes
@AlexSCorey I can not type inside key select anymore, when I try to do so, I get this error:

![image](https://user-images.githubusercontent.com/12464858/136445093-45f268a4-dfc6-4d50-bc7d-8a2dc830d882.png)

2 broken e2e tests is failing

2021-10-07 19:54 UTC, akus062381 commented
@Alex, I found this bug in a different place (as we talked about). In this case, the user not only needs to be able to type, but they also need to be able to create a tag entry.
![wfjt-error](https://user-images.githubusercontent.com/63685497/136453177-8685b5c5-c95b-4be4-83f9-8eb6d11b7e55.gif)

2021-10-07 20:25 UTC, AlexSCorey commented
@akus062381 and @tiagodread that bug seems to be related to a PF upgrade that happened a few days ago.  They made a change that seems to have broken things for us but those changes are not related to this PR. I think we need to file an issue for it, pleasse

2021-10-11 12:41 UTC, nixocio commented
@AlexSCorey, please, can you rebase this PR? Since we downgraded PF, and verify that reported error does not remain.

2021-10-13 13:32 UTC, tiagodread approved these changes
After reverting PF4 upgrade, the tests are looking better now and the previous failures aren't related to this change.

2021-10-13 13:32 UTC, merged