Disable default instance delete
ansible/awx pull request #11216
Opened 2021-10-07 15:49 UTC by AlexSCorey

##### SUMMARY
Resolves #11214 
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2021-10-07 at 11 48 45 AM](https://user-images.githubusercontent.com/39280967/136419543-cd0647c5-822c-4c02-95e7-22337e6fc587.png)
![Screen Shot 2021-10-07 at 11 48 37 AM](https://user-images.githubusercontent.com/39280967/136419550-0f97ea75-9871-4ebb-b4cc-04fc3a66b936.png)

2021-10-07 15:59 UTC, nixocio commented
@AlexSCorey it seems like there are extra commits on your branch - commits that have been already merged.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/9053044/136421260-a66a2da2-4cd2-41c0-9f8f-4a10707b78ca.png">

2021-10-07 16:14 UTC, nixocio requested changes
Good job @AlexSCorey .

Code changes looks good. 

Minor suggestion to add a tooltip explaining why the name change is disabled. 

As an example:

<img width="511" alt="image" src="https://user-images.githubusercontent.com/9053044/136423536-240c5517-20bc-4eb6-a1e0-e97269d24deb.png">

Also, are we going to hide delete button here?

<img width="938" alt="image" src="https://user-images.githubusercontent.com/9053044/136429643-7a224c74-371c-4a3f-9229-e878d74dfcc2.png">



We need to fix the extra commit before merging.

2021-10-07 16:14 UTC, nixocio commented on awx/ui/src/screens/InstanceGroup/shared/InstanceGroupForm.test.js
> +  test('Name field should be disabled, defualt', async () => {
```suggestion
  test('Name field should be disabled, default', async () => {
```

2021-10-07 16:14 UTC, nixocio commented on awx/ui/src/screens/InstanceGroup/shared/InstanceGroupForm.test.js
> +  test('Name field should be disabled, controleplane', async () => {
```suggestion
  test('Name field should be disabled, controlplane', async () => {
```

2021-10-07 18:21 UTC, nixocio commented
> @AlexSCorey it seems like there is an extra commit on your branch - commit that was already merged.
> 
> <img alt="image" width="1297" src="https://user-images.githubusercontent.com/9053044/136421260-a66a2da2-4cd2-41c0-9f8f-4a10707b78ca.png">


@AlexSCorey There are just 2 commits now, but the changes related to the third one remains.

2021-10-07 19:59 UTC, tiagodread approved these changes
This looks good from QE standpoint

2021-10-08 16:46 UTC, nixocio approved these changes

2021-10-08 16:48 UTC, merged