Updates patternfly dependencies
ansible/awx pull request #11402
Opened 2021-11-30 21:04 UTC by AlexSCorey

##### SUMMARY
This resolves #11105
##### ISSUE TYPE
-dependency upgrade

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION

2021-12-01 14:03 UTC, nixocio commented
Upgrade of PF should NOT add this issue here - https://github.com/ansible/awx/issues/11224 - Verify that this issue does not exist with the newer version.
A previous version of PF did, that is why we needed to roll back a previous upgrade.
I triggered the e2e tests.

2021-12-01 15:06 UTC, nixocio commented
@AlexSCorey this PR is changing the behavior of the drag/drop of elements.

On devel:

https://user-images.githubusercontent.com/9053044/144258863-98b0574b-d5d1-4409-bd6f-8d3d40608dec.mov

On the code related to this PR.

https://user-images.githubusercontent.com/9053044/144257751-61a0a724-6e47-472f-b7e3-42815f71b7ee.mov

Do we need to upgrade those components? I was able to run the code on devel on the PF version of this branch.

All tests done on Firefox.

2021-12-01 15:08 UTC, nixocio requested changes
The drag/drop behavior is different from devel.

2021-12-02 21:04 UTC, nixocio requested changes

2021-12-02 21:04 UTC, nixocio commented on awx/ui/src/components/SelectedList/DraggableSelectedList.js
> +                    ouiaId={`draggable-list-remove-${label}`}
removal of `data-cy` may break tests.

2021-12-02 21:04 UTC, nixocio commented on awx/ui/src/components/SelectedList/DraggableSelectedList.js
> +                  <GripVerticalIcon />
On the previous implementation once the user hover over this button - we allow the user to drag the row.

There were lines between rows, and the `x` to remove that row was positioned on the end of the row. This change may break visual tests..

Current implementation:

![image](https://user-images.githubusercontent.com/9053044/144502727-e2ff5de7-a180-476a-a829-dec7710adeeb.png)

Current devel implementation.

<img width="1229" alt="image" src="https://user-images.githubusercontent.com/9053044/144502827-05c7ead2-09e3-43b4-9143-78c92136de04.png">

2021-12-06 14:38 UTC, akus062381 commented
I'm going to run a Jenkins run against this branch

2021-12-07 14:43 UTC, nixocio approved these changes

2021-12-07 14:45 UTC, nixocio requested changes

2021-12-07 14:45 UTC, nixocio commented on awx/ui/src/setupTests.js
> +import Adapter from '@wojtekmaj/enzyme-adapter-react-17';
@AlexSCorey this line is failing the linter, and tests.

2021-12-07 15:42 UTC, akus062381 commented
@AlexSCorey please check with me before merging this. As the run above shows, we've got 16 failures on this branch.

2021-12-09 14:43 UTC, akus062381 approved these changes

2021-12-09 17:30 UTC, AlexSCorey commented
![drag](https://user-images.githubusercontent.com/39280967/145446377-a1bafad5-de80-40c1-b4a2-72324f689d4b.gif)

2021-12-10 18:54 UTC, nixocio approved these changes
@AlexSCorey we need to file an issue to cover accessibility.

https://www.patternfly.org/v4/components/drag-and-drop

> Note: Keyboard accessibility and screen reader accessibility are still in development.

2021-12-13 16:02 UTC, merged