Adds Inventory labels
ansible/awx pull request #11558
Opened 2022-01-18 16:59 UTC by AlexSCorey

##### SUMMARY
This PRs adds functionality so a user can add labels to an inventory in the same way that they can add labels to a job template.  

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![inventoryLabels](https://user-images.githubusercontent.com/39280967/149983290-08503e13-3992-44e1-a520-bb81aad34587.gif)

2022-01-18 22:40 UTC, keithjgrant approved these changes

2022-01-19 18:30 UTC, AlanCoding commented on awx/main/access.py
> +    )
In the access class `can_attach` and `can_unattach` should get called when managing labels... but it's likely the case that `BaseAccess` logic is sufficient for this.

2022-01-21 18:46 UTC, nixocio requested changes
Hey @AlexSCorey, overall great job.

![labels](https://user-images.githubusercontent.com/9053044/150582447-caf8e872-3f4c-45fa-a9c0-a5ab14e1cc3c.gif)

There is an extra time that no labels are displayed when editing the inventory.

Overall great job.

2022-01-24 17:59 UTC, nixocio approved these changes
Approve UI changes. 💯

2022-01-27 16:00 UTC, jbradberry commented on awx/api/views/inventory.py
> +from awx.main.models.label import Label
The `Label` model is re-imported at the top level of awx.main.models, so it can be put up in the big list above instead of as a separate line here.

2022-01-27 16:06 UTC, jbradberry approved these changes

2022-01-27 16:08 UTC, jbradberry commented
@AlexSCorey oh, I see that you have to update the unit tests.

2022-02-04 18:33 UTC, AlanCoding commented
Is this blocked on anything? As far as I can tell things look ready to go.

2022-02-07 15:52 UTC, AlexSCorey commented
@AlanCoding I am just waiting on testing. Just moved the issue to Needs test.

2022-02-08 19:16 UTC, rebeccahhh approved these changes

2022-02-08 19:16 UTC, rebeccahhh commented on awx/main/tests/unit/models/test_label.py
> +        mock_query_set.exists.return_value = True
good change

2022-02-11 15:47 UTC, InnocentK commented
@tiagodread and @akus062381 After this PR is merged we will need to add test coverage for this new feature

2022-02-11 15:49 UTC, InnocentK commented
Passes UI E2E testing: https://dashboard.cypress.io/projects/ui2mq7/runs/11658/overview (failed test is unrelated).
Will still need to verify API E2E testing before merging

2022-02-14 20:13 UTC, InnocentK commented
Passes API testing

2022-02-14 20:14 UTC, merged