Add info popover to WF node list items
ansible/awx pull request #11587
Opened 2022-01-21 19:30 UTC by marshmalien

##### SUMMARY
https://github.com/ansible/awx/issues/11325

* Add ability to pass row action items to checkbox rows 
* Add a "compact" detail list option
* Add detail popover to Template list items within the workflow addition node

![popover](https://user-images.githubusercontent.com/15881645/150587952-4b90e711-fd22-4d37-8988-edab7104b6a7.gif)

##### ISSUE TYPE

 - Enhancement Pull Request

##### COMPONENT NAME

 - UI

2022-01-25 14:35 UTC, nixocio requested changes
Hey @marshmalien good job, small suggestions. It would be nice to add a couple of unit-test to avoid future regressions.

2022-01-25 14:35 UTC, nixocio commented on awx/ui/src/components/DetailList/DetailList.js
> +  ${(props) => (props.compact ? `column-gap: 20px;` : `grid-gap: 20px;`)}
What about we add this prop explicitly to the component `DetailList`?

2022-01-25 14:35 UTC, nixocio commented on awx/ui/src/screens/Template/WorkflowJobTemplateVisualizer/Modals/NodeModals/NodeTypeStep/JobTemplatesList.js
> +        dataCy="template-${template.id-playbook"
```suggestion
        dataCy={`template-${template.id}-playbook`}
```

2022-01-27 20:22 UTC, nixocio approved these changes
💯

2022-01-27 20:26 UTC, nixocio commented
I triggered the e2e tests.

2022-02-01 16:10 UTC, InnocentK approved these changes
Looks good!

2022-02-01 16:10 UTC, merged