Fixes erroneous disabling of name input field on container and instance group forms
ansible/awx pull request #11691
Opened 2022-02-07 17:07 UTC by AlexSCorey

##### SUMMARY
Instance Groups and Container Groups have names, (`default`, `controlplane`) that are not available to the user when creating/editing an instance or container group.  This PR fixes a case where a user would go to type `default` and the name input would immediately disable which would prevent them from typing something like `default Instance Group`.  

To resolve that both forms do a check to see if the `initialValues === default || controlplane` (which would mean we are in edit mode, and these are protected instance groups so the name input should be disabled. Doing it this way prevents the field from going disabled as soon as the use types `default` or `controlplane` giving them the opportunity to type more than just those names.  I also introduce a validators to throw a form error when the user tries to create IG/CGs of those protected names
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Instancegroups](https://user-images.githubusercontent.com/39280967/152836556-3b6f243b-c289-4e0c-ac2b-42f9d5563cc2.gif)

2022-02-08 21:31 UTC, nixocio requested changes
Good job @AlexSCorey, minor suggestion.

2022-02-08 21:31 UTC, nixocio commented on awx/ui/src/util/validators.js
> +export function protectedResourceName(names = [], message) {
```suggestion
export function protectedResourceName(message, names = []) {
```

2022-02-09 18:53 UTC, nixocio approved these changes

2022-02-10 21:27 UTC, InnocentK approved these changes
The above E2E tests showing failure are not caused by the work done in this PR and so it should be safe to merge

2022-02-14 20:54 UTC, InnocentK commented
From QE: Good to merge once all the required CLI tests pass

2022-02-14 21:14 UTC, merged