Use select_related on db queries to reduce db calls
ansible/awx pull request #11790
Opened 2022-02-22 15:26 UTC by AlexSCorey

##### SUMMARY
Addresses #11712.  Without use `select_related('target', 'source')` we were making `n+1` sequel queries which is a performance issue.  This change reduces that number to just `n`.
##### ISSUE TYPE
-enhancement

##### COMPONENT NAME
 - API

##### AWX VERSION

##### ADDITIONAL INFORMATION

2022-02-22 15:35 UTC, nixocio requested changes
This code here https://github.com/ansible/awx/pull/11768 is already merged and being added again as part of this PR.

2022-02-23 15:31 UTC, AlexSCorey commented
> This code here #11768 is already merged and being added again as part of this PR.

That is weird I'm not sure it it looks I added that code.

2022-02-23 19:29 UTC, AlanCoding commented
@nixocio it doesn't look like this has already been merged. It seems valid as far as I can tell.

2022-02-23 19:29 UTC, AlanCoding approved these changes

2022-02-24 13:34 UTC, nixocio approved these changes
UI duplicated code was removed.

2022-03-02 00:53 UTC, AlanCoding commented
This looks ready to merge!

2022-03-02 16:33 UTC, merged