Add details related workflow job on the workflow approval details
ansible/awx pull request #12213
Opened 2022-05-11 14:55 UTC by nixocio

Add details related workflow job on the work flow approval details

Remove not used prop isLoading, fix, and expand unit-tests related to
workflow approval details.

This UX was created with @trahman73 feedback.

<img width="1481" alt="image" src="https://user-images.githubusercontent.com/9053044/167882486-a1d7806e-8598-411e-a4e7-430d7835c8a2.png">

2022-05-11 16:52 UTC, marshmalien approved these changes

2022-05-11 16:52 UTC, marshmalien commented on awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.js
> +              workflowJob.summary_fields?.inventory ? (
I don't think we need this additional check for `workflowJob.summary_fields?.inventory` since we check for the value in the ternary above.

2022-05-11 16:52 UTC, marshmalien commented on awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.test.js
> +            url: '/api/v2/credentials',
👍

2022-05-11 16:52 UTC, marshmalien commented on awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
> +import { createMemoryHistory } from 'history';
These imports are unused.

2022-05-12 16:34 UTC, kialam requested changes
Good job here. I think the tests should be written using RTL instead of Enzyme. If you want help mounting contextualized components (documentation can be found [here](https://testing-library.com/docs/example-react-context/)), let me know.

2022-05-12 16:34 UTC, kialam commented on awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
> +    waitForElement(wrapper, 'WorkflowApprovalDetail', (el) => el.length > 0);
RTL has a built-in function `waitFor` that we can leverage here. An example of its usage would be: `await waitFor(() => screen.getByText(/Workflow job details/i));`

2022-05-12 16:34 UTC, kialam commented on awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
>    mountWithContexts,
If we're writing unit tests, would it make sense to convert this to RTL instead of using Enzyme?

2022-05-12 16:38 UTC, nixocio commented on awx/ui/src/screens/WorkflowApproval/WorkflowApprovalDetail/WorkflowApprovalDetail.test.js
>    mountWithContexts,
hey @kialam , I basically fixed several uni-tests. Once I added more requests to the workflowApprovalDetails, it was required to wrap them in `act` -  I agree with you that we should aim to write brand new tests using RTL.

2022-05-12 17:37 UTC, kialam approved these changes

2022-05-12 20:02 UTC, akus062381 approved these changes

2022-05-12 20:02 UTC, merged