Add help text popovers to /#/applications details fields
ansible/awx pull request #12222
Opened 2022-05-12 14:37 UTC by nixocio

Add help text popovers to /#/applications details fields

See: https://github.com/ansible/awx/issues/11873

2022-05-12 19:30 UTC, kialam requested changes

2022-05-12 19:30 UTC, kialam commented on awx/ui/src/screens/Application/shared/Application.helptext.js
> +const applicationHelpTextStrings = () => ({
Since the translations here are just strings, there's no need to make this an anonymous function. An object literal would be preferred.

2022-05-12 20:12 UTC, kialam approved these changes

2022-05-17 18:36 UTC, InnocentK approved these changes
This should be good to go once the CI checks pass

2022-05-17 20:11 UTC, merged