Add support for TZID in schedule rrules
ansible/awx pull request #1231
Opened 2018-02-13 18:48 UTC by marshmalien

##### SUMMARY
This commit contains changes in how we are sending the schedule rrule string to the API.
* We are now including the local timezone information `TZID=NNNNN` in the rrule string. 
* The UI POSTs an rrule to a new endpoint `/api/v2/schedules/preview/`, and it returns the next 10 occurrences in local and UTC time.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
see: https://github.com/ansible/ansible-tower/issues/823

2018-02-13 19:46 UTC, jlmitch5 requested changes
Other than a slight alteration of the debounce approach, this is a really nice, surgical way of tackling this.  great job!

2018-02-13 19:46 UTC, jlmitch5 commented on awx/ui/client/src/scheduler/schedulerForm.partial.html
> +                    ng-model-options="{
update this to debouncing the function, instead of the input field.

2018-02-13 19:57 UTC, jaredevantabor reviewed
very nice

2018-02-13 19:57 UTC, jaredevantabor commented on awx/ui/client/src/scheduler/schedulerAdd.controller.js
> +    let timeZonesAPI = () => {
could this go in the resolve?

2018-02-13 19:57 UTC, jaredevantabor commented on awx/ui/client/src/scheduler/schedulerAdd.controller.js
> +            $http.post('/api/v2/schedules/preview/', {'rrule': req})
I think this is cool

2018-02-13 19:57 UTC, jaredevantabor commented on awx/ui/client/src/scheduler/schedulerForm.partial.html
> +                    {{ occurrence | date:'MM-dd-yyyy HH:mm:ss'}} UTC
is there upside to using Moment to format our dates?

2018-02-13 21:35 UTC, ryanpetrello commented
Gonna post some screenshots of weird bugs I manage to find.

![screen shot 2018-02-13 at 4 34 50 pm](https://user-images.githubusercontent.com/214912/36174941-db74700a-10db-11e8-9c4d-12ca3d6b9615.png)

2018-02-13 21:56 UTC, ryanpetrello commented
Example taken from https://github.com/ansible/awx/issues/710

![screen shot 2018-02-13 at 4 53 31 pm](https://user-images.githubusercontent.com/214912/36175740-7b749362-10de-11e8-96a8-ad6c55d9c17b.png)

Note that I chose "Noon CST", and the schedule printed starts at 13:00 in "local" time, which is wrong.

The value begin sent to the preview endpoint is:
`DTSTART;TZID=America/Chicago:20180221T120000 RRULE:FREQ=HOURLY;INTERVAL=4;UNTIL=20180223T180000Z`

...so this  _may_ be an API bug (I'm digging now).

2018-02-13 22:02 UTC, ryanpetrello commented
Given:

![screen shot 2018-02-13 at 4 53 31 pm](https://user-images.githubusercontent.com/214912/36175740-7b749362-10de-11e8-96a8-ad6c55d9c17b.png)

Note that I chose an end time of "18:00"; if you actually look at the `rrule` value that is sent, though, it's 18:00 UTC:

`DTSTART;TZID=America/Chicago:20180221T120000 RRULE:FREQ=HOURLY;INTERVAL=4;UNTIL=20180223T180000Z`

If a user fills out a form in this way, should we interpret this as "until 18:00 _local_?"

2018-02-13 22:09 UTC, ryanpetrello commented
If I create this simple schedule for noon Chicago:

![screen shot 2018-02-13 at 5 07 07 pm](https://user-images.githubusercontent.com/214912/36176367-5d8c76f6-10e0-11e8-96fd-8bc01240ec7c.png)

...and then save it and re-edit it, the timezone gets reset to America/New York, and the UI is wrong:

![screen shot 2018-02-13 at 5 08 28 pm](https://user-images.githubusercontent.com/214912/36176428-8b631fc6-10e0-11e8-9062-f1c358f2a4cc.png)

Now that we're storing TZID= info, it might be nice to update the UI with the correct timezone at the time it was saved.

2018-02-20 21:58 UTC, jlmitch5 approved these changes
Looks great now!

2018-02-20 21:58 UTC, jlmitch5 commented on awx/ui/client/src/scheduler/schedulerAdd.controller.js
> +
awesome!!

2018-02-21 18:15 UTC, marshmalien commented
I found a longwinded solution to convert the UNTIL value prior to POSTing the rrule. Based on the the host system’s current timezone and date/time, we can convert those values to the dropdown timezone date/time, and then finally to UTC standard format time. The rrule is sent with the values you expect based off of the user's input.

The problem lies in the fact that our library utilizes the UTC end date (without converting it to local time) to initialize the schedule form. 

For example: 
`UNTIL=20180224T000000Z` 
This value will appear as  02/24/2018 00:00:00 when they go back to re-edit the schedule.  I’ve explored using different helper methods to immediately convert the user’s inputs to UTC based on the dropdown, but it has led to some synchrony issues. 

 The input should be interpreted as either only UTC or Local time. As of this PR, we are interpreting the end date fields as UTC.

2018-02-21 18:55 UTC, merged