Add column to display resource related to a schedule
ansible/awx pull request #12360
Opened 2022-06-10 19:28 UTC by nixocio

Add column to display what resource is related to a schedule

See: https://github.com/ansible/awx/issues/5012

2022-06-13 17:01 UTC, akus062381 reviewed
nothing is broken but I wanted to bring something to your attention-

when a user creates a schedule inside a project or a job template, and they click the link to those resources from the list of schedules, it navigates to the detail pages for those resources. 
but- when a user clicks the resource link to a management job from the list of schedules, it doesn't navigate to the details page for that management job. it navigates to the list of management jobs.
So technically there isn't anything wrong, but perhaps for continuity, you could have them work the same way?

2022-06-13 17:14 UTC, AlexSCorey requested changes
Great job. Lets improve the UX by adding sort functionality for the new column.

2022-06-13 17:14 UTC, AlexSCorey commented on awx/ui/src/components/Schedule/ScheduleList/ScheduleList.js
> +            <HeaderCell>{t`Related resource`}</HeaderCell>
Lets add a sort key here
```suggestion
            <HeaderCell sortKey="unified_job_template">{t`Related resource`}</HeaderCell>
```

2022-06-13 17:41 UTC, akus062381 approved these changes

2022-06-13 17:50 UTC, nixocio commented
> nothing is broken but I wanted to bring something to your attention-
> 
> when a user creates a schedule inside a project or a job template, and they click the link to those resources from the list of schedules, it navigates to the detail pages for those resources. but- when a user clicks the resource link to a management job from the list of schedules, it doesn't navigate to the details page for that management job. it navigates to the list of management jobs. So technically there isn't anything wrong, but perhaps for continuity, you could have them work the same way?

@akus062381, good observation. However management jobs do not have a details page. That is why.

2022-06-13 17:55 UTC, nixocio commented on awx/ui/src/components/Schedule/ScheduleList/ScheduleList.js
> +            <HeaderCell>{t`Related resource`}</HeaderCell>
Done.

2022-06-14 15:28 UTC, nixocio commented
@AlexSCorey , PR updated ready to be reviewed again.

2022-06-15 15:53 UTC, AlexSCorey approved these changes
Looks good to me.

2022-06-15 15:53 UTC, merged