Making verbosity list and options a constant and adding WinRM debug
ansible/awx pull request #12378
Opened 2022-06-14 21:19 UTC by john-westcott-iv

##### SUMMARY

##### ISSUE TYPE

 - Bug or Docs Fix

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 21.1.1.dev84+gf042274bc5
```

##### ADDITIONAL INFORMATION

```

```

2022-06-15 17:24 UTC, kialam approved these changes
This works as-is, however if you wanted to use just one constant variable instead of having to maintain two I would suggest creating a mapper function to return the value (`label`) you want for the details views.

2022-06-15 17:24 UTC, kialam commented on awx/ui/src/constants.js
> +export const VERBOSITY = {
Good example of standardization here. If you wanted to just use one constant to represent Verbosity and it's permutations in the UI, I could see creating the object literal containing the `key`, `value`, and `label` keys and then calling a function to return the appropriate label when not used as an options dropdown.

```javascript
export const getVerbosity = (key) => VERBOSITY.filter(v => v.key === key)
const [{ label }] = getVerbosity(verbosityKey);
```

You could probably just save both the constant and the function as one object literal itself.

2022-06-15 18:52 UTC, nixocio requested changes, later dismissed
Those strings are not being selected to be translated.

I followed up with @john-westcott-iv offline.

2022-06-22 18:12 UTC, keithjgrant commented on awx/ui/src/components/AdHocCommands/AdHocDetailsStep.js
> +  // verbosityOptions: PropTypes.arrayOf(PropTypes.object).isRequired,
delete?

2022-06-22 18:13 UTC, keithjgrant commented on awx/ui/src/components/AdHocCommands/AdHocCommandsWizard.js
> +  // verbosityOptions: PropTypes.arrayOf(PropTypes.object).isRequired,
delete?

2022-06-22 18:14 UTC, keithjgrant approved these changes

2022-06-24 13:06 UTC, akus062381 approved these changes

2022-06-24 13:06 UTC, merged