Allow modification of schedule if there are two of the same name
ansible/awx pull request #12407
Opened 2022-06-22 13:48 UTC by Tompage1994

##### SUMMARY

Fixes issue where you couldn't modify or delete a schedule if two schedules of the same name exist.
related #12406  

##### ISSUE TYPE

 - Bug or Docs Fix

##### COMPONENT NAME

 - Collection
 
##### AWX VERSION

```
21.2.0
```

##### ADDITIONAL INFORMATION

```

```

2022-06-22 14:35 UTC, john-westcott-iv requested changes
Thanks for finding and fixing this issue!

Could we also add a test in `awx/awx_collection/tests/integration/targets/schedule/tasks` where you create two schedules with the same name and then try to delete one by name and assert that fails and then delete by name/unified_job_template and assert that works?

2022-06-22 14:35 UTC, john-westcott-iv commented on awx_collection/plugins/modules/schedule.py
> +        sched_search_fields['unified_job_template'] = unified_job_template_id
Could we either add information in the docs (line 107) and/or add an example which states that the unified_job_template field will be used to search for the schedule if provided. For the use case of deleting a schedule where there are 2 with the same name that might be useful.

2022-06-22 14:40 UTC, Tompage1994 commented
> 

I can do, however that wouldn't necessarily have failed in the way you expect with the current code.

Right now what happens if you create two of the same name using the modules it will just override the first with the second. Obviously the checking for a failure when no UJT is set will help us detect regression here though.

2022-06-22 17:42 UTC, john-westcott-iv approved these changes
Looks good from a code perspective, will wait for QE to add coverage before merging

2022-06-23 09:24 UTC, Tompage1994 commented
@john-westcott-iv I managed to get my pytest working properly and have added a unit test which captures the issue and should prevent regression

2022-06-28 23:23 UTC, merged