six.string_types in mixins.py
ansible/awx pull request #1241
Opened 2018-02-13 23:50 UTC by cclauss

##### SUMMARY

Replace __(str, unicode)__ with __six.string_types__ for compatibility with both Python 2 and Python 3.

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2018-02-14 05:40 UTC, cchurch approved these changes

2018-02-14 05:44 UTC, cchurch requested changes
At first glance it looked ok, but `six.string_types` in Python 2 is `(basestring,)`, `type(...)` will return either `str` or `unicode`, so it needs to be an `isinstance(..., six.string_types)` check instead.

2018-02-14 08:12 UTC, cclauss commented
Thanks massively...  A perfect explanation.  This is the __last of the flake8 showstopper issues__ (--select=E901,E999,F821,F822,F823) so once this PR is merged, we should add a '3.6' line at https://github.com/ansible/awx/blob/devel/.travis.yml#L3-L4 and see how far we get in the tests.

2018-02-14 15:05 UTC, ryanpetrello commented
@cclauss for what it's worth, that `.travis.yml` file is super old and not something we actually use (we use shippable ci)

2018-02-14 15:08 UTC, ryanpetrello commented
related: https://github.com/ansible/awx/pull/1249

2018-02-14 15:11 UTC, ryanpetrello commented
@cclauss also, when our tests run in shippable, they do so in a serious of containers that we build (as described in https://github.com/ansible/awx/pull/100#issuecomment-329517451).  The container we build for flake8 runs uses python2.  The process for adding a py3 lint isn't may not be as simple as just adding a line to the `shippable.yml` file; we'd probably need to change the way linting works (maybe we can just run flake8 _without_ actually using a container?) to support parallel runs for py2 *and* py3 linting.

2018-02-14 18:38 UTC, cchurch approved these changes

2018-02-14 18:38 UTC, merged

2019-01-22 15:26 UTC, ryanpetrello commented
FYI, we've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which runs under python3.6.  This version of awx also supports python2 _and_ python3 virtualenvs when running Ansible playbooks.