Adds Overview of job output with some images to help.
ansible/awx pull request #12510
Opened 2022-07-12 20:50 UTC by AlexSCorey

##### SUMMARY
This addresses #11822.

##### ISSUE TYPE
 - Bug or Docs Fix

##### COMPONENT NAME
 - UI

2022-07-12 20:52 UTC, AlexSCorey commented
@tvo318 can you check this out when you get a chance?

2022-07-12 20:57 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +points in the API.
endpoints is one word.

2022-07-12 21:38 UTC, tvo318 requested changes

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +Generally speaking the job output has 2 different states that result in different functionality.
```suggestion
The job output has 2 different states that result in different functionality.
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +The first state the output could be in is when the job is actively running. During this time there is limited
```suggestion
The first state the output could be in is when the job is actively running. During this time, there is limited
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +output is coming into the UI we turn off the following features:
```suggestion
output is coming into the UI, the following features turn off:
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +   job itself. The only part of the job ouput that is not collapsable is the playbook summary (Only jobs that
```suggestion
   job itself. The only part of the job ouput that is not collapsable is the playbook summary (only jobs that
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +We turn on the following features:
```suggestion
The following features are enabled:
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +1. Follow/unfollow - If you are `Following` this means that you are streaming the output ont the screen
```suggestion
1. Follow/unfollow - `Following` indicates you are streaming the output on the screen
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +1. Follow/unfollow - If you are `Following` this means that you are streaming the output ont the screen
Is it `Following` or just `Follow`?

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +   as it comes into the UI. If you see some output that you want to examine closer, while the job is running
```suggestion
   as it comes into the UI. If you see some output that you want to examine closer while the job is running,
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +   scroll to it, and click unfollow, and the output will stop streaming onto the screen. This feature is only
```suggestion
   scroll to it, and click `Unfollow`, and the output will stop streaming onto the screen. This feature is only
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +2. Page up and page down buttons- These buttons allow you to navigate quickly up and down the output.
```suggestion
2. Page up and page down buttons - Use these buttons to navigate quickly up and down the output.
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +   ![Running job](images/JobOutput-running.png)
It would be more helpful to the reader if the image was annotated (with arrows or a box around) pointing to the buttons you are describing here.

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +After the job is complete we remove the Follow/Unfollow button, and allow for Expand/Collapse and Search.
```suggestion
After the job is complete, the Follow/Unfollow button disables, and the Expand/Collapse and Search button enables.
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +and a Task can be inside a Play, and a Play is inside a Playbook. We take advantage of this concept and enable
```suggestion
a Task can be inside a Play, and a Play inside a Playbook. Leveraging this concept to enable
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +Expand/Collapse for these job types, so that the user can make children of a particular line of output collapse and
```suggestion
Expand/Collapse for these job types, allows you to collapse and hide the children of a particular line of output. 
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +disappear. This parent-child event relationship only exists on jobs executed from a job template. All other types of jobs do not
```suggestion
This parent-child event relationship only exists on jobs executed from a job template. All other types of jobs do not
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +have this event concept and therefore do not have Expand/Collapse functionality. By default all job
```suggestion
have this event concept, and therefore, do not have Expand/Collapse functionality. By default, all job
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
>  2. When an event that has children arrives in output, but the children are not present yet
```suggestion
2. When an event with children arrives in output, but the children are not yet present.
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +### Expand collapse a single event- how it works and how it changes the state object
```suggestion
### Expand collapse a single event - how it works and how it changes the state object
```

2022-07-12 21:38 UTC, tvo318 commented on awx/ui/docs/JobOutput.md
> +### Expand collapse all- how it works and how it changes the state object
```suggestion
### Expand collapse all - how it works and how it changes the state object
```

2022-07-13 14:49 UTC, AlexSCorey commented on awx/ui/docs/JobOutput.md
> +1. Follow/unfollow - If you are `Following` this means that you are streaming the output ont the screen
`Follow`

2022-07-13 16:41 UTC, keithjgrant commented on awx/ui/docs/JobOutput.md
> +   scroll to it, and click `Unfollow`, and the output will stop streaming onto the screen. This feature is only
The UI will stop following as soon as the user scrolls up

2022-07-13 17:00 UTC, keithjgrant approved these changes
This is a great start to our docs for the feature. Nice work!

2022-07-14 21:44 UTC, tvo318 approved these changes

2022-07-15 14:52 UTC, merged