Improves visibility of workflow approval notification bell
ansible/awx pull request #12727
Opened 2022-08-24 14:07 UTC by akira6592

##### SUMMARY

Previously, unapproved workflows  on header looked the same even if they existed or not. It was difficult to distinguish between them.
<img width="418" alt="image" src="https://user-images.githubusercontent.com/16851744/186439268-feaca9e4-1fa1-4070-8638-123763f036c3.png">

<img width="393" alt="image" src="https://user-images.githubusercontent.com/16851744/186439318-c97fc1b0-ed1f-46df-a941-dedbb59b5ea8.png">

So, if there are unapproved workflows, I made it easier to notice them by changing the color.

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/16851744/186438892-5782d5da-2030-4891-ad1f-c91f31c06537.png">

<img width="1344" alt="image" src="https://user-images.githubusercontent.com/16851744/186438950-80c6cb7b-672a-47d6-8a3f-28055e8f0992.png">

##### ISSUE TYPE

 - New or Enhanced Feature
 
##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 21.4.1.dev23+g8ea3c9c43e
```

##### ADDITIONAL INFORMATION

```

```

2022-08-26 14:12 UTC, AlexSCorey requested changes
@akira6592 Thanks so much for submitting this PR. This is really good work.  If we are going to update this feature we should use this component from Patternfly https://www.patternfly.org/v4/components/notification-badge.  Feel free to update this PR

2022-08-27 01:47 UTC, akira6592 commented
@AlexSCorey Thank you for information. 
I fixed for using NotificationBadge. How about this?

count 0
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/16851744/187009199-d578c50d-6f00-4839-baa6-9390b93dbe0c.png">

count 1
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/16851744/187009225-c4b85510-f692-4a87-8730-cdce75a93436.png">

movie
![gamen_test1](https://user-images.githubusercontent.com/16851744/187009411-c685b9a4-891c-4bd0-9cfc-021b11eb6edd.gif)

When the count is 0, the number is not displayed, but I think there is no particular problem.

2022-09-07 22:17 UTC, AlexSCorey approved these changes
Good work on this!

2022-09-07 22:26 UTC, AlexSCorey commented
@akira6592 probably need to rebase this to get the tests to pass.

2022-09-08 04:29 UTC, akira6592 commented
@AlexSCorey Thank you for approval and information. I rebased.

2022-09-13 20:38 UTC, AlexSCorey commented
e2e tests triggered

2022-09-22 14:02 UTC, akira6592 commented
@AlexSCorey Should I rebase again?

2022-09-22 14:13 UTC, merged

2022-09-22 14:13 UTC, AlexSCorey commented
@akira6592 thanks for doing this.  Well done!

2022-09-22 14:22 UTC, akira6592 commented
@AlexSCorey Thank you for merging!