Fix the `is_successful` assertion corner case
ansible/awx pull request #12833
Opened 2022-09-06 13:02 UTC by AlanCoding

##### SUMMARY
This was breaking my attempts to write tests that did `job.assert_status(['successful', 'canceled'])`. Because "successful" is in the allowed status list, it won't pass on the "canceled" status because `is_successful` isn't true.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - API

2022-09-06 16:02 UTC, jbradberry commented on awxkit/awxkit/api/mixins/has_status.py
> +            if self.status != 'successful' or self.is_successful:
This doesn't seem useful, `is_successful` is literally defined as `return self.status == 'successful'`.  It seems to me that this line then will always be true.

If I follow what is going on, this changes the intent of this block.

2022-09-06 16:19 UTC, jbradberry requested changes
To be honest, looking at this I realize that this sub-block should probably be taken out entirely.  If `self.status in status_list` is true, we ought to just bail out immediately.

2022-09-06 16:41 UTC, jbradberry commented
@AlanCoding having just tracked down the original PR that put that there, which indicates that `is_successful` may have different implementations, I am amending my opinion.  Something like this seems called for:

```
if ('successful' in status_list) == self.is_successful:
    return
```

2022-09-06 17:04 UTC, AlanCoding commented
```python
if ('successful' in status_list) == self.is_successful:
    return
```

This still doesn't allow the fairly reasonable use of `job.assert_status(['successful', 'canceled'])`, because a canceled job is _not_ successful. That's why I think this needs to reference `self.status` in some way. The conditional is hard to read, that's true.

If I go through all the `is_successful` definition, I honestly don't find any of them helpful looking, and I wouldn't be opposed to deleting this block.

2022-09-06 17:48 UTC, jbradberry commented
Yeah, no, I just realized that my suggestion isn't workable either.  This is tricky, and I don't think anymore that getting rid of the inner block is the way to go either.

2023-01-17 18:58 UTC, jbradberry commented
Clearing out my review, in case this gets picked up again.

2023-04-13 15:17 UTC, AlanCoding commented
Clearly, this is challenging to think about. Although believed to be valid, I will close because unlikely to have time for it.

2023-04-13 15:17 UTC, closed without merging