Adding make option to enable sql debugging
ansible/awx pull request #12951
Opened 2022-09-24 13:28 UTC by john-westcott-iv

##### SUMMARY

Turns on SQL query logging and SQL headers if enabled.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Other

##### AWX VERSION

```
awx: 21.6.1.dev52+g05e3c29fe8
```

##### ADDITIONAL INFORMATION

```

```

2022-09-26 16:15 UTC, AlanCoding commented on tools/docker-compose/ansible/roles/sources/tasks/sql_debug.yml
> +    line: "SQL_DEBUG = True"
It seems a little overkill to enable SQL logging in django _and_ in postgres. Wouldn't it be hard to see anything?

2022-09-26 16:16 UTC, AlanCoding commented on tools/docker-compose/ansible/roles/sources/tasks/sql_debug.yml
> +#   < X-API-Query-Time: 0.006s
I thought these came with general DEBUG mode?

2022-11-15 16:28 UTC, AlanCoding requested changes
This feels overly-specific to me. Users should already have a means to change the file-based settings. That changed some time ago for docker-compose, now it looks for local_overrides.py or something like that. The advice should be to set SQL_DEBUG there.

I also think that adding an option for extra postgres options would be fine, but handling each parameter individually doesn't strike me as a good approach.

2025-04-02 14:08 UTC, djyasin commented
@john-westcott-iv is this PR still relevant? Can we close this one?

2025-04-03 12:35 UTC, closed without merging