Add shellcheck and codespell checks.
ansible/awx pull request #13221
Opened 2022-11-21 20:01 UTC by djyasin

Spelling corrections in markdown files.

Co-Authored By: Lila Yasin <89486372+djyasin@users.noreply.github.com>

##### SUMMARY

Adding Shellcheck and a few code spelling corrections. Cherry-picked from a community PR #11439

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - Docs
 - Other

##### AWX VERSION

```
21.9.1
```

2022-11-30 20:37 UTC, fosterseth commented on Makefile
> +shellcheck:
@shanemcd  does this all look good to you? if so we'll merge this in soon

2022-12-07 16:01 UTC, shanemcd commented on tools/docker-compose/entrypoint.sh
> +exec "$@"
This change looks suspicious to me and would expect it to cause problems for commands with more than one argument.

2022-12-07 16:03 UTC, shanemcd commented
I called this out on the original PR but, right now this seems to rely on someone manually running this command, which doesn't feel particularly useful. It's very trivial to add new CI checks and I think we should do that before merging this PR: https://github.com/ansible/awx/blob/a0b8215c06918260c4f3d0c481fb1adac6fa2613/.github/workflows/ci.yml#L17 The only additional thing you might need to do is ensure the correct package is installed, but only in the _devel_ image. There are other examples in the Dockerfile of us doing this.

2022-12-07 16:03 UTC, shanemcd requested changes
Added some comments. The main thing that worries me right now is the change to the entry point. But I also don't see this being very useful without a CI check.

2022-12-14 14:22 UTC, AlexSCorey approved these changes
UI portion looks good to me.

2023-04-28 09:56 UTC, gundalow reviewed
Do you plan on adding shellcheck & codespell into CI?

2023-04-28 09:56 UTC, gundalow commented on Makefile
> +shellcheck:
How come we've got more than detect & fix?

2023-04-28 09:56 UTC, gundalow commented on Makefile
We will add these into CI at a later point?

2023-04-28 20:16 UTC, djyasin commented
This PR had a bit of a mix-up. When we had initially discussed pulling these changes in, we decided not to pull in the Makefile changes and not to add to CI. That decision was made because we realized we would A) have to go back and retroactively fix all the existing spelling issues (I worked on that for a bit and realized it was very big endeavor to sift through) and B) it could cause PRs to fail since sometimes the spellchecks aren't 100% correct.

When I cherry-picked this commit initially, I didn't realize I had grabbed those changes as well.

I have now pulled out the makefile changes and am just keeping the spelling suggestions.

Let me know if you feel it should be done a different way- I've had quite a bit of conversation around this one and there are different opinions. I can definitely pivot!

2023-05-02 09:27 UTC, gundalow commented
> This PR had a bit of a mix-up. When we had initially discussed pulling these changes in, we decided not to pull in the Makefile changes and not to add to CI. That decision was made because we realized we would A) have to go back and retroactively fix all the existing spelling issues (I worked on that for a bit and realized it was very big endeavor to sift through) and B) it could cause PRs to fail since sometimes the spellchecks aren't 100% correct.
> 
> When I cherry-picked this commit initially, I didn't realize I had grabbed those changes as well.
> 
> I have now pulled out the makefile changes and am just keeping the spelling suggestions.
> 
> Let me know if you feel it should be done a different way- I've had quite a bit of conversation around this one and there are different opinions. I can definitely pivot!

Thanks for the explanation. 
This sounds good, though we may just need to accept things might regress without CI (though this PR still makes things better than they were).

2023-05-02 13:54 UTC, djyasin commented
> > This PR had a bit of a mix-up. When we had initially discussed pulling these changes in, we decided not to pull in the Makefile changes and not to add to CI. That decision was made because we realized we would A) have to go back and retroactively fix all the existing spelling issues (I worked on that for a bit and realized it was very big endeavor to sift through) and B) it could cause PRs to fail since sometimes the spellchecks aren't 100% correct.
> > When I cherry-picked this commit initially, I didn't realize I had grabbed those changes as well.
> > I have now pulled out the makefile changes and am just keeping the spelling suggestions.
> > Let me know if you feel it should be done a different way- I've had quite a bit of conversation around this one and there are different opinions. I can definitely pivot!
> 
> Thanks for the explanation. This sounds good, though we may just need to accept things might regress without CI (though this PR still makes things better than they were).

Thank you!! I will keep this in my notes in case we do decide to take the time to fix all of the existing spelling issues and add the CI check.

2023-05-23 19:42 UTC, djyasin commented
@shanemcd does this look okay now?

2023-05-23 20:18 UTC, shanemcd commented
I think it's good to fix these typos, but I also think it would be worthwhile and relatively trivial to add a CI check that runs the utility mentioned in https://github.com/ansible/awx/pull/11439. 

If we're not going to do that here, please open an issue for running spell checking as part of the PR checks. It should probably get added to https://github.com/ansible/awx/blob/devel/.github/workflows/ci.yml. 

You can see there is a pretty well established pattern there. As long as the dependency is installed in the devel image, it will just be a matter of adding a new item to the test [matrix](https://github.com/ansible/awx/blob/daf39dc77ecb75a97f7509ffa58ab76b18f4e8a9/.github/workflows/ci.yml#L19).

2023-05-24 13:21 UTC, djyasin commented
> It should probably get added to https://github.com/ansible/awx/blob/devel/.github/workflows/ci.yml.

Thank you so much for your feedback! I went ahead and made a new issue here: https://github.com/ansible/awx/issues/14039

2023-05-24 13:28 UTC, shanemcd approved these changes

2023-05-24 14:06 UTC, merged