Fix missing controller error within projects.edit.templates
ansible/awx pull request #1323
Opened 2018-02-22 13:53 UTC by pennycoders

related #960

##### SUMMARY

This commit fixes #960 by:
- Defining TemplatesListController for the projects.edit.templates view 
- Defining resolve.resolvedModels within the project-templates route
It also implements the new, expanded view as there was a TODO 
for that within the code. The route now uses the 
awx/ui/client/features/templates/list.view.html file as the 
view template.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 1.0.4.8
```

2018-02-22 18:40 UTC, jlmitch5 reviewed
Thanks for the PR!  Your approach looks great.  Ping me when you update these references and I will pull down and test locally and approve.

2018-02-22 18:40 UTC, jlmitch5 commented on awx/ui/client/features/templates/list.route.js
> +            controller: 'ListController',
This is my bad (not yours), but can you update the reference here to 'TemplateListController' here and in templates/index.js

2018-02-22 18:40 UTC, jlmitch5 commented on awx/ui/client/src/projects/main.js
> +import TemplatesListController from '~features/templates/list-templates.controller';
And update this one to ProjectTemplatesListController

2018-02-24 07:36 UTC, pennycoders commented
Hi @jlmitch5 ,

The PR now has all the changes you have suggested. Should be good to test & merge.

Thanks,

Alex.

2018-03-01 18:46 UTC, jlmitch5 approved these changes
Works good!

There's some styling work in which this list needs to be styled slightly differently.  Feel free to update your PR to do that.

Basically, we need to conditionally not pad and do the border of the list when it is embedded in a form view like this.

We also want to make it so the add dropdown here only shows add for job templates.

We want to do these things conditionally (so that it doesn't affect the standard, job templates list)

https://tower-mockups.testing.ansible.com/mockups/projects/projects-templates/

2018-03-05 00:34 UTC, pennycoders commented
Hi @jlmitch5 ,

All the changes you have requested are now done. Also, there's now a directive which allows you to add directives based on conditions of your choice (rather than simply adjusting the styling based on where the view is shown, the wrapping at-panel is now only shown on the project templates page). I think that is much better compared to just hacking something together for this fix only. The new directive is going to be useless in the future as well. Also, I have noticed two other issues:

* The page was not changing
* The state was not kept when changing the page, as soon as I used the 'updateDataset' event.

Both of these issues are now fixed.

Cheers,

Alex.

2018-03-05 18:58 UTC, jlmitch5 requested changes
@pennycoders Really appreciate you taking a look here.  Conceptually, the use of the standAlone value to conditionally show things in different ways I like a lot.

That being said, invoking a custom pre-compile with the conditionalAttributes directive is a bit of an aggressive step to make the abstraction happen.

I'd update the approach to be a little simpler (albeit a bit more code repetition, but that's easier to maintain than the custom compile and having to move away from the simpler pattern of making all custom components utilize more than the element-specific directive, which is a best practice as it keeps partials clean and easy to mentally parse).

I'm gonna take a look at this and push some updates with the approach I'm thinking of, as I was typing it out,
 and it was difficult to express in terms of something that'd be easily actionable.  Note this might be a few days, as I'm in the middle of tie-ing up some loose ends on some other code.  I apologize about the delay here and really appreciate the effort you have been putting in, just juggling a few different things right now that I need to finish up.

2018-03-05 20:24 UTC, pennycoders commented
Hi @jlmitch5 , 

Well, the reason I have created the conditionalAttributes directive and bound the at-panel, at-panel-* directives to attributes as well was because they were initially bound to attribute names, and I was thinking that it would be better to have something like that implemented, rather than, let's say, split the templates view into partials (Which is an alternative I had in mind), or conditionally remove the styling. With all that said, what would your approach be ? I mean, I just tried to make everything both backwards compatible and with as little of a change as I could, as the contributing guide states. Another way would have been to modify the at-panel directive templates themselves, but in general, I do not think having business logic within the views is generally a good idea, as with time, things will start to look pretty complicated and will eventually become harder and harder to maintain. Could you please explain to me what your approach would be ? I could eventually change the at-panel directive templates to accommodate this change, or split the part inside at-panel into partials, but IMHO, I do not think that this is hard to maintain, as it is just a very broad, generic directive, that can, eventually be reused for a lot of cases similar to this issue.

Thanks,

Alex.

2018-03-11 20:47 UTC, jlmitch5 commented
Hey @pennycoders, (nearly) tied together all the other stuff so I got some time to circle back to this, appreciate your patience and your work on this PR!

> Well, the reason I have created the conditionalAttributes directive and bound the at-panel, at-panel-* directives to attributes as well was because they were initially bound to attribute names, and I was thinking that it would be better to have something like that implemented, rather than, let's say, split the templates view into partials (Which is an alternative I had in mind), or conditionally remove the styling.

So I guess to take a step back.  Some of the goals of the "new" codebase (new being the stuff that is in the features and lib folders as opposed to src) is to make things easier to grok for people who are newer to Angular, as well as not rely too heavily on some of the more "complicated" things AngularJS lets you do (i.e. keep things "loosely coupled").  Ideally, the partial acts as a fairly transparent/easy to mentally consume interface into how the state is configured.

With that being said if we look at the conditonal-attributes directive:

`conditional-attributes="{ 'at-panel-heading' : standAlone }" `

it's fairly obvious that `at-panel-heading` "shows up" based on the truthiness of `standAlone` so that's good, but if we dive in and try to get into what "shows up" means:

```
+        compile: () => ({
+            pre: (scope, element, attr) => {
+                const directives = scope.$eval(attr.conditionalAttributes);
+                compileLoopControl++;
+                if (compileLoopControl >= 10) {
+                    return;
+                }
+                Object.keys(directives).forEach((key) => {
+                    if (directives[key]) {
+                        attr.$set(key, true);
+                    } else {
+                        attr.$set(key, null);
+                    }
+                });
+                attr.$set('conditionalAttributes', null);
+                $compile(element)(scope);
+                compileLoopControl = 0;
+            }
+        })
```

We've got a bunch of complicated AngularJS patterns in use here: the pre-compile step, scope.$eval, $set, $compile.  Using these makes the AngularJS usage of the components pretty tightly coupled (If/when we want to switch from using AngularJS to something else, any component that uses "conditional attributes" is gonna be a bit of a painful process to refactor "conditional-attributes" out because it is tied to all these AngularJS concepts).

I think:

> the templates view into partials (Which is an alternative I had in mind)

Gets pretty close to what I had in mind.  Basically, you could excise the actual list part of the pane into a partial.  And then have the outer pane that the list sits in be a part of a different partial/view.  Something along the lines of having an index.view.html that the templates route (stuff defined in the features directory uses) and a list.view.html which is a sub-view of that index view, and able to be directly injected into the old-style form (might not be exactly like below but this should give the gist of what I'm talking about).

```
<at-panel>
    <at-panel-heading hide-dismiss="true">
        TEMPLATES
        <span class="badge List-titleBadge">
            {{ vm.templatesCount }}
        </span>
    </at-panel-heading>
   <div ui-view="templateList"></div>
</at-panel>
```

```
<at-panel-body>
        <div class="at-List-toolbar">
           ...
        </div>

        <at-list results="applications">
            ...
        </at-list>
```

I'm exploring this pattern (but not taking it all the way as described above ^) with the index.view.html in the [third-party oauth applications crud views I'm working on](https://github.com/jlmitch5/awx-1/tree/bff532af6e210a85f74f43d5fa10dcef24242d31/awx/ui/client/features/applications)

If we can figure out the right abstraction that makes the list placeable within forms that it will need to be a tab in, as well as in the "main" view, that'd really be ideal for moving forward as we continue to move all of our views to the features/lib pattern.

2018-03-12 02:44 UTC, jlmitch5 commented
@pennycoders actually gonna be working the next few days to implement this for the Jobs' view.  Here's the [commit](https://github.com/jlmitch5/awx-1/commit/401a01209b13892d65ae009f43dbe8f7e9a18483) with the scaffolding for that for reference

2018-03-13 19:40 UTC, pennycoders commented
Hi @jlmitch5 ,

Is there any chance we can discuss this on irc or something ? I think I can be of help. I also have a few other ideas / proposals for this project besides this fix.

Cheers,

Alex.

2018-03-16 09:51 UTC, itsmjeu commented
Anyone can inform me what was the last version were this was working or when the fix  will be applied? seems that the lastest version still not have this fixed. 

Thanks again

2018-03-16 12:12 UTC, jlmitch5 commented
Hey @itsmjeu, 1.0.2.

On Fri, Mar 16, 2018 at 5:51 AM itsmjeu <notifications@github.com> wrote:

> Anyone can inform me what was the last version were this was working or
> when the fix will be applied? seems that the lastest version still not have
> this fixed.
>
> Thanks again
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/ansible/awx/pull/1323#issuecomment-373660088>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABR8oBoH-13-RfO65mG1yxGqI5SD2Bg2ks5te4swgaJpZM4SPWMm>
> .
>
-- 
John Mitchell
Front End Developer
Ansible, Inc.
919-394-6667

2018-03-26 15:11 UTC, jlmitch5 commented
@pennycoders can you revert to commit `beda392` and I will approve and we can merge this?

2018-03-26 19:24 UTC, matburt commented
Going to close this in preparation for a release branch, reopen when conflicts are resolved

2018-03-26 19:24 UTC, closed without merging