Only allow promote and stage to run on the awx repo
ansible/awx pull request #13304
Opened 2022-12-07 19:10 UTC by john-westcott-iv

##### SUMMARY

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Other

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2022-12-07 19:11 UTC, jbradberry approved these changes

2022-12-07 19:12 UTC, shanemcd requested changes

2022-12-07 19:12 UTC, shanemcd commented on .github/workflows/promote.yml
> +    if: github.repository == 'ansible/awx'
I don't want to lose the ability to test releases out on our personal forks of AWX. This should probably be:

```
endsWith(github.repository, '/awx') 
```

2022-12-07 21:40 UTC, shanemcd commented on .github/workflows/promote.yml
> +    if: github.repository == 'ansible/awx'
```suggestion
    if: endsWith(github.repository, '/awx') 
```

2023-02-16 13:04 UTC, shanemcd approved these changes

2023-02-16 13:05 UTC, merged