tag awx-ee latest with awx release
ansible/awx pull request #13338
Opened 2022-12-14 17:17 UTC by fosterseth

##### SUMMARY

each time AWX is released, tag quay.io/ansible/awx-ee:latest with the same AWX tag

this allows users to have an image to fallback to in case the lastest breaks their custom EEs

Tagging it with AWX release tags provides a regular cadence, and the tag itself allows users to roughly align awx-ee to awx images.

see https://github.com/ansible/awx-ee/issues/117
and https://github.com/ansible/awx-ee/issues/125

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - API

2022-12-15 23:42 UTC, shanemcd requested changes
See my comment about staging on ghcr.io.

2022-12-15 23:42 UTC, shanemcd commented on .github/workflows/stage.yml
> +          docker push quay.io/ansible/awx-ee:${{ github.event.release.tag_name }}
We shouldn't be pushing straight to quay in the stage workflow. There's already a pattern in place where we use ghcr.io as a staging area, run tests, then if everything succeeds we pull the staged images and _then_ push to quay.

2023-01-11 22:01 UTC, relrod approved these changes
This is awesome!

2023-01-12 02:00 UTC, TheRealHaoLiu approved these changes

2023-01-12 20:07 UTC, rebeccahhh approved these changes
thanks for doing this :)

2023-01-16 04:48 UTC, shanemcd approved these changes
Thanks for making all the requested changes! 🎉

2023-01-20 17:44 UTC, merged