Fix error for byweekday in schedule_rruleset
ansible/awx pull request #13541
Opened 2023-02-09 08:44 UTC by npithonDR

Fix error:
```
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.schedule_rruleset'. Error was a <class 'ansible.errors.AnsibleError'>, original message: In rule 1 byweekday must only contain values in monday, tuesday, wednesday, thursday, friday, saturday, sunday. In rule 1 byweekday must only contain values in monday, tuesday, wednesday, thursday, friday, saturday, sunday"
}
```

with:
```
    - name: Build a complex schedule for every monday using the rruleset plugin
      awx.awx.schedule:
        name: "Test build complex schedule"
        state: present
        unified_job_template: "template name"
        rrule: "{{ query('awx.awx.schedule_rruleset', '2030-04-30 10:30:45', rules=rrules, timezone='Europe/Paris' ) }}"
      vars:
        rrules:
          - frequency: 'day'
            interval: 1
            byweekday: 'monday'
```

##### SUMMARY

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Collection

##### AWX VERSION

```
AWX 21.11.0
```

##### ADDITIONAL INFORMATION

```
Tested with:
- byweekday: 'monday'
- byweekday: 'monday, friday'
- byweekday: monday
```

2023-02-10 18:52 UTC, john-westcott-iv commented
Thank you for your contribution. Could you add additional tests to cover the tested conditions and expected behavior in the following test file? https://github.com/ansible/awx/blob/devel/awx_collection/tests/integration/targets/lookup_rruleset/tasks/main.yml

2023-02-13 08:54 UTC, npithonDR commented
Hello,
I added additional tests

2023-02-15 12:23 UTC, john-westcott-iv approved these changes

2023-02-23 17:09 UTC, AlanCoding commented
This doesn't pass the existing test failure. I don't meant to just scope creep, but the problem comes from the same place in code as what this is fixing, and this doesn't seem to change that code in a way consistent with the intention.

```
TASK [call rruleset with a monthly rule with invalid bymonthday (32)] *****************************************************
task path: /home/alancoding/repos/awx/awx_collection/tests/integration/targets/lookup_rruleset/tasks/main.yml:172
exception during Jinja2 execution: Traceback (most recent call last):
  File "/home/alancoding/repos/ansible/lib/ansible/template/__init__.py", line 831, in _lookup
    ran = instance.run(loop_terms, variables=self._available_variables, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/.ansible/collections/ansible_collections/awx/awx/plugins/lookup/schedule_rruleset.py", line 300, in run
    rrule_kwargs['bymonthday'] = self.process_integer('bymonthday', rule, 1, 31, rule_number)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alancoding/.ansible/collections/ansible_collections/awx/awx/plugins/lookup/schedule_rruleset.py", line 200, in process_integer
    rule[field_name] = rule[field_name].split(',')
                       ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'
fatal: [localhost]: FAILED! => {
    "msg": "An unhandled exception occurred while running the lookup plugin 'awx.awx.schedule_rruleset'. Error was a <class 'AttributeError'>, original message: 'list' object has no attribute 'split'. 'list' object has no attribute 'split'"
}
...ignoring

TASK [assert] *************************************************************************************************************
task path: /home/alancoding/repos/awx/awx_collection/tests/integration/targets/lookup_rruleset/tasks/main.yml:185
fatal: [localhost]: FAILED! => {
    "assertion": "'In rule 2 bymonthday must be between 1 and 31' in results.msg",
    "changed": false,
    "evaluated_to": false,
    "msg": "Assertion failed"
}

PLAY RECAP ****************************************************************************************************************
localhost                  : ok=22   changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=9   
```

I put up https://github.com/npithonDR/awx/pull/1

With that

```
$ ansible-playbook -i localhost, testing/integration.yml -e test=lookup_rruleset > /dev/null  2> /dev/null
$ echo $?
0
```

2023-02-23 17:13 UTC, AlanCoding requested changes
suggested patch in comments. Integration test module passes with that.

2023-02-27 02:18 UTC, AlanCoding approved these changes

2023-02-27 15:24 UTC, merged