fix headless awx build
ansible/awx pull request #13745
Opened 2023-03-23 03:17 UTC by TheRealHaoLiu

##### SUMMARY
headless build of awx end in following error 
```
 => ERROR [builder 12/12] RUN AWX_SETTINGS_FILE=/dev/null SKIP_SECRET_KEY_CHEC  2.1s
------
 > [builder 12/12] RUN AWX_SETTINGS_FILE=/dev/null SKIP_SECRET_KEY_CHECK=yes SKIP_PG_VERSION_CHECK=yes /var/lib/awx/venv/awx/bin/awx-manage collectstatic --noinput --clear:
#19 1.839 Traceback (most recent call last):
#19 1.839   File "/var/lib/awx/venv/awx/bin/awx-manage", line 8, in <module>
#19 1.839     sys.exit(manage())
#19 1.839   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/__init__.py", line 200, in manage
#19 1.840     execute_from_command_line(sys.argv)
#19 1.840   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
#19 1.840     utility.execute()
#19 1.840   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/__init__.py", line 413, in execute
#19 1.840     self.fetch_command(subcommand).run_from_argv(self.argv)
#19 1.840   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 354, in run_from_argv
#19 1.840     self.execute(*args, **cmd_options)
#19 1.840   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/management/base.py", line 398, in execute
#19 1.840     output = self.handle(*args, **options)
#19 1.840   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 187, in handle
#19 1.841     collected = self.collect()
#19 1.841   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 105, in collect
#19 1.841     for path, storage in finder.list(self.ignore_patterns):
#19 1.841   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/contrib/staticfiles/finders.py", line 130, in list
#19 1.841     for path in utils.get_files(storage, ignore_patterns):
#19 1.841   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/contrib/staticfiles/utils.py", line 23, in get_files
#19 1.841     directories, files = storage.listdir(location)
#19 1.841   File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/files/storage.py", line 330, in listdir
#19 1.841     for entry in os.scandir(path):
#19 1.841 FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/awx/venv/awx/lib64/python3.9/site-packages/awx/ui/build/static'
------
executor failed running [/bin/sh -c AWX_SETTINGS_FILE=/dev/null SKIP_SECRET_KEY_CHECK=yes SKIP_PG_VERSION_CHECK=yes /var/lib/awx/venv/awx/bin/awx-manage collectstatic --noinput --clear]: exit code: 1
make: *** [awx-kube-build] Error 1
```

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - Other

##### AWX VERSION

```
awx: 21.13.1.dev105+g0e6f49288a
```

##### ADDITIONAL INFORMATION
test:
```
make clean
HEADLESS=yes make awx-kube-build
```

2023-03-23 03:22 UTC, TheRealHaoLiu commented
```
Traceback (most recent call last):
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/core/handlers/base.py", line 204, in _get_response
    response = response.render()
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/var/lib/awx/venv/awx/lib64/python3.9/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
```

2023-03-23 15:09 UTC, jjwatt approved these changes

2023-03-23 16:00 UTC, john-westcott-iv commented on Makefile
> +dist/$(SDIST_TAR_FILE): ui-headless ui-next/headless
Should we make ui-next/headless a target of ui-headless so that if I run `make ui-headless` from the root folder it will hit both targets?

2023-03-23 16:07 UTC, shanemcd commented
I'd like to understand why this isn't happening in the awx-operator CI check... which builds AWX in headless mode and seems to be passing on other PRs.

2023-03-23 16:10 UTC, shanemcd commented on Makefile
> +	@touch awx/ui/build/static/HEADLESS
What is `awx/ui/build/static/HEADLESS` supposed to do?

2023-03-23 16:13 UTC, shanemcd requested changes
Looking at this code, this command isn't supposed to get run when doing a headless build: https://github.com/ansible/awx/blob/bf98f626540cc0df35b3b044bd99a4cf31613ee8/tools/ansible/roles/dockerfile/templates/Dockerfile.j2#L86-L88

Not sure how you got into this state, but I don't think more cruft in the Makefile is the answer here.

2023-04-07 17:16 UTC, TheRealHaoLiu commented
ok headless build is broken for `make awx-kube-build` bc it's different from what our CI does

2023-04-19 01:46 UTC, TheRealHaoLiu commented
fixed in https://github.com/ansible/awx/pull/13658 bc its literally 1 line

2023-04-19 01:46 UTC, closed without merging