Check user permissions before fetching system settings
ansible/awx pull request #13849
Opened 2023-04-12 15:18 UTC by marshmalien

##### SUMMARY
Only system admins and system auditors can access the settings endpoint, so this PR checks if the user has access before making a `/settings` GET request. This should resolve 403 errors in the instance list and instance details pages.

_Org admin with permission to view instances_
<img width="835" alt="Screenshot 2023-04-12 at 9 44 25 AM" src="https://user-images.githubusercontent.com/15881645/231503360-3b7596c0-3f71-4e5f-9068-f8f05f6fb905.png">

_Org admin without permission to view instances_
<img width="834" alt="Screenshot 2023-04-12 at 9 43 17 AM" src="https://user-images.githubusercontent.com/15881645/231503366-8b344a04-4a27-4c13-97c3-bbb2abd3c012.png">

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - UI

2023-04-17 16:32 UTC, mabashian commented
Here's how I tested this:

1. Create an organization "test"
2. create a "test-admin" user with admin role inside the "test" organization
3. Browse: Administation > Instances

![org_admin_instances](https://user-images.githubusercontent.com/9889020/232551260-63675b1e-5e12-467b-9fe8-cc9cf7e70142.gif)

2023-04-17 16:32 UTC, mabashian approved these changes

2023-04-18 19:19 UTC, akus062381 requested changes
The following shows when the user tries to turn on the tech preview:
![image](https://user-images.githubusercontent.com/63685497/232882491-2f4e738c-1472-4d7a-848b-01fef5cc7b33.png)

2023-04-18 20:41 UTC, akus062381 approved these changes

2023-04-18 20:41 UTC, merged