Adding add_fields and remove_fields on api
ansible/awx pull request #14229
Opened 2023-07-12 08:06 UTC by tanganellilore

##### SUMMARY
This PR is to allow us the possibility to add and/remove fields from API query, simpli adding new query parameters called `add_fields` and `remove_fields`.

This is related discussion with @AlanCoding on #14199 ,  the idea is to have a way to add (or remove) one or more fileds in a api view.
My approach is to allow adding and removing fields via query params, separated by comma for all API, not only for single endpoint. 

In case of `add_fields` we need to evaluate fields, retrieve him models and then create field based on model, so in that way we can extend current field defined in serializer, with all fields present in the model itself.

In all cases (add/remove), if fields requested not exists in the model, we simply skip it.

Some example:
- Add ansible_facts to host view
`http://localhost:8013/api/v2/hosts/?add_fields=ansible_facts`
- Remove related and summary_fields from api view
`http://localhost:8013/api/v2/hosts/?remove_fields=related,summary_fields`
- A combination of add/remove
`http://localhost:8013/api/v2/hosts/?remove_fields=related,summary_fields&add_fields=ansible_facts`

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - API

##### AWX VERSION

```
N/A
```

##### ADDITIONAL INFORMATION

```

```

2023-07-12 18:53 UTC, gamuniz commented
@tanganellilore are you able to add some testing and test scenarios around this?

2023-07-12 19:43 UTC, tanganellilore commented
I can try to do that, but before i refer to have @AlanCoding feedback

2023-07-13 07:40 UTC, tanganellilore commented
fixed one missing fields during my copy...sorry for that

2023-07-18 17:11 UTC, jbradberry commented
@tanganellilore I am philosophically opposed to this approach.  This PR does _way_ too much by being generalized.  The new `add_fields` and `remove_fields` are bypassing any serializer validation, and I could easily imagine this functionality bypassing access control logic.

Like @AlanCoding I'm uneasy with the idea of adding a parallel list view just for your use case.  My suggestion is to add a `show_facts` field to the host serializer and just write the logic to switch on or off showing the facts based on that.

2023-07-18 18:07 UTC, tanganellilore commented
Thanks @jbradberry for your feedback, probably I'm not so expert on this topic but why addind/removing fields that is present in the model used by serialization itself should bypass serialization validation?
I'm not adding something that is not already present on model used by serialization...moreover i skipped all argunent passed if it's not present in model itself. 
(I see in some points that serializer add something outside the model, like lookup, but this is not "allowed" in my implementation) 

For access control logic, I don't have any idea how test it, but i think that access control should be present on api path and method, not in the serializer fields itself. 
 

Can we evaluate to have an "allowed list" for remove/add fields? (just to restrict it). 
To me allow possibility to user to add/remove fields will be a great features, also to ui point of view (we can reduce heavy of data passed to client with removal of unused fields). 

Imagine to have an integration that non require summary_fields or related_fields, or, just my start use case,  integrate current view with something exclude from serializer but present in the model (due to performance issue like adding facts).

Anyway, I'm simply try to address what @AlanCoding asked, but probably

2023-07-19 17:41 UTC, sdktr commented
This seems to built a graphql approach into REST. Was graphql evaluated before in the AWX project?

2023-07-26 19:34 UTC, fosterseth commented
@tanganellilore after some discussion, I think an easier PR to get merged in is going with what @jbradberry proposed. A show_facts query for the Hosts endpoint only. If enabled, add ansible facts to the hosts

would you be able to make those changes? we can just close this PR (to keep it as a reference in case we want to resurrect the idea) and open a new one.

2023-08-03 16:07 UTC, jbradberry requested changes
@tanganellilore 

Bypassing validation:

You are pulling the values of `add_fields` and `remove_fields` directly out of the request.  They could be any value at all and thus ought to be run through serializer fields with some validators first.  Additionally and more seriously, the only concept of "allowlist" here is that they are fields on the model.

Access control:

To the best of my recollection, we have various model fields that are either not allowed or only conditionally allowed to be present in the API.  This PR will bypass any logic we have elsewhere that determines this.  Additionally, I suspect that the machinery that you are making use of here will allow relational fields to be exposed directly.

I would very much prefer to see a more tightly focused PR that only conditionally exposes the facts, nothing else.

2023-08-03 19:02 UTC, tanganellilore commented
Clear @jbradberry,
I will try to submit a new PR to go in direct io suggested by you and @fosterseth.

You can close this PR just for future question about it.

2023-08-09 19:12 UTC, closed without merging