Modified URL includes to be dynamic
ansible/awx pull request #14307
Opened 2023-08-01 23:26 UTC by john-westcott-iv

##### SUMMARY

This PR should have a net 0 affect, it just tidies up the urls.py file by allowing for dynamically including URL files from sub directories rather than having to import and include them. Each URL file can have three variables in it:
 * `extend_urls` - These are appended as is to the url list being extended
 * `urls` - These are imported with a namespace of the file by default. For example, any URLs in a file called 'object.py' would be included as being under `/object/`.
 * `entry_point` - This modifies the namespace used for the `urls` variables from the filename without the .py to this value. Again, using our example of `object.py` if we set `entry_point = 'something'` the urls defined in urls would be added under `/something/`.

##### ISSUE TYPE

 - New or Enhanced Feature
 
##### COMPONENT NAME

 - API
 
##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2023-08-01 23:28 UTC, john-westcott-iv commented on awx/api/urls/urls.py
> +    urls_dir = path.join(path.dirname(inspect.getfile(ApiRootView)), '..', '..', 'api', 'urls', dir_name)
I'm not in love with finding another known class and then going relative down to api/urls. Maybe we just want to import something from awx.api and go from there? Anyone else have another trick?

2023-08-01 23:29 UTC, john-westcott-iv commented on awx/api/urls/urls.py
> +            print(f"Not loading {fully_qualified_module} missing urls or extend_urls")
I should probably change this to a logger instead of just a print.

2024-01-15 20:41 UTC, jbradberry requested changes
Rather than create our own new pattern, I would like to see us make use of the modern Django pattern for this, e.g. `path("whatever/", include("foo.bar"))`.

https://docs.djangoproject.com/en/4.2/topics/http/urls/#including-other-urlconfs

2024-02-14 16:23 UTC, jbradberry commented
Closing due to staleness.

2024-02-14 16:23 UTC, closed without merging