Fix: #14500 Added alt text to images for Userguide: credential_plugins.rst
ansible/awx pull request #14527
Opened 2023-10-02 23:23 UTC by maskboyAvi

##### SUMMARY

Added alt text to images for Userguide: credential_plugins.rst

#14500 
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Docs

##### AWX VERSION

Latest

##### ADDITIONAL INFORMATION

Please add Hacktoberfest label to the PR. Thank You.

```

```

2023-10-03 14:46 UTC, gundalow requested changes
/home/runner/work/awx/awx/docs/docsite/rst/userguide/credential_plugins.rst:51: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/runner/work/awx/awx/docs/docsite/rst/userguide/credential_plugins.rst:60: WARNING: Explicit markup ends without a blank line; unexpected unindent.

2023-10-03 14:50 UTC, oraNod approved these changes
LGTM. Thanks @maskboyAvi

2023-10-03 14:54 UTC, maskboyAvi commented
> /home/runner/work/awx/awx/docs/docsite/rst/userguide/credential_plugins.rst:51: WARNING: Explicit markup ends without a blank line; unexpected unindent. /home/runner/work/awx/awx/docs/docsite/rst/userguide/credential_plugins.rst:60: WARNING: Explicit markup ends without a blank line; unexpected unindent.

I will Fix the code ASAP.

2023-10-03 15:29 UTC, maskboyAvi commented
@gundalow I have made the requested changes. Please check once ;)

2023-10-03 18:00 UTC, gundalow approved these changes
Thank you so much for doing these :)

2023-10-05 16:50 UTC, oraNod approved these changes

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Applications - Button for managing key-related operations.
```suggestion
   :alt: Icon for managing external credentials
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Prompt for linking a credential field to Centrify Vault.
```suggestion
   :alt: Credential section of the external secret management system dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Prompt for credential metadata
```suggestion
   :alt: Metadata section of the external secret management system dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Credentials link metadata Test Error
```suggestion
   :alt: Example exception dialog for credentials lookup
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a Centrify Vault Credential Provider Lookup credential.
```suggestion
   :alt: Example new centrify vault credential lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a configured CyberArk credential.
```suggestion
   :alt: Example new CyberArk vault credential lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of CyberArk Conjur Secrets Manager Lookup credential.
```suggestion
   :alt: Example new CyberArk Conjur Secret lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a configured HashiCorp Vault Secret Lookup credential.
```suggestion
   :alt: Example new HashiCorp Vault Secret lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a configured HashiCorp Vault Signed SSH credential.
```suggestion
   :alt: Example new HashiCorp Vault Signed SSH credential lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a configured Microsoft Azure Key Vault credential.
```suggestion
   :alt: Example new Microsoft Azure Key Vault credential lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a configured Thycotic DevOps Secrets Vault credential.
```suggestion
   :alt: Example new Thycotic DevOps Secrets Vault credential lookup dialog
```

2023-10-05 16:50 UTC, oraNod commented on docs/docsite/rst/userguide/credential_plugins.rst
> +   :alt: Example of a configured Thycotic Secret Server credential.
```suggestion
   :alt: Example new Thycotic Secret Server credential lookup dialog
```

2023-10-05 20:19 UTC, tvo318 approved these changes
Looks great, thanks @maskboyAvi 👍

2023-10-06 20:53 UTC, merged