Fix: #14510 Add alt-text codeblock to Images for Userguide: jobs.rst
ansible/awx pull request #14530
Opened 2023-10-03 13:32 UTC by maskboyAvi

##### SUMMARY

Added the Alt tags for all images in Userguide: jobs.rst 

related #14510 
##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Docs

##### AWX VERSION

Latest

##### ADDITIONAL INFORMATION

Please Add Hacktoberfest label to the PR. Thank You.

2023-10-03 22:00 UTC, tvo318 requested changes
Thank you for working on adding these alt texts, @maskboyAvi.

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +                                  :alt: Jobs List with Example Job
This should really read, "Jobs List with Example Jobs" since there are multiple jobs.

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +   :alt: Filter Options in Job Details
This should read, "Filter options in the Jobs Output window"

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +   :alt: Filter Examples in Job Details
This should read, "Selected filter examples from the Jobs Output window"

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +   :alt: Job Details for Inventory Sync
This should read, "Job Output for Playbook Job Run"

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +   :alt: Host Summary in Job Standard Output
This should read, "Events summary in Job Output"

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +   :alt: Filter Failed Jobs
This should read, "Example of errored jobs filtered by unreachable hosts"

2023-10-03 22:00 UTC, tvo318 commented on docs/docsite/rst/userguide/jobs.rst
> +   :alt: JSON Output Tab
This should read, "Example of Job details for a Playbook run"

2023-10-03 22:31 UTC, maskboyAvi commented
@tvo318 I will fix the code asap and sorry for so many mistakes.

2023-10-03 23:32 UTC, maskboyAvi commented
@tvo318 I have made the requested changes. Please check once . Thank You :)

2023-10-05 13:09 UTC, maskboyAvi commented
@tvo318 Please check the requested changes. Thank you :)

2023-10-05 17:39 UTC, oraNod approved these changes

2023-10-06 18:05 UTC, maskboyAvi commented
@tvo318 Please check the requested changes. Thank you for your time.

2023-10-09 22:40 UTC, tvo318 approved these changes
Looks good, thanks for making these changes!

2023-10-09 22:40 UTC, merged