docs: Update teams.rst
ansible/awx pull request #14539
Opened 2023-10-03 21:44 UTC by ro4i7

##### SUMMARY

solved: #14520
solved under hacktoberfest 2023

##### ISSUE TYPE

 - Breaking Change 
 - New or Enhanced Feature
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API
 - UI
 - Collection
 - CLI
 - Docs
 - Other

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2023-10-04 03:43 UTC, ro4i7 commented
@tvo318 please check this

2023-10-05 04:53 UTC, tvo318 requested changes
Suggested a few alt text revisions... Also, please amend your final commit to do the DCO signoff per the [Contributor's Guide guidelines](https://ansible.readthedocs.io/projects/awx/en/latest/contributor/work_items.html#things-to-know-prior-to-submitting-revisions)? To do this:
1. Do a git commit --signoff
2. Then push the new commits to your branch

Thanks again for your valuable contributions!

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Teams Page
Can we be more descriptive? maybe something helpful to someone with limited sight would be, "Teams page containing a list of teams and the organizations they belong to."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Users List
I suggest something more descriptive along these lines:
"Teams list showing the Access tab displaying a list of users and their roles."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Disassociate Button
I suggest something more descriptive along these lines:
"Access tab with list of users and an arrow pointing to the disassociate button next to a user's role."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Permissions List
I suggest something more descriptive along these lines:
"Permissions list with resource names, type and their associated roles."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Permissions Templates Select
This implies it is just for templates. I suggest something like:
"Add Teams Permissions Wizard step 2, choose the resources from the list."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Permissions Template Roles
I suggest something like:
"Add Teams Permissions Wizard step 3, choose the roles to apply to the previously selected resource."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
Missing image after Step 1: teams-users-add-permissions-form.png. 
I suggest something like:
"Add Teams Permissions Wizard step 1, choose the resource type."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
>  5. Click **Save** when done, and the Add Permissions Wizard closes to display the updated profile for the user with the roles assigned for each selected resource.
Found a typo in original text - Should be "...updated profile for the team with the roles assigned..."

2023-10-05 04:53 UTC, tvo318 commented on docs/docsite/rst/userguide/teams.rst
> +   :alt: Updated Profile
I suggest something like:
"Updated profile for each team's resources and their roles."

2023-10-09 22:53 UTC, tvo318 commented
@ro4i7 - can you address these changes, please? If not I'll update your PR with my own changes. thanks!

2023-10-16 23:41 UTC, tvo318 approved these changes
Thanks @ro4i7 for your contributions. I've added my own commits to yours and went ahead and approved it!

2023-10-17 20:16 UTC, merged