Add alt text for image directives in job_templates.rst
ansible/awx pull request #14548
Opened 2023-10-06 10:07 UTC by kishan3

Fixes #14509

##### SUMMARY
Added alt test for image directives in job_templates.rst

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Docs

2023-10-10 06:17 UTC, kishan3 commented
Hi @tvo318 can you please check my PR if anything required?

2023-10-10 10:47 UTC, oraNod commented
Hi @kishan3 Thanks for the contribution!

Can you please amend your final commit to do the DCO signoff per the [Contributor's Guide guidelines](https://ansible.readthedocs.io/projects/awx/en/latest/contributor/work_items.html#things-to-know-prior-to-submitting-revisions)?

1. ``git commit --signoff``
2. Push to your branch

2023-10-13 07:01 UTC, kishan3 commented
Hi @tvo318 @oraNod I updated PR with signoff commit.

2023-10-13 23:27 UTC, tvo318 requested changes
Looks pretty good, just a couple minor inputs. Thanks for contributing!

2023-10-13 23:27 UTC, tvo318 commented on docs/docsite/rst/userguide/job_templates.rst
> +    :alt: Job templates - create new job template
"Job template with Privilege Escalation checked from the Options field."

2023-10-13 23:27 UTC, tvo318 commented on docs/docsite/rst/userguide/job_templates.rst
> +    :alt: Configure AWX jobs fact cache timeout
"Jobs Settings window showing the location of the Per-Host Ansible Fact Cache Timeout parameter from the Edit Details screen."

2023-10-19 20:00 UTC, tvo318 approved these changes
Looks awesome, thank you for your contribution, @kishan3 🎉

2023-10-19 20:24 UTC, merged