Fix export with system auditor user
ansible/awx pull request #14626
Opened 2023-11-03 18:23 UTC by tanganellilore

##### SUMMARY
If we use a system auditor user to export elements like schedules or worklows (that have schedule) we receive a general error from awx.awx.module (because is wrapped and is not clear what is behind).

Going down in the error itself I notice that issue was the `Insufficient privileges on %s, inferring POST fields from description.` and in the `parse_description` function that is called whtn POST action is not visible to "unpriviledge" user.

Inside the `parse_description` i notice that argument passed is referring to `desc[desc.index('POST') :]` but if the description of API not have any POST section (like schedule) extraction go in error.

I think that we can check if `POST` is present in the description and if not use the description itself to extract required data.

Otherwhise is better to return an error to end user (or add the POST descriptio where is missing)

Let me know if i need to modify something

##### ISSUE TYPE
- Bug, Docs Fix or other nominal change

##### COMPONENT NAME
- API
 - Collection
 - CLI
 
##### AWX VERSION
```
23.3.1
```

##### ADDITIONAL INFORMATION

```

```

2023-12-14 16:04 UTC, chrismeyersfsu commented
Hey @tanganellilore thanks for the bug issues and the follow up PR, it helps me get up to speed on the issue.

I think what you have here is better than before so I'm good with approving and merging it. I'll note that it does not fix the underlying issue, but that issue is harder to fix.

2023-12-14 16:04 UTC, chrismeyersfsu submitted a review, later dismissed

2023-12-15 20:48 UTC, chrismeyersfsu commented
Digging into this further. This PR avoids the error in question but the fields are not discovered correctly from the description text blob. Below is what an successful export of the schedule roughly looks like with an admin user vs system auditor.

### Admin user
```
{
  "rrule": "DTSTART:20151117T050000Z RRULE:FREQ=DAILY;INTERVAL=1;COUNT=1",
  "name": "test-sched",
  "description": "",
  "extra_data": {},
  "scm_branch": null,
  "job_type": null,
  "job_tags": null,
  "skip_tags": null,
  "limit": null,
  "diff_mode": null,
  "verbosity": null,
  "execution_environment": null,
  "forks": null,
  "job_slice_count": null,
  "timeout": null,
  "enabled": true,
  "inventory": {
    "organization": {
      "name": "Default",
      "type": "organization"
    },
    "name": "test-inv",
    "type": "inventory"
  },
  "unified_job_template": {
    "organization": {
      "name": "Default",
      "type": "organization"
    },
    "name": "test-jt",
    "type": "job_template"
  },
  "related": {
    "credentials": []
  },
  "natural_key": {
    "unified_job_template": {
      "organization": {
        "name": "Default",
        "type": "organization"
      },
      "name": "test-jt",
      "type": "job_template"
    },
    "name": "test-sched",
    "type": "schedule"
  }
}
```

### System Auditor
```
{
  "assets": {
    "schedules": [
      {
        "related": {
          "credentials": []
        },
        "natural_key": {
          "unified_job_template": {
            "organization": {
              "name": "Default",
              "type": "organization"
            },
            "name": "test-jt",
            "type": "job_template"
          },
          "name": "test-sched",
          "type": "schedule"
        }
      }
    ]
  },

```

2023-12-16 08:09 UTC, tanganellilore commented
Nice highligtht.
My opinion is to have an export fully compatibile with system Auditore role, not only partial.

Probably is required some more changes on api level, but better approach.

Fields are missing because are not present in the description and system Auditore user is not able to see post method.

This happen on all api that require extract io of post method

2023-12-18 17:02 UTC, chrismeyersfsu commented
I share your goal. I wonder why we require POST data and fields when doing an `export`. I would have thought we should rely on the `GET` data and fields.

2023-12-18 18:14 UTC, tanganellilore commented
Yes, this nlis not clear to me.... I checked the conde and probably the reason is related to check the permission and/or role and /or reuse some function.

Tomorrow if i have time I will check if i can change Thi beaviour

2023-12-18 21:52 UTC, jbradberry commented
@chrismeyersfsu @tanganellilore the POST fields were needed because we provide a number of read-only fields, and my goal when writing this functionality was to avoid loading up the output with extraneous data.  Maybe it's ok to fall back to just dumping everything (I don't see much reason to hit OPTIONS if POST isn't going to do the job)...?  But how then are you going to distinguish the case when the exporting user legit doesn't have access to the resources?

2023-12-18 22:05 UTC, jbradberry commented
Rummaging through the code now, I'll document the sharp edges I see here:

2023-12-19 06:57 UTC, tanganellilore commented
@jbradberry you are correct, your post remeber me when i digging into the code ans see why it's used post instead get .

The question now could be... Why we need to "hide" the post key in options to user that is read only like system auditor?

2023-12-19 15:13 UTC, jbradberry commented
> @jbradberry you are correct, your post remeber me when i digging into the code ans see why it's used post instead get .
> 
> The question now could be... Why we need to "hide" the post key in options to user that is read only like system auditor?

It's a good point, I was thinking myself that we're conflating two things: metadata about the fields and permissions for the current user.  It'd be nice to decouple them, but I'll point out that any changes we make to the API won't entirely remove the headaches for us since there is an expectation that different versions of the CLI can work with different versions of the API.  The same holds (but worse, since devs frequently forget that we need to keep awxkit in sync with changes in the API) if we solve this problem by hard-coding information in awxkit about what fields are important.

2023-12-19 18:00 UTC, chrismeyersfsu commented
> It's a good point, I was thinking myself that we're conflating two things: metadata about the fields and permissions for the current user. It'd be nice to decouple them

:+1: Philosophically I share this view and direction.

> * some foreign keys are required on import, and that info is in the POST fields (awxkit/api/pages/api.py, L114-5)
> * POST fields are used to distinguish between create-only and attach api relational endpoints

Hmm, this changes my mental model. I was considering export in isolation, but it seems that when I think about export I need to think about import at the same time.

Am I correct that the two reasons I quoted from you above is why we can't simply fall back to getting the fields from `GET` after we try `POST` ?

2023-12-19 18:46 UTC, jbradberry commented
@chrismeyersfsu yeah, I think those are the critical reasons.

2024-01-15 20:05 UTC, jbradberry approved these changes
I think this is fine.

2024-02-07 16:00 UTC, jbradberry requested changes
@tanganellilore Can you please update `awx_collection/test/awx/test_export.py::test_export_system_auditor`?  Your changes are making the test fail, since it presumes that exporting as a system auditor will fail.  We're also getting a linting failure.

2024-02-07 20:32 UTC, TheRealHaoLiu approved these changes

2024-02-07 20:40 UTC, jbradberry approved these changes
I went ahead and pushed some quick fix commits that I think will pass CI.  Will merge if so.

2024-02-07 20:55 UTC, merged