Added the :alt: attribute
ansible/awx pull request #14685
Opened 2023-11-23 18:06 UTC by Dule-martins

##### SUMMARY

Added the :alt: attribute to display alt text for all image

related #14505 

##### ISSUE TYPE

 - Bug, Docs Fix, or other nominal change

##### COMPONENT NAME

 - Docs

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2023-12-06 17:06 UTC, gundalow requested changes
Thanks for this, just a couple of minor suggestions

2023-12-06 17:06 UTC, gundalow commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories constructed invontory venn
```suggestion
   :alt: Inventories constructed inventory Venn diagram
```

2023-12-06 17:06 UTC, gundalow commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories constructed inventory details
```suggestion
   :alt: Constructed inventory details
```

2023-12-06 17:06 UTC, gundalow commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories create new create new inventory
```suggestion
   :alt: Create new create new inventory
```

2023-12-06 17:06 UTC, gundalow commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Select instance groups modal
```suggestion
   :alt: Select instance groups dialogue
```

2023-12-15 00:21 UTC, tvo318 requested changes
Thank you for your contributions, @Dule-martins! 👍 I've made some minor wording suggestions so they are more descriptive when a screen reader reads to a user who has difficulty viewing the images.

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories smart create filter highlighted
Suggested rewording to sound more natural: "Create smart inventory window with Smart host filter highlighted"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories smart define host filter
Suggested wording: "Host filter with drop-down menu options"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories smart define host filter facts
Suggested wording: "Example of an advanced search for host filter ansible facts"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Second inventories smart define host filter facts
Suggested wording: "Selected search criteria for host filter ansible facts listed below search field"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories smart create filter added
Suggested wording: "Specified search criteria for host filter ansible facts shown in the Smart host filter field of the Create new smart inventory window"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories smart create details
Suggested wording: "Details tab of the new Smart Inventory displaying the specified ansible facts in the Smart host filter field"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories smart define host filter facts group
Suggested wording: "Specified search criteria consisting of host filter ansible facts and groups listed below search field"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories constructed inventory Venn diagram
Suggested wording: "Venn diagram describing the input inventory content for a constructed inventory"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Create new create new inventory
Suggested wording: "Create new inventory form"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Create new inventory
Suggested wording: "Example Create new inventory form filled out"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventores manage group add
Suggested wording: "Create new group form for inventories"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add group subgroup
Suggested wording: "Related Groups tab of the Groups form for inventories"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add group existing subgroup
Suggested wording: "Existing group appearing in a separate selection window"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories group delete root with children
Suggested wording: "Delete group confirmation dialog box with a prompt to select whether to delete all groups and hosts or promote child groups and hosts"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add group host
Suggested wording: "Hosts tab of the Groups window showing available hosts"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add existing host
Suggested wording: "Existing host appearing in a separate selection window"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add group host emphasized
Just host, not group host, despite the image name.

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add group host details
Suggested wording: "Host details tab for the selected inventory"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +       :alt: Inventories add group hosts add groups
Suggested wording: "Select Groups dialog showing two available groups"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories add host view completed jobs
Suggested wording: "Jobs tab showing list of completed jobs associated with the selected host"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories create source
Suggested wording: "Create new source form for inventory source"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +       :alt: Inventories create source with notification tab
Suggested wording: "Notification tab for the inventory source"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: Inventories view source
Suggested wording: "Sources tab of the inventory showing one inventory source"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +       :alt: Inventories create source sourced from project filter
Suggested wording: "Inventory file field of the Sourced from a project inventory type"

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +     :alt: Inventories create source rhaap example
Spell out rhaap ("Red Hat Ansible Automation Platform")

2023-12-15 00:21 UTC, tvo318 commented on docs/docsite/rst/userguide/inventories.rst
> +   :alt: ad hoc inventory run command ee
Suggested wording: "Ad Hoc Run command dialog prompting for Execution Environments with two listed to choose from"

2024-07-23 05:07 UTC, closed without merging

2024-07-23 05:10 UTC, tvo318 commented
Closed this PR and re-opened new PR (#15394) with all the changes suggested.