Email with custom notifications not working
ansible/awx pull request #14839
Opened 2024-02-02 15:43 UTC by dmzoneill

##### SUMMARY
This targets "Email with custom notifications not working"
related #13983 

This checks for blank body and add templates errors for the user.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - API

2024-02-13 19:01 UTC, jbradberry commented on awx/main/models/notifications.py
> +                msg += '\n'.join(traceback.format_exception(None, e, e.__traceback__))
This is not going to work in the way that you expect.

```
In [1]: try:
   ...:     raise Exception("foo")
   ...: except Exception as e:
   ...:     msg = e
   ...:     msg += "bar"
   ...: 
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
      1 try:
----> 2     raise Exception("foo")
      3 except Exception as e:

Exception: foo

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
      3 except Exception as e:
      4     msg = e
----> 5     msg += "bar"

TypeError: unsupported operand type(s) for +=: 'Exception' and 'str'
```

2024-02-13 19:20 UTC, TheRealHaoLiu commented on awx/main/models/notifications.py
> +                msg = e  # __str__
what does `# __str__` do?

2024-02-13 19:30 UTC, jbradberry commented on awx/main/models/notifications.py
> +                msg = e  # __str__
Nothing.

2024-02-13 19:36 UTC, jbradberry commented on awx/main/models/notifications.py
> +                msg += '\n'.join(traceback.format_exception(None, e, e.__traceback__))
Also, using `+=` to build up strings is an anti-pattern in Python.  I'd instead suggest something like

```
msg = '\n'.join([
    str(e),
    ...whatever...
])
```

2024-02-13 19:39 UTC, jbradberry requested changes
The concept seems good, but the exception handling is broken as-is.

2024-02-14 15:49 UTC, jbradberry approved these changes

2024-02-14 15:49 UTC, merged