add Azure config dump
ansible/awx pull request #15134
Opened 2024-04-23 20:19 UTC by jessicamack

##### SUMMARY

dump_auth_config will now also dump Azure AD config data.

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - Other

##### AWX VERSION

```
awx: 24.2.1.
```

##### ADDITIONAL INFORMATION

if Azure AD is not configured
```
    {
        "AZURE_missing_fields": [
            "KEY"
        ]
    }
```
if Azure AD is configured
```
    {
        "type": "ansible_base.authentication.authenticator_plugins.azuread",
        "name": "AZUREAD",
        "enabled": true,
        "create_objects": true,
        "users_unique": false,
        "remove_users": true,
        "configuration": {
            "CALLBACK_URL": "https://towerhost/sso/complete/azuread-oauth2/",
            "KEY": "b380e716-01ae-11ef-8fb0-0242ac140004",
            "SECRET": "test"
        }
    }
```

2024-05-30 20:08 UTC, jbradberry commented on awx/main/management/commands/dump_auth_config.py
> +            awx_azure_enabled, azure_missing_fields = self.is_enabled(awx_azure_settings, self.DAB_AZURE_AUTHENTICATOR_KEYS)
I see that `is_enabled` is a method that is already established prior to this PR, but I'm concerned that it treats an explicit `None` the same as a missing key/value.  Worse, now that I'm thinking of it, any explicit value that evaluates as false-like.  This is IMO a bug waiting to happen.

2024-05-30 20:11 UTC, jbradberry commented on awx/main/management/commands/dump_auth_config.py
> +            awx_azure_enabled, azure_missing_fields = self.is_enabled(awx_azure_settings, self.DAB_AZURE_AUTHENTICATOR_KEYS)
The way I'd deal with it:

- establish a module variable `MISSING = object()`
- condition becomes `if required and settings.get(key, MISSING) is MISSING:`

2024-05-30 20:15 UTC, jbradberry requested changes
See my comments.

2025-04-02 14:12 UTC, djyasin commented
Closing this PR as it will need to be re-implemented at this point.

2025-04-02 14:13 UTC, closed without merging

2025-04-02 14:26 UTC, tvo318 commented
Closing these series of PRs.. @jessicamack is unable to reproduce "potential error" - This branch is still available if needed to reopen in the future.