Add check_instance_ready management command
ansible/awx pull request #15238
Opened 2024-05-30 20:09 UTC by TheRealHaoLiu

##### SUMMARY
- throw exception and return 1 if instance not ready
- return 0 if ready

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - API

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2024-05-30 20:20 UTC, jbradberry requested changes

2024-05-30 20:20 UTC, jbradberry commented on awx/main/management/commands/check_instance_ready.py
> +            raise Exception('Instance is not ready')  # so that return code is not 0
The correct way to exit out of Django commands with a failure is to raise `CommandError` (from `django.core.management.base`)

2024-05-30 20:53 UTC, fosterseth commented on awx/main/management/commands/check_instance_ready.py
> +
```suggestion
from django.core.management.base import CommandError
```

2024-05-30 20:54 UTC, fosterseth commented on awx/main/management/commands/check_instance_ready.py
> +            raise Exception('Instance is not ready')  # so that return code is not 0
```suggestion
            raise CommandError('Instance is not ready')  # so that return code is not 0
```

2024-05-31 13:03 UTC, TheRealHaoLiu commented
Thx for the review. Incorporated the suggestion plz rereview

2024-05-31 13:24 UTC, jbradberry approved these changes

2024-05-31 13:29 UTC, merged