Prevent assigning credential to user of other org
ansible/awx pull request #15296
Opened 2024-06-25 02:40 UTC by fosterseth

##### SUMMARY

requires https://github.com/ansible/django-ansible-base/pull/490

Utilizes the `validate_role_assignment` callback from dab (see dab PR #490) to prevent granting credential access to a user of another organization.

This logic will work for role_user_assignments and role_team_assignments endpoints.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API

2024-06-25 17:50 UTC, AlanCoding commented on awx/main/models/credential/__init__.py
> +            if actor.is_superuser or self.organization in actor.organizations:
`actor.organizations` is only coherent if it's a team.

2024-06-25 18:00 UTC, AlanCoding commented on awx/main/models/credential/__init__.py
> +            if actor.is_superuser or self.organization in actor.organizations:
`actor.organizations` wasn't correct, and it was my fault. https://github.com/ansible/awx/pull/15298

2024-06-26 18:48 UTC, AlanCoding requested changes
We should add a unit test for this. Considering it now has 2 dependent patches, I would not feel comfortable merging without that as added verification. Otherwise we should be good.

2024-06-27 02:46 UTC, AlanCoding commented on awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py
> +    # can assign credential to superuser
Never really thought about this case, also don't think I care either way.

2024-06-27 02:47 UTC, AlanCoding approved these changes

2024-06-27 02:54 UTC, fosterseth commented
CI should be re-ran once https://github.com/ansible/django-ansible-base/pull/490 is merged

2024-06-27 13:33 UTC, AlanCoding commented
I previously rebased this (using github). Checks failed due to stale image. I rebuilt the image and restarted the check (without modifying patch) just now. I am expecting a pass, but we'll see.

2024-06-27 14:31 UTC, AlanCoding commented
I know the image has rebuilt, but locally, I pulled it and got a version from 19 hours ago (which is too old) and confirmed it has this commit:

https://github.com/ansible/django-ansible-base/commit/8eab0c06bfee9c1ad29661bbaa373a19a6fe7525

And if that's what the checks are using (which it could be) then that would be why it's failing.

2024-06-28 15:13 UTC, AlanCoding commented
https://github.com/ansible/awx/pull/15308 was merged to freshen up the images and address the issue with CI here.

2024-07-01 19:00 UTC, AlanCoding commented
With the latest test failure, I think we're seeing a conflict of expectations with what I did in https://github.com/ansible/awx/pull/15298

What I merged there considered _indirect_ "member" permission to an organization. We have faced this in a couple of circumstances, and according to the logic of indirect access, the superuser has "member" permission to all organizations. However (and I hit this in other places as well), people are confused about listing superuser as a member of all organizations.

Consulting the prior expectations, I think it would give a 400 even if the user in question was a superuser (who was not a _direct_ member of the organization).

2024-07-01 19:01 UTC, AlanCoding commented
Link related issue https://github.com/ansible/awx/pull/15296#issuecomment-2200819511

2024-07-02 18:56 UTC, AlanCoding commented
```diff
diff --git a/awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py b/awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py
index c54f5677cb..5bc4244fa3 100644
--- a/awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py
+++ b/awx/main/tests/functional/dab_rbac/test_dab_rbac_api.py
@@ -134,9 +134,8 @@ def test_assign_credential_to_user_of_another_org(setup_managed_roles, credentia
     assert "You cannot grant credential access to a User not in the credentials' organization" in str(resp.data)
 
     # can assign credential to superuser
-    rando.super_user = True
+    rando.is_superuser = True
     rando.save()
-    assert organization not in rando.organizations
     post(url=url, data={"user": rando.id, "role_definition": rd.id, "object_id": credential.id}, user=admin_user, expect=201)
 
     # can assign credential to org_member
```

This brings it from failing to passing. We are pretty well agreed that this is acceptable, and is the same as before.

2024-07-02 19:10 UTC, AlanCoding approved these changes

2024-07-02 21:05 UTC, merged