Fallback to use subscription cred for analytic upload
ansible/awx pull request #15479
Opened 2024-08-29 17:56 UTC by TheRealHaoLiu

##### SUMMARY
Fall back to use SUBSCRIPTION_USERNAME/PASSWORD to upload analytic to if REDHAT_USERNAME/PASSWORD are not set

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2024-08-29 20:03 UTC, matburt commented on awx/main/analytics/core.py
> +        logger.error('Either REDHAT_USERNAME nor SUBSCRIPTIONS_USERNAME are set')
Can you say this a different way 😆

2024-08-29 20:04 UTC, matburt requested changes
Possible to add a test?

2024-08-29 20:07 UTC, TheRealHaoLiu commented on awx/main/analytics/core.py
> +        logger.error('Either REDHAT_USERNAME nor SUBSCRIPTIONS_USERNAME are set')
Either vs Neither always gets me...

2024-08-30 03:13 UTC, TheRealHaoLiu commented
Added test please rereview

2024-08-30 03:35 UTC, matburt approved these changes
Awesome work @TheRealHaoLiu

2024-08-30 08:39 UTC, pb82 commented
thanks @TheRealHaoLiu and @matburt , will merge and backport

2024-08-30 08:39 UTC, merged