Removal of Third Party Auth
ansible/awx pull request #15571
Opened 2024-10-02 18:10 UTC by jessicamack

##### SUMMARY

As referenced here: https://forum.ansible.com/t/transitioning-authentication-and-authorization-rbac-to-the-new-awx-architecture

##### ISSUE TYPE

 - Breaking Change 

##### COMPONENT NAME

 - API
 - UI
 - Collection
 - CLI
 - Docs
 - Other

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

2024-10-03 20:57 UTC, hakbailey requested changes
In addition to the inline comments, we should remove the [part of the requirements README that references social-auth-app-django](https://github.com/ansible/awx/blob/feature_3rd-party-auth-removal/requirements/README.md#social-auth-app-django), which has been removed.

2024-10-03 20:57 UTC, hakbailey commented on awx/api/views/__init__.py
> +        if 'ansible_base.authentication' in getattr(settings, "INSTALLED_APPS", []):
I still think we want to remove this entire view, as a view in AWX listing single-sign-on endpoints no longer makes sense.

2024-10-03 20:57 UTC, hakbailey commented on docs/docsite/rst/release_notes/known_issues.rst
> -   pair: known issues; LDAP authentication
We should also remove these two below:
```
   pair: known issues; login problems with social authentication
   pair: known issues; OAuth account recreation
```

2024-10-07 13:54 UTC, TheRealHaoLiu commented on pre-commit.sh
> +# fi
please revert this change

2024-10-14 13:25 UTC, hakbailey approved these changes

2024-10-15 17:01 UTC, chrismeyersfsu commented
I see sso app migrations deleted. I can see this working for a new install but does it break upgrading?

I looked for, but didn’t find, the deletion of the sso app from the Django app list. On mobile right now, going to look again on the desktop and update my comment.

2024-10-15 18:18 UTC, chrismeyersfsu approved these changes

2024-10-15 21:43 UTC, merged