cli: fix `TypeError` in `HelpfulArgumentParser` for python 3.13.1
ansible/awx pull request #15692
Opened 2024-12-06 18:11 UTC by mhassan1

##### SUMMARY

This PR adds logic to `HelpfulArgumentParser` to handle `_parse_known_args` with either 3 (Python 3.13.0 and below) or 4 (Python 3.13.1 and above) positional arguments.

Resolves https://github.com/ansible/awx/issues/15687.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - CLI

##### AWX VERSION
```
awx: 0.1.dev34249+g91bb012
```

##### ADDITIONAL INFORMATION
N/A

2025-01-03 15:44 UTC, mhassan1 commented
@AlanCoding Please take a look, when you have a moment. Thanks.

2025-01-29 16:46 UTC, djyasin commented
Hi @mhassan1! Thank you for your contribution. We have updated your branch so that we can run our CI Checks on this.

2025-01-29 23:48 UTC, mhassan1 commented
@djyasin I have pushed up a linting fix. I'm not sure what to do about the Code Coverage violation, since it's related to Python version; any suggestions?

2025-03-10 03:42 UTC, qgong commented
Hi, when could we merge this MR?

2025-04-09 20:57 UTC, netopsengineer commented
@djyasin could you provide an update on when this might be merged, or what @mhassan1 needs to do to get it moving again?

2025-05-15 16:26 UTC, thedoubl3j approved these changes
While I am not 100% happy with this, I am not against it either. ping @fosterseth to have a look as well.

2025-05-16 19:28 UTC, fosterseth commented
I think I'd rather just get rid of this _parse_known_args method altogether. I think that would fix it for all version of python

```diff
diff --git a/awxkit/awxkit/cli/utils.py b/awxkit/awxkit/cli/utils.py
index 61c2fe8f5e..9e6b5d38ff 100644
--- a/awxkit/awxkit/cli/utils.py
+++ b/awxkit/awxkit/cli/utils.py
@@ -40,14 +40,6 @@ class HelpfulArgumentParser(ArgumentParser):
         self._print_message('\n')
         self.exit(2, '%s: %s\n' % (self.prog, message))
 
-    def _parse_known_args(self, args, ns):
-        for arg in ('-h', '--help'):
-            # the -h argument is extraneous; if you leave it off,
-            # awx-cli will just print usage info
-            if arg in args:
-                args.remove(arg)
-        return super(HelpfulArgumentParser, self)._parse_known_args(args, ns)
-
 
 def color_enabled():
     return _color.enabled
```

the method appears to only chop off `-h` or `--help`, which actually has some negative side affects. Namely, you can't type a command with some args, then just append `--help` at the end to get the help text

e.g. current behavior
```
sbf@fedora:~/awx$ awx -f json --conf.host test --help
Invalid URL 'test/api/': No scheme supplied. Perhaps you meant https://test/api/?
```

with the diff applied

```
sbf@fedora:~/awx$ awx -f json --conf.host test --help
usage: awx [--help] [--version] [--conf.host https://example.awx.org] [--conf.token TEXT] [--conf.username TEXT] [--conf.password TEXT] [-k] [-f {json,yaml,jq,human}] [--filter TEXT] [--conf.color BOOLEAN] [-v] resource ...
blah
blah
```

@mhassan1 would you update the PR to just remove this method override?

2025-05-16 19:29 UTC, fosterseth requested changes
left my suggestion in a comment

2025-05-20 14:31 UTC, fosterseth approved these changes

2025-05-20 14:45 UTC, merged

2025-05-22 12:09 UTC, sverrehu commented
Any chance to get a 24.6.2 with this fix?