Fixed bug on non-required multiple choice survey questions
ansible/awx pull request #1640
Opened 2018-03-21 19:02 UTC by mabashian

##### SUMMARY
The problem here involved the awRequireMultiple directive which was initially added for custom model validation.  Since the model is an array of values and not a string, traditional validation did not work out of the box.  In the case outlined in #1561, `attrs.required` is set to true and then to false.  As soon as it's set to true, the custom validator is initiated and the model becomes invalid since the array is empty.  To combat this, we want to take into account whether the model is actually required at validation time.  If it is, then we check to make sure there are values in the array.  If it's not, then we return that the model is in fact valid.

This can be tested by creating a job template with a single survey question (multiple choice single select or multi select) with no default value.  Launch the JT and observe that the survey form should always be valid (NEXT button enabled) even if no value is specified in the multiple choice question.

link https://github.com/ansible/awx/issues/1561

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
awx: 1.0.4.122
```

2018-03-21 20:24 UTC, jlmitch5 requested changes

2018-03-21 20:24 UTC, jlmitch5 commented on awx/ui/client/src/shared/directives.js
> +                    if(angular.isArray(value)) {
`else { return false; }` for this conditional, in case the value is null (not sure if an issue, but probably wouldn't hurt to have the path).

2018-03-23 13:17 UTC, jlmitch5 approved these changes
very nice!

2018-03-23 13:31 UTC, merged

2018-03-23 20:51 UTC, brace01 commented
Thank you much!

Bryce Acer,
Rackspace