Added Doas to the drop down selection.
ansible/awx pull request #1742
Opened 2018-04-09 19:07 UTC by thedoubl3j

Signed-off-by: Jake Jackson <jajackso@jajackso-OSX.local>

##### SUMMARY

Added the selection "Doas" to the Privilege Escalation Method dropdown. Addressing issue #1712 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API

##### AWX VERSION

```
awx: 1.0.5.21
```

##### ADDITIONAL INFORMATION

2018-04-09 19:08 UTC, simfarm commented
🎆

2018-04-09 19:16 UTC, AlanCoding commented
@ryanpetrello 

https://github.com/ansible/awx/blob/d685815478b813d669dd55c248392a8eecb97923/awx/main/models/credential/__init__.py#L710

migration needed?

2018-04-09 20:07 UTC, ryanpetrello commented
Would be nice to see some tests, too.  Maybe something like this test:

https://github.com/ansible/awx/blob/devel/awx/main/tests/unit/test_tasks.py#L574

...but instead of creating a Credential with a username and a password, create one with the new `doas` become_method and confirm that the `ansible-playbook` arguments contain `"--become_method doas"`.

2018-04-09 20:11 UTC, thedoubl3j commented
can most definitely do that @ryanpetrello thanks for all the help, also have notes from @AlanCoding about the migrations stuff, can talk more later once I get some more traction done here

2018-04-09 20:11 UTC, ryanpetrello requested changes
Marking this as 👎 for now because it _definitely_ needs a migration to work for upgrades.  Here's an example of a similar migration we did when the CredentialType definition for AzureRM changed awhile back:

https://github.com/ansible/awx/commit/f28b48a4730047a275623807204a18a2d3ad71a4

The goal would be to find the _existing_ CredentialType where `kind='ssh'` and overwrite its `inputs` field with the _new_ value generated by `CredentialType.defaults.get('ssh', None)().inputs`.

2018-04-10 17:58 UTC, AlanCoding commented
@ryanpetrello instead of writing a new data migration like `add_azure_cloud_environment_field`, wouldn't it be better to ultimately have a method like `update_credential_types`, and then just loop over all of them and save them if any changes have occurred? If a new one is ever added, we can then just remove all prior calls and leave their files as no-ops.

Don't know if this would be a popular idea or not, but I don't think the credential type schemas will ever stop changing. Hey, managing perpetually-ballooning schemas was a large part of the reason for having credential types in the first place.

2018-04-10 18:11 UTC, ryanpetrello commented
@AlanCoding we need to be careful about changes to field definitions - it's really only kosher to do _additive_ things for types that might already have credentials associated.  That may be hard to detect and get right with something that auto-updates.

2018-04-11 10:38 UTC, AlanCoding commented
Yes, that makes sense as an approach. For this it makes sense to just carry forward the existing pattern.

2018-04-19 14:32 UTC, AlanCoding commented on awx/main/migrations/_credentialtypes.py
> +    become_credtype.inputs = CredentialType.defaults.get('ssh', None)().inputs
Don't think you need the `None` default, in that case it would fail either way

2018-04-19 14:33 UTC, AlanCoding commented on awx/main/migrations/_credentialtypes.py
> +    become_credtype = CredentialType.objects.get(kind='ssh')
I would want to add the filter of `managed_by_tower` at least, in case we introduce custom ssh types or something like that

2018-04-23 15:02 UTC, thedoubl3j commented
closing, resolved downstream

2018-04-23 15:02 UTC, closed without merging