refactor configuration (settings)
ansible/awx pull request #2069
Opened 2018-07-16 20:40 UTC by Haokun-Chen

##### SUMMARY

- Refactor configuration page to settings page
- create reusable card view directive
- add a settings-card view page and route to wrap on

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### ADDITIONAL INFORMATION

previous configuration page structure:
1. configuration route -- configuration controller -- configuraiton.partial
2. sub-form serve under the configuration state: as child-view@configuration 

new settings page structure:
1. settings route -- settings controller -- settings.partial (card view), each card navigates to settings.form state, and passes the corresponding stateParams.
2. settings-form route -- settings-form controller -- settings-form.partial (wrapper handle all sub-form, similar to previous configuration page)
3. sub-form serve under settings-form state: as child-view@settings.form
4. combine license route into settings.form.route

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    display: grid;
This is cool 😎

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    color: #161b1f;
we typically don't hard-code hex values, but rather we refer to them with a .less alias. The aliases are kept in `awx/ui/client/src/shared/branding/colors.default.less`

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    display: flex;
My understanding of CSS-Grid is minimal at best, but if the parent container, in this case `twr-card-container` uses `display:grid`, then does it's child elements need to specify `display:flex`? I thought that the parent element would take care of all that for you.

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    display: flex;
Seems kind of redundant to have css-grid and flex box in motion here. Maybe the flex is for the content in the card itself?

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    background-color: #fcfcfc;
You could probably replace this w/ an alias as well.

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    border-left: 3px solid #337ab7;
and this hex too :)

2018-07-26 17:00 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    box-shadow: 0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12);
is this the best way to write this?

2018-07-26 17:55 UTC, jaredevantabor requested changes
So far, I've found some cleanup that could happen with the .less file, some comments that could be removed, and also, I can't get to the license screen. Something weird going on with that route. 

But I did pull it down again and it looks like saving/editing settings are still in tact which is good.

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/lib/components/cards/_index.less
> +    font-size: 1em;
I haven't seen us use `em` for font size much, typically `px`

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/auth-form/configuration-auth.controller.js
> +        // if ($stateParams.currentTab === '' || $stateParams.currentTab === 'auth') {
can remove commented out code

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/auth-form/configuration-auth.partial.html
> +    <!-- <hr ng-show="authVm.activeTab === 'ldap' || authVm.activeTab === 'github'"/> -->
could remove

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/jobs-form/configuration-jobs.controller.js
> +        // }, 1000);
if you don't think this hack is still necessary let's just remove it

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/jobs-form/configuration-jobs.controller.js
> +                // codeInputInitialized = true;
can remove

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/license.route.js
>  	// templateUrl: templateUrl('license/license'),
can remove

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/license.route.js
> +	name: 'form.license',
shouldn't this be `settings.license`?

2018-07-26 17:55 UTC, jaredevantabor commented on awx/ui/client/src/configuration/license.route.js
>  	// templateUrl: templateUrl('license/license'),
can you remove these lines?

2018-08-13 15:56 UTC, wenottingham commented
Apologies, this now has conflicts. Can you rebase and fix the conflicts?

2018-08-14 15:35 UTC, Haokun-Chen commented
Sure! resolving conflicts

2018-08-15 19:31 UTC, jaredevantabor approved these changes

2018-08-16 17:12 UTC, merged