Add notify to Slack threads
ansible/awx pull request #2136
Opened 2018-08-04 21:59 UTC by walkafwalka

Signed-off-by: walkafwalka <41709139+walkafwalka@users.noreply.github.com>

##### SUMMARY
Adds the ability to specify a Slack thread to reply to.

Fixes #1048 and #1741.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API
 - UI

##### AWX VERSION
```
awx: 1.0.6.44
```

##### ADDITIONAL INFORMATION
I also bumped the slackclient and added the Slack error message to error log.

2018-08-04 22:00 UTC, walkafwalka commented
@matburt

2018-08-06 19:30 UTC, matburt reviewed
Looks good... can you add the thread-reply detail to the notifications architecture documents under docs/

2018-08-06 22:47 UTC, walkafwalka commented
Aaaand, done.

2018-10-30 16:53 UTC, jakemcdermott commented
hello @walkafwalka 

Thanks for the PR. You'll need to rebase your changes over the latest devel for this to be mergeable.

2018-10-30 17:02 UTC, jakemcdermott requested changes

2018-10-30 17:02 UTC, jakemcdermott commented on requirements/requirements.txt
> -debtcollector==1.15.0     # via oslo.config, oslo.utils, python-designateclient, python-keystoneclient, python-neutronclient
It is not clear to me why this dependency is being removed, and I would like to know more!

2018-11-26 18:20 UTC, matburt commented
ping @walkafwalka can you address the concerns above?

2019-01-03 20:12 UTC, walkafwalka commented
Sorry. I do not have time to address this fix for this project. Anyone feel free to pick this up.

2019-01-03 20:12 UTC, closed without merging

2022-09-06 17:13 UTC, tanujdevops commented
Hi @matburt, I would like to pick this issue up again. Can you please assign it to me?

2022-09-06 17:14 UTC, tanujdevops commented
Hi @matburt, I would like to pick this issue up again. Can you please assign it to me?