dont render blank output lines for some event types + adjust line wrapping
ansible/awx pull request #2457
Opened 2018-10-16 17:11 UTC by jakemcdermott

##### SUMMARY
- don't render `playbook_on_notify` or `runner_on_ok` events if they have empty strings for their `stdout` field.
- adjust line wrapping for output lines to make the behavior more ansible-like

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
![output_terminal](https://user-images.githubusercontent.com/9753817/47034306-fc8ed300-d144-11e8-8073-6babe0a6b205.gif)
![output_ui](https://user-images.githubusercontent.com/9753817/47034311-00225a00-d145-11e8-9334-fbc2f4178396.gif)

2018-10-16 17:44 UTC, wenottingham commented on awx/ui/client/features/output/_index.less
>          height: 100%;
probably should elide this

2018-10-16 17:56 UTC, kialam commented
Would we want to render _any_ events if their `stdout` field is an empty string? 🤔

2018-10-16 17:59 UTC, jakemcdermott commented
> Would we want to render _any_ events if their `stdout` field is an empty string? 🤔

_Maybe_ - Keeping this filtering reduced to specific event types seems more surgical, but it might not be inclusive enough. @ryanpetrello @wenottingham What are your thoughts?

2018-10-16 18:05 UTC, ryanpetrello approved these changes
@jakemcdermott I like this change, and I like you.

2018-10-16 18:29 UTC, wenottingham commented
Aren't there events that just return OK/Changed/Failed w/o a `stdout` field?

2018-10-16 19:16 UTC, jakemcdermott commented
> Aren't there events that just return OK/Changed/Failed w/o a `stdout` field?

Yes - these should already be covered by a [similar check](https://github.com/ansible/awx/blob/devel/awx/ui/client/features/output/render.service.js#L200)(in this case, for all events that don't have a `stdout` field defined).

The changes here are for an even more specific case, which is that some event types have defined `stdout` fields that are empty strings `''` that we don't want render an extra line for.

2018-10-17 16:08 UTC, matburt commented
under what scenario does a `runner_on_ok` event not have a stdout? I would think that would never happen.

2018-11-01 20:29 UTC, ryanpetrello commented
Hey @jakemcdermott any updates on this one?

2018-11-05 16:30 UTC, jlmitch5 requested changes
Looks great! one small css change and it should be good to go

2018-11-05 16:30 UTC, jlmitch5 commented on awx/ui/client/features/output/_index.less
> +    // flex: 1;
remove this in favor of commenting out

2018-11-05 21:11 UTC, jlmitch5 approved these changes
nice!

2018-11-06 01:22 UTC, jakemcdermott commented
recheck

2018-11-06 01:37 UTC, jakemcdermott commented
recheck

2018-11-06 01:54 UTC, merged