Add pod limits. Related #2488
ansible/awx pull request #2489
Opened 2018-10-18 20:24 UTC by jaevans

##### SUMMARY

We enforce having limits and requests on all containers in our environment, and set the LimitRange very low to require them to be set. This change adds new variables to control the limits, and defaults them to the requests.

Without these limits set, the database migration fails due to the migration process running out of memory, and the awx-0 pod fails to start.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
awx: 2.0.1
```

##### ADDITIONAL INFORMATION

```

```

2018-10-25 21:05 UTC, shanemcd requested changes
Before accepting this, we would need to default to not having a limit. In most scenarios we do not want things getting OOM killed. The `request` values should be thought of as minimum requirements for your workload. It would make sense for this to be a separate, higher value than what you are requesting.

2018-11-29 03:59 UTC, Idanatcox commented
@shanemcd I think this PR is important to merge and default to having limits. Although on local minishift cluster it is not necessary and flexibility is useful but mostly production clusters will have dedicated quotas with limits set per namespace. 
It's also a good practice to have some limits configured so mem leaks will be identified and app performance will be known at a given resources
I agree with you that limits should be higher than requests but I don't think it should block this valuable PR. 
Will it be helpful to create a separated issue for setting the limits higher so this can move forward?

2018-11-29 18:44 UTC, shanemcd commented
@Idanatcox I have requested the changes that would be necessary for this to land but I haven't heard back from the original author. If you or someone else would like to wrap up the work here I'd be happy to review and test it.

2018-11-29 19:48 UTC, jaevans commented
@shanemcd I'm the original author of the PR, and due to changing priorities I haven't gotten back to this yet. Your original request was to default to no limits, but I agree with @Idanatcox that anything beyond a development minikube style environment should have limits set.

I agree that defaulting the limits to the requests isn't a good idea, it was more a quick and dirty way to get things working and start a conversation about it.

I see two different thoughts here:

1. Don't add limits by default
2. Add limits by default, with an appropriate set of values

I'm open to either, but would need input on the values for number 2, I'm still in POC mode with my AWX in k8s. We'll be going live soon, so I'll actually have to worry about reasonable limits!

2019-01-14 16:51 UTC, matburt commented
I think I like the approach of #2994 more

2019-01-14 16:51 UTC, closed without merging

2019-01-14 17:15 UTC, Idanatcox commented
thanks @matburt