fix permission issue with regular user jt admins
ansible/awx pull request #2596
Opened 2018-11-05 19:47 UTC by jlmitch5

regular users assigned jt admin could not add user jt roles for users they couldn't edit

2018-11-05 20:32 UTC, AlanCoding commented
I'll let you triage this, but if I sort the permissions page by first name, it changes the total count

![jt_permissions_sort](https://user-images.githubusercontent.com/1385596/48024891-d9d25780-e10f-11e8-962e-7e7bd65cbc26.gif)

This is because the original list checks for only users where `is_superuser` is false, but that filter is lost once the list is sorted.

Back to the issue at hand here, this user does not have edit permission to any of those users in the list, so the fact that they are not greyed out looks correct.

2018-11-05 20:47 UTC, AlanCoding commented
This doesn't seem to resolve the issue.

Here, I am org admin of the "Default" organization.

I add a user who is system auditor, but not in my organization. This is not allowed, because this could allow me to change the password of the user, and gain system auditor privilege, which would be a permissions leak.

![org_permissions_again](https://user-images.githubusercontent.com/1385596/48025576-da6bed80-e111-11e8-9921-af4cf7f42c75.gif)

The UI just doesn't help here.

See JSON for users list:

```json
        {
            "id": 59,
            "type": "user",
            "url": "/api/v2/users/59/",
            "related": {
                "admin_of_organizations": "/api/v2/users/59/admin_of_organizations/",
                "authorized_tokens": "/api/v2/users/59/authorized_tokens/",
                "roles": "/api/v2/users/59/roles/",
                "organizations": "/api/v2/users/59/organizations/",
                "access_list": "/api/v2/users/59/access_list/",
                "teams": "/api/v2/users/59/teams/",
                "tokens": "/api/v2/users/59/tokens/",
                "personal_tokens": "/api/v2/users/59/personal_tokens/",
                "credentials": "/api/v2/users/59/credentials/",
                "activity_stream": "/api/v2/users/59/activity_stream/",
                "projects": "/api/v2/users/59/projects/"
            },
            "summary_fields": {
                "user_capabilities": {
                    "edit": false,
                    "delete": false
                }
            },
            "created": "2018-10-16T12:34:33.441351Z",
            "username": "system_auditor_XxTEGrc9R8",
            "first_name": "Joe (姀ⴹ㹝擀똭閠훉徹銉㬀)",
            "last_name": "System Auditor (矋䌸禦誷㪸삒쓊哣쥗猟)",
            "email": "pLoJHZya@test.biz",
            "is_superuser": false,
            "is_system_auditor": true,
            "ldap_dn": "",
            "external_account": null,
            "auth": []
        },
```

It clearly tells me that I don't have permission to edit this user. In that case, the UI shouldn't present me the option to make the user either organization admin or organization member, because that will result in a 403.

Or at minimum, the UI should give me some text about the error message the API returned in this situation.

2018-11-05 21:47 UTC, jlmitch5 commented
@AlanCoding thank you for that scenario!  I realized that the way I was going about this change before was incorrect.  Now, I am basing disabling off of the object you are trying to add permissions to.  For non-organization, the user shows up enabled:

<img width="883" alt="screen shot 2018-11-05 at 4 44 37 pm" src="https://user-images.githubusercontent.com/1342624/48028785-713ca800-e11a-11e8-9b62-7a99222508ce.png">

and for organization, they show up disabled:

<img width="812" alt="screen shot 2018-11-05 at 4 44 59 pm" src="https://user-images.githubusercontent.com/1342624/48028730-49e5db00-e11a-11e8-9ca9-bf5f68d97bb5.png">

2018-11-05 21:55 UTC, jlmitch5 commented
also, filed low priority issue for the changing badge count https://github.com/ansible/awx/issues/2602

2018-11-06 06:24 UTC, jakemcdermott requested changes

2018-11-06 06:24 UTC, jakemcdermott commented on awx/ui/client/src/access/rbac-multiselect/rbac-multiselect-list.directive.js
> +            console.log(scope.objectType);
should remove this line

2018-11-06 11:56 UTC, AlanCoding commented
That should solve the main issue here. It's a big problem that the users are greyed out in the JT list. If this is what you want for the immediate fix, then it looks good to me.

There's the thornier issue that you _can_ give the auditor workflow_admin_role, or similar org-resource-roles, and that I don't think the UI has exposed that ability yet. It's not super important compared to fixing the JT permissions.

2018-11-06 15:52 UTC, jakemcdermott approved these changes

2018-11-06 16:40 UTC, merged