Remove MD5 usage and dependency from UI
ansible/awx pull request #2747
Opened 2018-11-19 18:16 UTC by kialam

##### SUMMARY

Built off of #2718

Related ansible/tower#814

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 2.1.0
```

2018-11-19 18:18 UTC, ryanpetrello approved these changes
😄

2018-11-19 19:58 UTC, mabashian commented
Code makes sense and looks good.  Seems like we need to discuss what the expectation is for the package-lock file as a lot's changed in there.  Also, not sure why the api tests would be failing with this PR 🤷‍♂️

2018-11-19 20:28 UTC, wenottingham commented
> Also, not sure why the api tests would be failing with this PR 

The license checker runs as an 'api' test as it was the most convenient place to shove it.

2018-11-19 21:35 UTC, kialam commented
> > Also, not sure why the api tests would be failing with this PR
> 
> The license checker runs as an 'api' test as it was the most convenient place to shove it.

@wenottingham does the license checker also look in the /ui directory? I found a second `angular-md5` license there.

2018-11-19 22:02 UTC, wenottingham commented
Yes, it should be.

2018-11-20 08:47 UTC, Spredzy commented
recheck

2018-11-20 15:59 UTC, ryanpetrello commented
recheck

2018-11-20 21:00 UTC, ryanpetrello commented on awx/ui/client/src/templates/job_templates/factories/hash-setup.factory.js
> +                    (c ^ crypto.getRandomValues(new Uint8Array(1))[0] & 15 >> c / 4).toString(16)
https://caniuse.com/#feat=getrandomvalues

2018-11-20 21:59 UTC, jlmitch5 approved these changes
all the changes from MD5 to hash look good.  the UUID generation looks okay I think?  so far as I understand it

2018-11-20 22:29 UTC, ryanpetrello commented
From a testing perspective, the thing I mostly am concerned about coverage-wise is ensuring that `crypto.getRandomValues` _does_ seem to work across our supported browser matrix (
https://caniuse.com/#feat=getrandomvalues suggests that it does).

2018-11-21 01:42 UTC, jakemcdermott approved these changes
verified locally:

![hostconfigkey1](https://user-images.githubusercontent.com/9753817/48813409-c96fce80-ed04-11e8-951f-959aaaedc284.gif)

2018-11-21 01:44 UTC, jakemcdermott commented on awx/ui/package-lock.json
> +        "codemirror": "5.38.0",
I'm unclear on why this is changing?

2018-11-21 02:00 UTC, jakemcdermott requested changes
This mostly looks good to me - just one change (see comments) and I think this should be good to go!

Happy to verify again locally with more browsers when ready 👍

2018-11-21 02:00 UTC, jakemcdermott commented on awx/ui/package-lock.json
>        "integrity": "sha1-w8p0NJOGSMPg2cHjKN1otiLChMo=",
I think all we need here is:

```
make clean
npm uninstall --prefix awx/ui --save angular-md5
```

2018-11-21 18:13 UTC, jakemcdermott approved these changes
code changes now look good to me! 👍 thank you @kialam 

I'll verify again with a supported firefox version shortly and then I think this should be ready to go!

2018-11-21 18:14 UTC, jakemcdermott commented on awx/ui/README.md
> +- npm >=5.10
👍

2018-11-21 18:30 UTC, unlikelyzero commented
@ryanpetrello @jakemcdermott what will happen with previously generated values if a user upgrades?

2018-11-21 18:41 UTC, jakemcdermott commented
@unlikelyzero 
Nothing, I'd presume? In the end of the day the hash is just a string. Old values already persisted in the db and sent over from the API should still be displayable.

2018-11-21 18:54 UTC, jakemcdermott commented
still looks good to me on ffox esr:

![hostconfigkey5](https://user-images.githubusercontent.com/9753817/48862406-4bf39f00-ed94-11e8-9f62-c80b78e52b3e.gif)

2018-11-21 19:10 UTC, jakemcdermott commented
e2e, etc. still checks out. Probably ready to merge this finally?

2018-11-21 19:14 UTC, jakemcdermott commented
update: probably should get wf convergence in first, as they both update `package.json`.

2018-11-26 12:39 UTC, ryanpetrello commented
Agreed on holding off the merge until after WF convergence is in.

@unlikelyzero nothing will happen w/ the old values; this code is only used to generate a random string that is passed to and stored in the API.

2018-11-28 05:44 UTC, jakemcdermott commented
- reverified on firefox esr
- e2e still looks good

2018-11-28 16:16 UTC, merged