Remove error message for regular logout
ansible/awx pull request #3091
Opened 2019-01-28 20:30 UTC by beeankha

##### SUMMARY 
Connected to issue https://github.com/ansible/awx/issues/2837

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 3.0.0
```

##### ADDITIONAL INFORMATION

The `You have been logged out. Please sign in.` error showed up even when logging out on purpose.  This error message seemed redundant, and was showing up on top of the timeout error:

![timeoutnotification](https://user-images.githubusercontent.com/28930622/51864229-20031580-2311-11e9-9858-828747a226a5.png)

With the change in this PR, this is what the user sees when logging out on purpose:

![noerrormessage](https://user-images.githubusercontent.com/28930622/51864333-7a9c7180-2311-11e9-93e2-feb34d548c36.png)

...and this is what shows up when the session times out (only one error message vs two):

![nomoredoubleerror](https://user-images.githubusercontent.com/28930622/51864337-7e2ff880-2311-11e9-8b47-0f913d6e2843.png)

2019-01-28 20:56 UTC, jlmitch5 approved these changes
code looks great!  would just double check with @tvo318 and @trahman73 about the UX and wording (though no wording has really changed, just we don't show logging out as an error message)

2019-01-28 21:00 UTC, jlmitch5 requested changes
As @wenottingham mentioned, a change needs to be made so that the two messages don't show up

2019-01-28 21:15 UTC, beeankha commented
Added back the original signout error message.  Now when the user logs out on purpose, this shows up:

![logouterrormsg](https://user-images.githubusercontent.com/28930622/51866795-dec23400-2317-11e9-9098-b696ecbef16b.png)


...and when session times out, this shows up:

![timeouterror](https://user-images.githubusercontent.com/28930622/51866798-e08bf780-2317-11e9-9f59-9a44d760891a.png)

2019-01-28 21:22 UTC, kialam commented on awx/ui/client/src/login/loginModal/loginModal.partial.html
> +                <div class="LoginModal-alert LoginModal-alert--error" ng-show="userLoggedOut && !sessionExpired">
I would suggest using separate `ng-show` expressions for the two different logout messages. The current expression will return truthy if one of those criteria are met.

2019-01-29 18:11 UTC, beeankha commented
Now the regular logout message should NOT double up with `session limit expired`, `third party attempt failed`, timeout, etc.

2019-01-29 18:42 UTC, jlmitch5 approved these changes

2019-01-29 19:00 UTC, kialam requested changes
When I log out on purpose, I still get the error message, "You have been logged out. Please sign in." In the PR it is noted that when a user logs out on purpose, they should not see any error message. Is this the expected behavior?

2019-01-29 19:05 UTC, wenottingham commented
The expected behavior is that logging out on purpose is what generates the 'You have been logged out' message.

2019-01-29 19:19 UTC, beeankha commented
Yep @kialam , sorry about not clarifying that.  I preserved the "You have been logged out" message for when the user logs out, just changed the doubling up of that message along with other logout scenarios.

2019-01-29 19:40 UTC, kialam approved these changes

2019-01-29 19:51 UTC, merged