Add settings to control screenshot capturing
ansible/awx pull request #3148
Opened 2019-02-04 17:07 UTC by elyezer

##### SUMMARY
Add settings to configure screenshot capturing for e2e tests. This will help debugging when running the test suite on a headless machine.

##### ISSUE TYPE
 - UI Test Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
awx: 3.0.0
```

2019-02-04 20:50 UTC, jakemcdermott commented on awx/ui/test/e2e/settings.js
> +const AWX_E2E_SCREENSHOTS_ON_ERROR = process.env.AWX_E2E_SCREENSHOTS_ON_ERROR || true;
This should probably default to false. Otherwise, the default behavior for existing systems / workflows might change.

2019-02-04 22:03 UTC, unlikelyzero requested changes
I think we should move the screenshots section out of the test_settings defaults and move it into the overall config definition. Our elgaul/docker-selenium container should be able to handle these screenshots in the same way.
Also, we should resolve the path using the same pattern as we use to define the reports and test folders.

2019-02-05 18:30 UTC, elyezer commented on awx/ui/test/e2e/settings.js
> +const AWX_E2E_SCREENSHOTS_ON_ERROR = process.env.AWX_E2E_SCREENSHOTS_ON_ERROR || true;
@jakemcdermott `AWX_E2E_SCREENSHOTS_ENABLED` controls if the screenshot machinery will be enabled or not and it is false by default. The other flags are set to true because, once the machine is enabled, I think it would be useful to capture screenshots on both on error and on failure.

Having those on_failure and on_error enabled by default would avoid to pass enabled plus those two.

2019-02-05 18:32 UTC, elyezer commented
@unlikelyzero do you mean instead of having those variables on the `settings.js` file to have the logic on the `nightwatch.conf.js`?

2019-02-07 20:48 UTC, unlikelyzero approved these changes

2019-02-07 20:49 UTC, unlikelyzero commented
@elyezer i meant to use the path resolution defined in the import statement in nightwatch.conf.js:1 it's used on nighwatch.conf.js:21-24

2019-02-11 16:47 UTC, merged