WIP: don't update parent event changed|failed in bulk (it's expensive)
ansible/awx pull request #3179
Opened 2019-02-06 22:10 UTC by ryanpetrello

2019-02-06 22:46 UTC, ryanpetrello commented on awx/main/models/events.py
> +                    JobEvent.objects.filter(job=self.job, uuid=self.parent_uuid).update(**kwargs)
```sql
\d main_jobevent

...
Indexes:
    ...
    "main_jobevent_job_id_uuid_3df694c5_idx" btree (job_id, uuid)
```

2019-02-06 22:47 UTC, ryanpetrello commented on awx/main/models/events.py
> +                    JobEvent.objects.filter(job_id=self.job_id, uuid=self.parent_uuid).update(**kwargs)
```sql
\d main_jobevent

...
Indexes:
    ...
    "main_jobevent_job_id_uuid_3df694c5_idx" btree (job_id, uuid)
```

2019-02-06 22:52 UTC, ryanpetrello commented on awx/main/models/events.py
> +                    JobEvent.objects.filter(job_id=self.job_id, uuid=self.parent_uuid).update(**kwargs)
Sample query:

```sql
UPDATE "main_jobevent"
    SET "failed" = true
    WHERE ("main_jobevent"."job_id" = 7 AND "main_jobevent"."uuid" = '0242ac12-0005-4e0c-d27c-00000000000d');
```

2019-02-06 22:54 UTC, ryanpetrello commented on awx/main/models/events.py
> +                    JobEvent.objects.filter(job_id=self.job_id, uuid=self.parent_uuid).update(**kwargs)
Sample index scan on a production install:

```
awx=> EXPLAIN UPDATE "main_jobevent" SET "failed" = true WHERE ("main_jobevent"."job_id" = 7 AND "main_jobevent"."uuid" = '0242ac12-0005-4e0c-d27c-00000000000d');
                                                      QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------
 Update on main_jobevent  (cost=0.41..8.43 rows=1 width=964)
   ->  Index Scan using main_jobevent_job_id_1a69b01a6e969026_idx on main_jobevent  (cost=0.41..8.43 rows=1 width=964)
         Index Cond: ((job_id = 7) AND ((uuid)::text = '0242ac12-0005-4e0c-d27c-00000000000d'::text))
(3 rows)

awx=> SELECT COUNT(id) FROM main_jobevent;
 count
-------
 34765
(1 row)
```

2019-02-07 00:17 UTC, matburt requested changes

2019-02-07 00:17 UTC, matburt commented on awx/main/models/events.py
> +            if any([
I think we can shortcut this entirely by just checking `self.changed` and `self.failed` for `True` and then falling into the JobEvent filter.

We'll save potentially `dozens` of microseconds!

2019-02-07 00:20 UTC, matburt commented on awx/main/models/events.py
> +            if any([
Even if this means affecting a parent above the task level I don't think that's such a big deal.

2019-02-07 00:21 UTC, matburt commented
One other thing will be checking to see if we bubble changed/failed up to a higher level beyond the task level in the current implementation.

2019-02-07 00:47 UTC, ryanpetrello commented
> One other thing will be checking to see if we bubble changed/failed up to a higher level beyond the task level in the current implementation.

I wouldn't _expect_ it to, given that we're currently filtering on these events on `.startwith('runner_on')`:

https://github.com/ansible/awx/blob/fc94b3a943d20c82216898e58c979027d80343a3/awx/main/models/events.py#L404

2019-02-07 01:28 UTC, ryanpetrello commented
Old query is _definitely_ slow:

```sql
awx-dev=> INSERT INTO main_jobevent
    (created, modified, uuid, parent_uuid, failed, changed, host_name, play, role, task, counter, event, job_id, event_data, start_line, end_line, stdout, verbosity, playbook)
    SELECT now(), now(), x, 'parent_uuid', false, false, '', '', '', '', 1, 'playbook_on_start', 1, '{"pid": 3, "playbook_uuid": "461fdef8-ed03-402a-9f90-d283961ec8e3", "playbook": "hello_world.yml"}', 0, 1, 'foo', 0, 'hello_world.yml'
    FROM generate_series(1, 100000000) AS x;

awx-dev=> SELECT COUNT(id) FROM main_jobevent;
-[ RECORD 1 ]---
count | 11000043
```

`<run a simple Job Template that emits events>`

```sql
\timing
UPDATE "main_jobevent"
    SET "failed" = true
    WHERE "main_jobevent"."uuid" IN (
        SELECT U0."parent_uuid" AS Col1
        FROM "main_jobevent" U0
        WHERE (U0."job_id" = 16 AND U0."event"::text LIKE 'runner\_on%' AND U0."failed" = true)
    );
UPDATE 1
Time: 5060.824 ms
```

2019-02-07 01:47 UTC, ryanpetrello commented
If you pump the event count up to 25-30M, it can get pretty bad:

```sql
awx-dev=> UPDATE "main_jobevent" SET "failed" = true WHERE "main_jobevent"."uuid" IN (SELECT U0."parent_uuid" AS Col1 FROM "main_jobevent" U0 WHERE (U0."job_id" = 19 AND U0."event"::text LIKE 'runner\_on%' AND U0."failed" = true));
UPDATE 1
Time: 31314.081 ms
```

2019-02-07 14:58 UTC, matburt approved these changes

2019-02-07 15:16 UTC, merged