add padding to label list tag.
ansible/awx pull request #3340
Opened 2019-02-28 18:23 UTC by AlexSCorey

##### SUMMARY
Added top-padding to the smart host filter list

##### ISSUE TYPE
 - Bugfix Pull Request
 - Enhancement

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
3.0.1
```

##### ADDITIONAL INFORMATION
<img width="803" alt="screen shot 2019-02-28 at 1 11 52 pm" src="https://user-images.githubusercontent.com/39280967/53588677-81f6ab00-3b5b-11e9-85e2-1838223b84aa.png">

```

```

2019-02-28 19:05 UTC, jlmitch5 approved these changes

2019-02-28 20:46 UTC, marshmalien requested changes
![image](https://user-images.githubusercontent.com/15881645/53597284-c7bd6e80-3b6f-11e9-85a3-3ea24c67af0f.png)
I don't think this addresses the original issue. The smart inventory host filter is **missing** the space between the host tag and search input border.

2019-02-28 22:03 UTC, AlexSCorey commented
Here is the change. 
<img width="424" alt="screen shot 2019-02-28 at 5 01 59 pm" src="https://user-images.githubusercontent.com/39280967/53601702-b037b300-3b7a-11e9-8656-03ce511b3c7d.png">

2019-03-01 15:59 UTC, marshmalien approved these changes

2019-03-01 15:59 UTC, marshmalien commented
🔥

2019-03-01 16:20 UTC, merged