add template name to launch prompt modal.
ansible/awx pull request #3373
Opened 2019-03-06 20:15 UTC by AlexSCorey

##### SUMMARY
Adds a template note to the launch template.  I would love some input on how I am "building" the title and template name.  I couldn't do template literals because the linter rejected them.

##### ISSUE TYPE
 - Enhancement Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
3.0.1
```

##### ADDITIONAL INFORMATION
<img width="903" alt="screen shot 2019-03-06 at 3 05 36 pm" src="https://user-images.githubusercontent.com/39280967/53910711-8969f880-4022-11e9-9320-58da41ad0e02.png">

2019-03-06 20:22 UTC, jakemcdermott requested changes

2019-03-06 20:22 UTC, jakemcdermott commented on awx/ui/client/src/templates/prompt/prompt.controller.js
> +                        modal.show(strings.get('prompt.PROMPT'), null, templateName);
Job template names reflect input from other users, so let's apply a `$filter('sanitize')` to `templateName` here.

2019-03-07 15:03 UTC, jakemcdermott approved these changes

2019-03-07 15:21 UTC, merged

2019-03-08 16:37 UTC, sumkincpp commented
Are there any plans for also showing a description of Job Template/Workflow?