The keyword 'cloud' has been deprecated in favor of the 'profile' key…
ansible/awx pull request #366
Opened 2017-10-05 05:42 UTC by larry-s

…word in os_client_config.

##### SUMMARY

For openstack inventories the 'cloud' has been deprecated in favor of the 'profile' keyword. This changes the sample openstack.yml file.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API

##### AWX VERSION

```
awx: 1.0.0.589
```

##### ADDITIONAL INFORMATION

```

```

2017-10-05 14:48 UTC, matburt requested changes
We actually pull these from ansible upstream... they are mostly here for completeness as a dev guide. I might recommend you push these changes upstream to ansible itself and then we can pull them in on ours later.

Here's an example: https://github.com/ansible/ansible/blob/devel/contrib/inventory/openstack.yml

2017-10-12 17:21 UTC, matburt commented on awx/plugins/inventory/openstack.yml
> +    profile: hp
These need to be removed and instead contributed upstream to ansible core.

2017-10-12 17:23 UTC, matburt commented
Your PR here contains a merge commit, we need to have you rebase/rewrite the commit log to not include that see: https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#submitting-pull-requests

2017-10-12 21:46 UTC, larry-s commented
Contributed to ansible/ansible instead.

2017-10-12 21:46 UTC, closed without merging