Add "Disable SSL Verification" checkbox to webhook notification
ansible/awx pull request #3839
Opened 2019-05-06 14:33 UTC by zicklam

##### SUMMARY
This commit will add a checkbox which will disable SSL verification on
the generic webhook notification type. This is required when using
self-signed certificates.

This option is copied from already existing notification types like
* grafana
* mattermost
* rocket.chat

related #3838 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
awx: 4.0.0
```

##### ADDITIONAL INFORMATION
BEFORE against self-signed https endpoints:
```
awx.main.tasks Send Notification Failed ("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",)
```

AFTER
```
awx.main.dispatch publish awx.main.tasks.send_notifications(dba84e5d-aaab-468e-b726-55c813583171, queue=awx_private_queue)
awx.main.dispatch delivered dba84e5d-aaab-468e-b726-55c813583171 to worker[180] qsize 0
awx.main.dispatch task dba84e5d-aaab-468e-b726-55c813583171 starting awx.main.tasks.send_notifications(*[[34]])
awx.main.dispatch task dba84e5d-aaab-468e-b726-55c813583171 is finished
```

2019-05-06 14:44 UTC, jakemcdermott requested changes
@zicklam

Thanks for contributing. The code changes look good to me. Nice work!

Would you please post a screenshot of the updated UI and leave a quick note on how you tested this? Once that's in, I'd consider this ready to merge.

We'll also need to address the failing unit tests somehow - [the test bot is indicating we have a failure somewhere](https://github.com/ansible/awx/pull/3839#issuecomment-489645641). Did you have a chance to give those a run locally? You can do that by shelling into the dev container and running the following commands:

```shell
docker exec -it tools_awx_1 bash
cd awx_devel
make test
```

2019-05-06 15:01 UTC, zicklam commented
@jakemcdermott 
I will test it again and report.

**Screenshot**:
![webhook_notification](https://user-images.githubusercontent.com/5683163/57234257-87231b00-7020-11e9-9f99-8cccdb80d3a1.png)

2019-05-06 15:57 UTC, jakemcdermott commented
@zicklam 
I'm seeing the following unit test failures, in `awx/main/tests/functional/test_notifications.py`


```
_________________________ test_basic_parameterization __________________________
Traceback (most recent call last):
  File "/awx_devel/awx/main/tests/functional/test_notifications.py", line 34, in test_basic_parameterization
    assert response.status_code == 201
AssertionError: assert 400 == 201
 +  where 400 = <Response status_code=400, "application/json">.status_code
----------------------------- Captured stderr call -----------------------------
2019-05-06 15:28:37,556 WARNING  awx.api.generics status 400 received by user admin-poster attempting to access /api/v2/notification_templates/ from 127.0.0.1
------------------------------ Captured log call -------------------------------
generics.py                221 WARNING  status 400 received by user admin-poster attempting to access /api/v2/notification_templates/ from 127.0.0.1
____________________ test_inherited_notification_templates _____________________
Traceback (most recent call last):
  File "/awx_devel/awx/main/tests/functional/test_notifications.py", line 87, in test_inherited_notification_templates
    assert response.status_code == 201
AssertionError: assert 400 == 201
 +  where 400 = <Response status_code=400, "application/json">.status_code
----------------------------- Captured stderr call -----------------------------
2019-05-06 15:28:38,011 WARNING  awx.api.generics status 400 received by user admin-poster attempting to access /api/v2/notification_templates/ from 127.0.0.1
------------------------------ Captured log call -------------------------------
generics.py                221 WARNING  status 400 received by user admin-poster attempting to access /api/v2/notification_templates/ from 127.0.0.1
______________________ test_custom_environment_injection _______________________
Traceback (most recent call last):
  File "/awx_devel/awx/main/tests/functional/test_notifications.py", line 149, in test_custom_environment_injection
    assert response.status_code == 201
AssertionError: assert 400 == 201
 +  where 400 = <Response status_code=400, "application/json">.status_code
----------------------------- Captured stderr call -----------------------------
```

For the first test, it looks like the notification template detail endpoint is expecting `webhook_no_verify_ssl` as a required variable, which isn't being provided in the test:

```
{'__all__': ["Missing required fields for Notification Configuration: ['webhook_no_verify_ssl']."]}
```

Is the intent here to _not_ have a default value for this field? As long as the other notification types that have this field (rocket chat and mattermost, for example) behave the same way then I think that is fine - I think to resolve these you'll need to double-check that the behavior is consistent with the other notification types and then update the tests to provide values for the new field.

2019-05-06 16:45 UTC, zicklam commented
@jakemcdermott 
Thank you for your help. I guess the difference is, that there is no test template for other notifications then "webhook" and "twilio".

I think i found the issue & I will test it again and submit the changes, when I am done.

2019-05-07 08:37 UTC, zicklam commented
@jakemcdermott 
The issue should be solved now, test was successfull.
I will make another notification type for Zulip later, so we can use the complete test function for this webhook.

2019-05-07 12:07 UTC, jakemcdermott commented
@zicklam thanks - this LGTM. I'd like to test these changes out in a few places today prior to merging. I'll leave another update here when this is ready to merge.

2019-05-07 13:41 UTC, ryanpetrello commented
@jakemcdermott in the past, we've been bitten by changes like this after a migration/upgrade.  I want to make sure we don't observe the following:

1.  Install AWX 4.0.0 and make one of these webhooks _without_ a default.
2.  Update to their PR.
3.  💥

2019-05-07 14:06 UTC, beeankha commented
I second what @ryanpetrello says. When I changed the email notification to have a customizable timeout, a default had to be specified because otherwise any previously-created notification from any older version of AWX would act weird upon upgrading to the latest version (it would spin and spin then eventually fail).  So that `"default": false` bool is most likely necessary for upgrade purposes.

2019-05-07 18:41 UTC, jakemcdermott commented
@zicklam let's add in that default param 🎉. once that's in we'll take another look

2019-05-08 06:58 UTC, zicklam commented
@ryanpetrello @beeankha Thank you for your advise and help.
@jakemcdermott I've added the default value now, test on tools_awx_1 was successfull aswell.

2019-05-08 18:10 UTC, ryanpetrello approved these changes

2019-05-08 19:31 UTC, jakemcdermott approved these changes

2019-05-08 19:44 UTC, merged