Feature/hosts description
ansible/awx pull request #3901
Opened 2019-05-15 14:51 UTC by jlariza

##### SUMMARY

Fixes:  #3348 
Hosts object have two main fields, name and description. The name tends to be an IP address that is not very explicit. However, all the hosts list do not display their description, only their name so they are very confusing.

This Branch adds the description fields to the hosts list so they are easily identifiable with no extra effort.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 4.0.0
```

##### ADDITIONAL INFORMATION

```

```

2019-05-15 15:04 UTC, cdvv7788 commented
@ryanpetrello How can we check the failures in the build? Are there any instructions for that?

2019-05-15 15:06 UTC, ryanpetrello commented
@cdvv7788 the current build failures are an issue w/ our zuul CI that we're looking into.

2019-05-15 15:10 UTC, ryanpetrello commented
recheck

2019-05-15 15:36 UTC, wenottingham commented
What sources actually populate `description`? Is this only ever manually set?

2019-05-15 17:08 UTC, shanemcd commented
recheck

2019-05-15 19:54 UTC, shanemcd commented
recheck

2019-05-17 16:44 UTC, cdvv7788 commented
@wenottingham I am not sure if this is populated only manually. The changes are only for visualization tho, so there shouldn't be an issue even if they are inserted somewhere else.

2019-05-17 18:50 UTC, wenottingham commented
I understand; I just wonder about always including a column if none of AWX's inventory sources populate it.

2019-05-17 19:00 UTC, cdvv7788 commented
@wenottingham So we can include it conditionally. Would that be better? It should not be that hard to check if the hosts have description if they are already fetched.

2019-05-19 12:44 UTC, lijok commented
@wenottingham @cdvv7788 to chime in, i know import inventory from a script sets description to "imported" https://github.com/ansible/awx/blob/devel/awx/main/management/commands/inventory_import.py#L667

2019-06-07 19:46 UTC, mabashian requested changes

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/hosts/hosts.partial.html
> +                                <div class="List-tableCell name-column InventoryManage-breakWord col-lg-3">
@jlariza I don't think we want the description to be a link - we don't have that pattern anywhere else in the application.  I think you'll want this code to look like:

```
                                <div class="List-tableCell name-column InventoryManage-breakWord col-lg-3">
                                    {{host.description }}
                                </div>
```

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
> +                uiSref: ".edit({inventory_id: host.inventory_id,host_id: host.id})",
See above - this shouldn't be a link.  You can get rid of `key`, `uiSref`, `ngClass`, `dataHostId`, `dataType`, and `class`.

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
> +                columnClass: 'col-lg-3 col-md-3 col-sm-8 col-xs-7',
Change to `columnClass: 'col-lg-3 col-md-6 col-sm-8 col-xs-7',`

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
> +                columnClass: 'col-lg-3 col-md-3 col-sm-8 col-xs-7',
Change to `columnClass: 'd-none d-lg-flex col-lg-3'`

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
> +                columnClass: 'd-none d-md-flex List-tableCell col-lg-3 col-md-3'
Change to `columnClass: 'd-none d-lg-flex List-tableCell col-lg-3'`

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js
> +            columnClass: 'col-lg-2 col-sm-3 col-xs-5 text-right',
Change to `columnClass: 'col-lg-3 col-md-6 col-sm-4 col-xs-5 text-right',`

2019-06-07 19:46 UTC, mabashian commented on awx/ui/client/src/inventories-hosts/hosts/hosts.partial.html
> +                            <div class="List-tableHeader" base-path="hosts" collection="hosts" dataset="host_dataset" column-sort="" column-field="name" column-iterator="host" column-no-sort="undefin
We'll want to apply the same Bootstrap grid layout classes (`col-...`) to these elements.  See the proposed changes to `related-host.list.js` for context.  For `lg` sized screens we should show all 4 columns but we want to hide groups/description on smaller screens.

2019-06-15 18:25 UTC, jlariza commented
Hi @mabashian, thanks for the recommendations. I just applied them. I had to make some modifications in order to make it look good on mobile.

Please, check it again and let me know if something is missing. Thank you

2019-07-02 13:33 UTC, mabashian commented
@jlariza noticing a couple of things when taking a look at the most recent changes:

1) I doesn't seem like ellipse-ifying the description is working as expected on `#/hosts`.  The column alignment gets thrown off when the description is wider than the column.
<img width="1496" alt="Screen Shot 2019-07-02 at 9 21 04 AM" src="https://user-images.githubusercontent.com/9889020/60516480-d5b10680-9cab-11e9-96f1-c454266237c2.png">

2) If we're going to ellipse the description on `#/hosts` we should do the same thing for the hosts list within an inventory `#/inventories/inventory/:id/hosts`
<img width="1511" alt="Screen Shot 2019-07-02 at 9 27 01 AM" src="https://user-images.githubusercontent.com/9889020/60516621-2294dd00-9cac-11e9-97ff-0d4007a5f3d0.png">

We'll also need you to squash down your commits before we get this merged in.

2019-07-03 20:56 UTC, jlariza commented
@mabashian Done. I removed the ellipsis class; it made no sense to cut the description If what we want is to ease each host identification.

I already squashed the commits. Thank you

2019-07-09 21:30 UTC, mabashian commented
recheck

2019-07-10 16:05 UTC, mabashian commented
@jlariza I branched off of your branch and made a few extra changes.  That PR can be found here: https://github.com/ansible/awx/pull/4304.  If it's alright I'd like to move forward with these changes in that PR.  Thank you for your work on this feature and I apologize that it's taken this long to get the ball rolling.

2019-07-10 16:19 UTC, jlariza commented
@mabashian sure, go Ahead. I check the changes you made and they make sense. Thank you!

2019-07-16 14:31 UTC, mabashian commented
@jlariza https://github.com/ansible/awx/pull/4304 has been merged - thanks for your efforts on that.  We appreciate it!

2019-07-16 14:31 UTC, closed without merging