fixed row item labels to view horizontally instead of vertically
ansible/awx pull request #4077
Opened 2019-06-14 03:26 UTC by j-shade

##### SUMMARY

As seen in issue #4076, the Item Labels on Templates and other elements overflow vertically, which when a lot of labels are in use, can overflow the screen making the expanded view a little less user friendly. The change required occurs on the following css element

.at-RowItem--labels

such that the display field must be changed from inline-block to inline-flex.

The design consideration improves usability as well as screen real-estate as observed in the images provided in the issue.

Only the changes in lines 262-265 are required (actually just the single line)

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
3.5.0
```

##### ADDITIONAL INFORMATION

```

```

2019-06-25 06:02 UTC, MrBones757 commented
Is there any update / feedback on this change?

2019-06-25 12:11 UTC, ryanpetrello commented
recheck

2019-06-25 12:45 UTC, kialam requested changes
@j-shade Actual changes look good to me.

A note on your CSS/LESS formatting: the lack of white space between selector combinators is inconsistent with the rest of our codebase and in general makes styles harder to read.

Once the formatting concern has been addressed I will be happy to approve the PR.

Nice work on this and thanks for your contribution!

2019-06-25 12:45 UTC, kialam commented on awx/ui/client/lib/components/list/_index.less
> +    display: inline-flex;
👍

2019-06-26 01:20 UTC, j-shade commented
@kialam changes have been fixed :)

2019-06-26 12:27 UTC, kialam approved these changes

2019-06-26 12:50 UTC, merged