ensure "create_preload_data" is honored in docker-compose deployments
ansible/awx pull request #4107
Opened 2019-06-19 11:50 UTC by gizero

##### SUMMARY

Use a templated version of launch_awx_task.sh which conditionally preloads
sample data according to create_preload_data value.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
"awx: 5.0.0"
```

##### ADDITIONAL INFORMATION

Without this patch, docker-compose deployments end up having preloaded data into the DB, regardless of `create_preload_data`value.

```

```

2019-06-19 12:45 UTC, ryanpetrello approved these changes

2019-06-19 12:46 UTC, ryanpetrello requested changes
<img width="614" alt="image" src="https://user-images.githubusercontent.com/214912/59766591-87911180-926e-11e9-977f-e7c3b2287d85.png">

Does this need to be changed, too?  Did you test this by building an image and installing?

2019-06-19 22:02 UTC, gizero commented
> Does this need to be changed, too? Did you test this by building an image and installing?

What do you mean exactly here? Once it's rendered from the template, `launch_awx_task.sh` is then included into images... I run the install for a docker-compose deployment and both `create_preload_data=True` and `create_preload_data=False` work as intended. I have no k8s cluster to test with, but I don't see a reason for this patch to break k8s deployments.

2019-06-20 13:38 UTC, shanemcd commented
I believe @ryanpetrello is pointing out that you changed the name of the file but there is a reference to the old file in the Dockerfile. You don't need a Kubernetes cluster to build your own image, just comment out [this line](https://github.com/ansible/awx/blob/devel/installer/inventory#L9) an run the installer.

2019-06-20 15:22 UTC, gizero commented
This is exactly how I'm doing my tests. I'm building (successfully with and without preloaded data) my own images for the docker-compose scenario. I might be wrong, but IMO the `Dockerfile` is using the file that the Ansible task I changed is in charge of generating, which name did not change (same `dest`). What changed is this file's `src` that switched from `launch_awx_task.sh` to `launch_awx_task.sh.j2`. Isn't this the case?

2019-06-21 14:25 UTC, macno commented
> <img alt="image" width="614" src="https://user-images.githubusercontent.com/214912/59766591-87911180-926e-11e9-977f-e7c3b2287d85.png">
> 
> Does this need to be changed, too? Did you test this by building an image and installing?

No, it's not. In the Dockerfile we use the destination file which is not changed.

2019-06-25 20:45 UTC, gizero commented
Gentle ping! Does my comment clarify your concern?

2019-07-08 19:27 UTC, shanemcd requested changes
I dont love making this template, at least for this reason. Wouldnt it make more sense to call this as a conditional task in the installer? IIRC we do this on the Kubernetes / OpenShift side already. So for the local docker method it would be something like:

```
$ docker exec -ti tools_awx_1 awx-manage create_preload_data
```

2019-11-12 15:30 UTC, shanemcd approved these changes
Somehow there are no conflicts after all this time. Merging now.

2019-11-12 15:43 UTC, shanemcd commented
Gate failed, going to attempt to rebase myself and push to your branch.

2019-11-12 16:44 UTC, merged