Install a newer version of sqlite in the development image
ansible/awx pull request #4198
Opened 2019-07-01 17:06 UTC by shanemcd

2019-07-01 17:09 UTC, ryanpetrello approved these changes

2019-07-02 15:23 UTC, rooftopcellist approved these changes
lgtm, this just needs to be rebased before merging so the ui tests pass @shanemcd

2019-07-03 17:51 UTC, ryanpetrello commented
@jbradberry does this unblock you?

2019-07-03 20:25 UTC, jbradberry commented
> @jbradberry can you give this a whirl, and see if it unblocks you?

@ryanpetrello I can't at the current time, but what I was using (aside from letting Django 2.2 try to run) was running from the bash command line, `python -c "import sqlite3; print(sqlite3.sqlite_version)"`.  If it shows the new version, it should be good.  Also if running the tests work.

2019-07-08 14:31 UTC, jbradberry requested changes
```
(awx) bash-4.2$ sqlite3 --version
3.28.0 2019-04-16 19:49:53 884b4b7e502b4e991677b53971277adfaf0a04a284f8e483e2553d0f83156b50
(awx) bash-4.2$ python -c "import sqlite3; print(sqlite3.sqlite_version)"
3.7.17
```
I'm afraid that this is not sufficient.

2019-07-08 14:34 UTC, jbradberry commented
```
(awx) bash-4.2$ make test
Traceback (most recent call last):
  File "/venv/awx/bin/py.test", line 11, in <module>
    sys.exit(main())
  ... redacted ...
  File "/venv/awx/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 66, in <module>
    check_sqlite_version()
  File "/venv/awx/lib64/python3.6/site-packages/django/db/backends/sqlite3/base.py", line 63, in check_sqlite_version
    raise ImproperlyConfigured('SQLite 3.8.3 or later is required (found %s).' % Database.sqlite_version)
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17).
make: *** [test] Error 1
```

2019-07-08 16:14 UTC, shanemcd commented
Doesnt work, closing this.

2019-07-08 16:14 UTC, closed without merging