fix regression where clicking inside popover closed it
ansible/awx pull request #4557
Opened 2019-08-22 15:18 UTC by jlmitch5

link #4443

Looks like bootstrap had taken over the outer element of the popover and changed the id we were using to tell if we clicked inside or not (maybe due to an upgrade or something).  I wrapped the content around a span with the id to fix it.

2019-08-22 15:26 UTC, jakemcdermott requested changes

2019-08-22 15:26 UTC, jakemcdermott commented on awx/ui/client/src/shared/directives.js
> +                debugger;
left a debug statement here

2019-08-22 15:26 UTC, dsesami requested changes
all good, just drop the debugger line I think and it's solid

2019-08-22 15:26 UTC, dsesami commented on awx/ui/client/src/shared/directives.js
> +                debugger;
meant to drop this?

2019-08-22 16:56 UTC, jakemcdermott approved these changes

2019-08-22 16:57 UTC, dsesami approved these changes

2019-08-26 14:49 UTC, jlmitch5 commented
recheck

2019-08-26 15:26 UTC, merged