[WIP] Add SSL capability to our AMQP transport
ansible/awx pull request #4595
Opened 2019-08-26 17:11 UTC by ghjm

##### SUMMARY
Add the ability to use SSL when connecting to AMQP (RabbitMQ) via our kombu transport. New settings in settings.py are used to control server certificate verification.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API

##### AWX VERSION

6.1.0

2019-08-26 17:17 UTC, ryanpetrello commented on awx/main/dispatch/kombu.py
> +        if settings.BROKER_URL[:5].lower() == 'amqps':
nitpick: `settings.BROKER_URL.lower().startswith('amqps')`

2019-08-26 17:18 UTC, ryanpetrello approved these changes

2019-08-26 17:20 UTC, ghjm commented on awx/main/dispatch/kombu.py
> +        if settings.BROKER_URL[:5].lower() == 'amqps':
Yeah, I did it this way to avoid the compute penalty of lowercasing the whole string ... which I agree is absurd in this case since the string will be short

2019-08-26 17:30 UTC, ryanpetrello approved these changes

2019-08-26 18:17 UTC, chrismeyersfsu commented on awx/main/dispatch/kombu.py
> +                super(_SSLTransport, self).__init__(*args, **kwargs)
You know you want to use that python3 super

2019-08-26 18:23 UTC, chrismeyersfsu commented on awx/main/dispatch/kombu.py
> +                self.client.ssl = {
What lib uses this hidden gem of a setting? In kombu it sets `self.client.ssl` to a boolean, `True` 
 https://github.com/celery/kombu/blob/v4.5.0/kombu/transport/pyamqp.py#L179

2019-08-26 18:41 UTC, ghjm commented on awx/main/dispatch/kombu.py
> +                self.client.ssl = {
Right, which is a wrapper around https://github.com/celery/py-amqp/blob/master/amqp/transport.py#L293, which can take True if you want SSL with default options or a dict if you want to specify the options.

2019-08-26 18:41 UTC, ghjm commented on awx/main/dispatch/kombu.py
> +                super(_SSLTransport, self).__init__(*args, **kwargs)
I really really do

2019-08-26 19:44 UTC, ghjm commented
recheck

2019-08-26 19:52 UTC, chrismeyersfsu approved these changes

2019-08-26 20:13 UTC, wenottingham commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
If these are settings, they should be in Tower settings, not hardcoded.

2019-08-26 20:31 UTC, ghjm commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
The values here are the defaults.  You can change them in settings.py.

2019-08-26 20:32 UTC, ghjm commented
recheck

2019-08-27 00:52 UTC, wenottingham commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
That's still not in the actual tower settings - we don't want to add settings.py-only settings.

2019-08-27 00:54 UTC, wenottingham requested changes
If the cert verification and cacert bundle location are intended to be admin-modifiable, they should be in Tower settings.

2019-08-27 03:24 UTC, ryanpetrello commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
@wenottingham these are going to be pretty tricky to pull-off w/ API-based changes because *many* of our processes that perform RabbitMQ binding do so _at process startup_ time, and I'm not sure how well `kombu` will take to these values just changing automatically on-the-fly.  I'm okay with these config options being something you set _system-wide_ in the API, but I think realistically, it's going to mean you have to restart all your services everywhere for things to take effect when you change these.

2019-08-27 03:26 UTC, ryanpetrello commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
Also, when we eventually do this same dance for postgres, those are going to _have to_ be `settings.py`-only.

2019-08-27 14:58 UTC, wenottingham commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
I think RMQ at least has to be a database setting, because if it ever gets out of sync in settings.py, things just won't work, correct?

2019-08-27 15:01 UTC, ryanpetrello commented on awx/settings/defaults.py
> +AMQPS_CA_BUNDLE = '/etc/pki/tls/certs/ca-bundle.crt'
Yea, I think putting these in `main/conf.py` as API-configurable settings makes sense, but I just want to make it clear that I think the procedure for "switching to SSL on RMQ" should be:

1.  Update these settings in the API
2. Restart all AWX/Tower services everywhere

Adding code to cause all message-bus oriented services to auto-detect and rebind their *active* connection pools automatically is going to be a real nightmare, because the message bus *is* what we traditionally use to broadcast these types of events.

A certain component of enabling this feature is going to have to involve a few setting changes and restarting services.

2019-09-16 13:49 UTC, ghjm commented
I'm closing this PR because the Tower-to-RabbitMQ connection is always to localhost, so SSL isn't needed.

2019-09-16 13:49 UTC, closed without merging