Add project detail and unit tests
ansible/awx pull request #4965
Opened 2019-10-09 15:10 UTC by marshmalien

##### SUMMARY
* Add project detail view
* Add project detail unit tests
* Extend project type checking 

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
<img width="1436" alt="Screen Shot 2019-10-09 at 11 03 25 AM" src="https://user-images.githubusercontent.com/15881645/66494020-fcd65b80-ea84-11e9-8f7e-aac7442d4d90.png">

2019-10-09 18:27 UTC, mabashian commented on awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx
> +      modifiedBy = `${formatDateString(modified)} ${i18n._(t`by`)} ${
This is going to be nit-picky but can we go ahead and wrap the entire thing (as opposed to just `by`) for translation like https://github.com/ansible/awx/pull/4915/files#diff-41634e48aece6599257ec1cf59a0cbb8R111-R114

That lets the translator re-arrange the order of elements depending on the langauage

2019-10-09 18:31 UTC, mabashian requested changes
Just left one small comment - otherwise this looks great!

2019-10-09 21:30 UTC, ryanpetrello commented
@marshmalien could you rebase this PR against `devel` to get CI passing?

2019-10-14 18:07 UTC, mabashian approved these changes
🎉

2019-10-14 18:30 UTC, merged