remove inv source update job blocking
ansible/awx pull request #5328
Opened 2019-11-14 19:47 UTC by chrismeyersfsu

related to https://github.com/ansible/awx/issues/4809

* Before, if an inventory source, that lives in the inventory associated
with a job template, is actively running, any job associated with that
inventory would be blocked.
* Now, that restriciton is lifted. Jobs that have inventory w/ sources
updating are not blocked (they may still be blocked for other reasons).

2019-11-14 22:25 UTC, ryanpetrello reviewed
https://www.xkcd.com/1172/

I wonder who's workflow we're going to break with this :/

2019-11-15 01:31 UTC, AlanCoding requested changes
@fosterseth had some really important points to raise on this.

2019-11-20 19:24 UTC, chrismeyersfsu commented
This is not the wanted behavior.

2019-11-20 19:24 UTC, closed without merging

2019-11-20 21:07 UTC, omgjlk commented
😢

2019-11-20 21:18 UTC, fosterseth commented
The desired behavior is to prevent an inventory source from blocking an already-running or pending job, not the other way around. It's a simple change but will do some stability checking to make sure everything clicks into place.

2020-01-16 14:50 UTC, sdktr commented
If understood correctly this fix
1) allows updating the inventory during a template run
2) but the currently running jobs won't have access to the new inventory (e.g. to access updated hostvars)

Should #2 be fixed by running 'meta: refresh_inventory' within a play? Should that refresh the inventory data available to the play to the one updated while this Job was already running?

2020-01-16 14:56 UTC, AlanCoding commented
No, we do not have any means of updating inventory from the database mid-play. That would require opening up some new IPC mechanism to securely transfer the data.

2020-01-16 15:28 UTC, sdktr commented
> No, we do not have any means of updating inventory from the database mid-play. That would require opening up some new IPC mechanism to securely transfer the data.

Thanks for clearing that up @AlanCoding ; we've been trying to do the equivalent of 'meta: refresh_inventory' in Ansible terms within AWX, this explains why updating 'our currently used' inventory doesn't work in AWX with or without this PR.