Update deployment.yml.j2
ansible/awx pull request #5358
Opened 2019-11-20 13:20 UTC by ilijamt

Allow deployments on Kubernetes version 1.16, 
This change will support Kubernetes up to version 1.9

##### SUMMARY
Running the installer to deploy to K8S doesn't work for creating the apps as apps/v1beta1 has been deprecated in 1.16

see #5286 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

2019-11-20 16:57 UTC, shanemcd requested changes
Please take my feedback on the linked issue into account.

2019-11-20 20:53 UTC, shanemcd commented
I just spent a few minutes and put this together:

```yaml
- name: Get Kubernetes API version
  command: |
    {{ kubectl_or_oc }} version -o json
  register: kube_version

- name: Extract server version from command output
  set_fact:
    kube_api_version: "{{ (kube_version.stdout | from_json).serverVersion.gitVersion[1:] }}"

- name: Determine StatefulSet api version
  set_fact:
    kubernetes_statefulset_api_version: "{{ 'api/v1' if kube_api_version is version('1.9', '>=') else 'apps/v1beta1' }}"
```

This can go anywhere before [here](https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/tasks/main.yml#L189).

2019-11-20 22:57 UTC, ilijamt commented
I cannot test on an older version of kubernetes, < 1.9 so I couldn't be sure that the response is the same, I've checked 1.15 and 1.16, and these modifications work.

2019-11-21 13:10 UTC, shanemcd approved these changes
Thank you for collaborating with me on this!

2019-11-21 13:27 UTC, merged