[WIP] experiment with pageless pagination for job events
ansible/awx pull request #5766
Opened 2020-01-25 05:06 UTC by ryanpetrello

cc @jakemcdermott 

related: https://github.com/ansible/awx/pull/5679

```shell
~ curl -ks "https://awx/api/v2/jobs/10/job_events/?order_by=-counter" | jq '.results[] | "\(.counter) \(.start_line) \(.event)"'
"56 154 playbook_on_stats"
"55 154 runner_on_ok"
"54 151 runner_item_on_ok"
"53 148 runner_item_on_ok"
"52 145 runner_item_on_ok"
"51 142 runner_item_on_ok"
"50 139 runner_item_on_ok"
"49 136 runner_item_on_ok"
"48 133 runner_item_on_ok"
"47 130 runner_item_on_ok"
"46 127 runner_item_on_ok"
"45 124 runner_item_on_ok"
"44 121 runner_item_on_ok"
"43 118 runner_item_on_ok"
"42 115 runner_item_on_ok"
"41 112 runner_item_on_ok"
"40 109 runner_item_on_ok"
"39 106 runner_item_on_ok"
"38 103 runner_item_on_ok"
"37 100 runner_item_on_ok"
"36 97 runner_item_on_ok"
"35 94 runner_item_on_ok"
"34 91 runner_item_on_ok"
"33 88 runner_item_on_ok"
"32 85 runner_item_on_ok"
~ curl -ks "https://awx/api/v2/jobs/10/job_events/?order_by=-counter" | jq '.next'
"https://awx/api/v2/jobs/10/job_events/?after=32&order_by=-counter"
curl -ks "https://awx/api/v2/jobs/10/job_events/?after=32&order_by=-counter" | jq '.results[] | "\(.counter) \(.start_line) \(.event)"'
"31 82 runner_item_on_ok"
"30 79 runner_item_on_ok"
"29 76 runner_item_on_ok"
"28 73 runner_item_on_ok"
"27 70 runner_item_on_ok"
"26 67 runner_item_on_ok"
"25 64 runner_item_on_ok"
"24 61 runner_item_on_ok"
"23 58 runner_item_on_ok"
"22 55 runner_item_on_ok"
"21 52 runner_item_on_ok"
"20 49 runner_item_on_ok"
"19 46 runner_item_on_ok"
"18 43 runner_item_on_ok"
"17 40 runner_item_on_ok"
"16 37 runner_item_on_ok"
"15 34 runner_item_on_ok"
"14 31 runner_item_on_ok"
"13 28 runner_item_on_ok"
"12 25 runner_item_on_ok"
"11 22 runner_item_on_ok"
"10 19 runner_item_on_ok"
"9 16 runner_item_on_ok"
"8 13 runner_item_on_ok"
"7 10 runner_item_on_ok"
~ curl -ks "https://awx/api/v2/jobs/10/job_events/?after=7&order_by=-counter" | jq '.results[] | "\(.counter) \(.start_line) \(.event)"'
"6 7 runner_item_on_ok"
"5 4 runner_item_on_ok"
"4 4 runner_on_start"
"3 2 playbook_on_task_start"
"2 0 playbook_on_play_start"
"1 0 playbook_on_start"
~ curl -ks "https://awx/api/v2/jobs/10/job_events/?after=7&order_by=-counter" | jq '.next'
null
```

2020-01-25 05:33 UTC, ryanpetrello commented
Here's a job w/ 5M events paged backwards if I add an index on `(job_id, counter)`.  Note the page speeds since we don't have to deal with `COUNT()`:

<img width="737" alt="image" src="https://user-images.githubusercontent.com/214912/73116773-55354a00-3f0a-11ea-90c9-f444dccfab17.png">

2020-01-25 05:47 UTC, ryanpetrello commented
Here's the same comparison for 35M events:

<img width="357" alt="image" src="https://user-images.githubusercontent.com/214912/73116897-23bd7e00-3f0c-11ea-9e10-7eff0e1d335a.png">

<img width="549" alt="image" src="https://user-images.githubusercontent.com/214912/73116904-32a43080-3f0c-11ea-9c48-a340fdcb9472.png">

2020-01-25 18:45 UTC, jakemcdermott commented
FWIW, whether  we do `page=5`, `counter__gte=120&page_size=25`, or `after=120` style query params doesn't make much of a difference ui-side in terms of implementation (or changing the existing one). So if doing any of these is helpful from an api performance perspective we should do it.

Does this implementation retain the _count_ field? I do not see it in the screenshots.

We currently use that to determine the total scrolling range in `ui_next` and also to know which events to request when the user clicks `page last` (current ui and `ui_next`).

2020-01-25 19:30 UTC, jakemcdermott reviewed
https://github.com/ansible/awx/pull/5766#issuecomment-578431765

2020-01-26 01:26 UTC, jakemcdermott commented
@ryanpetrello @wenottingham @matburt 

The urgency of the problem we're trying to solve is not lost on me.  _If we must remove the count field the api_, I will make the needed adjustments in the current ui. That said, an accurate reading of the remote row count is needed for `ui_next` to work properly and so all of the work we've done so far there will need to be reconsidered and probably completely reworked. This took us the better part of 8 weeks to do. Our timeline, estimates, and planning for the redesign will be significantly impacted by this and so I would just like to make sure all of the facts are on the table before moving forward.

2020-01-27 13:40 UTC, matburt commented
From a sheer performance standpoint this looks good and is definitely where we are heading. On the other hand, I also get the difficulty overall on the UI and this is a pretty significant change on the API that could drastically affect API consumers.

I wonder if we can find a middle ground somewhere that involves caching a known count involving *all* of the events and remove the `count` property when the events are `filtered` based on record properties. We could count the number of events once the job is finished and display that in the case of the count?

I'm spitballing here. @jakemcdermott where does the count make the most sense and where it could it be removed without impacting the UI?

2020-01-27 15:32 UTC, ryanpetrello commented
I want to stress that at this point, this is mostly an experimental POC (as the title suggests 😄).  I'm just starting to profile the event requests at 1B+ events and come up with ideas that will improve performance for us.

2020-01-27 15:45 UTC, wenottingham commented
If we are experimenting on 'count'-less API results, will we need this for `/jobs/` and `/unified_jobs` in the future?

2020-01-27 16:41 UTC, ryanpetrello commented
@wenottingham _maybe_?  That seems like a much trickier ask to me.

2020-01-27 19:30 UTC, matburt commented
Eliminating counts anywhere other than events is definitely more drastic.

2020-01-27 19:54 UTC, jakemcdermott commented
> I wonder if we can find a middle ground somewhere that involves caching a known count involving all of the events and remove the count property when the events are filtered based on record properties. 

:man_shrugging: There is no reason it can't be done. 

We don't want drastically change the scrolling behavior as the user moves between filtered and unfiltered states. Without a remote count to normalize the scrolling range in _all_ cases, the most obvious option for building something like [this](https://tower-mockups.testing.ansible.com/patternfly/jobs/jobs-output/) that would technically work for both filtered and unfiltered states is just to go back to what we've done in the past and use an infinite scroll that grows from either end of the job results, depending on which end you start from.

The library we currently use to create virtualized lists has an example you can look at to get a better idea of what I mean: https://codesandbox.io/s/x70ly749rq

It will entail a considerably more complex implementation than the one we are currently working with in `ui_next` and there will no longer be any usability improvement to speak of on this page when moving over to the new ui.

2020-01-28 14:48 UTC, jakemcdermott requested changes
Keeping a count on the related job events list at the scale of some of our most valued customers is a major challenge, and I do get that this presents considerable difficulty to the API.

Removing the counts doesn't _solve_ this problem so much as redirect it into the frontend, so I think we should look at this more like a last resort rather than a forgone conclusion.

The performance numbers in this PR demonstrate that removing the counts will speed up the loading times of the related  job event list. They do not explain why or if we _must_ remove the counts.

Would you please share little more context on why _this_ approach is needed? Specifically, what _other_ solutions have been considered? Taking into consideration all of the other optimizations we've merged so far, what would be the net result of _not_ doing this? Finally, what are the maintenance tasks referred to in #5590 and to what extent will they be improved by merging this PR?

2020-02-10 19:42 UTC, ryanpetrello commented
Closing this for now until I have time to investigate further.

2020-02-10 19:42 UTC, closed without merging