Fixes update failure on TeamEdit
ansible/awx pull request #5809
Opened 2020-01-31 19:11 UTC by AlexSCorey

##### SUMMARY
This addresses #5799.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
9.1.1
```

##### ADDITIONAL INFORMATION
![Team Update](https://user-images.githubusercontent.com/39280967/73566991-564b0780-4433-11ea-96c9-40e5aa37a6e0.gif)

2020-01-31 19:19 UTC, marshmalien commented on awx/ui_next/src/screens/Team/TeamEdit/TeamEdit.jsx
> +      setError(error);
The name of the thrown exception and the name of the value passed to `setError` should match.

2020-01-31 19:58 UTC, marshmalien requested changes
Nice job refactoring TeamEdit! Found one thing we should fix before merging in my previous comment.

2020-01-31 20:15 UTC, marshmalien approved these changes

2020-02-03 14:06 UTC, appuk commented
LGTM! I have tested this PR and Team Edit works as expected

2020-02-03 14:43 UTC, merged