change docker data dir
ansible/awx pull request #581
Opened 2017-11-04 18:24 UTC by emj365

##### SUMMARY
every time host start pg data would be lost, so it's better not use `/tmp`

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - Installer

2017-11-08 01:58 UTC, matburt requested changes
I don't particularly like this approach any better than `/tmp`.

I think the better approach would be to obey TMPDIR.

This field is meant to work as an evaluation construct and is really intended to be changed.

2017-11-08 02:41 UTC, emj365 commented
as a new awx user, when I test that with the default setup, that resting(migration take much time) of every host restart make me confuse and feel not convenience.

2017-11-09 15:28 UTC, matburt commented
This is exactly why that is overrideable.

2017-11-09 15:28 UTC, closed without merging

2017-11-13 02:53 UTC, rromanchuk commented
I think a good compromise would just be to remind people that this directory is the persistent store of their entire project and that the default data directory will get wiped out every time there is a server reboot. In other words, it should almost *never* be left unchanged. The only valid context for this default is for building AWX as a demo. It's objectively a bad default, there are a handful of support tickets because this value not being changed.

2018-04-10 12:39 UTC, khelkun commented
Just a testimony:
- I used docker-compose installation, created a dummy inventory and tried down/up to ensure my data was persisting so I assumed it was because my dummy inventory was still existing after docker-compose down/up.
- So I started to really evaluate awx: did setup a few projects, job templates, inventories, etc ...
- Then a few days later I rebooted my workstation, and all my awx content were gone.

I should have pay more attention to the `postgres_data_dir` in [installer/inventory](https://github.com/ansible/awx/blob/devel/installer/inventory#L30) but I didn't and was a bit confused after the reboot of my workstation.