Add ingress_hostname to openshift
ansible/awx pull request #5948
Opened 2020-02-15 13:39 UTC by jdorel

##### SUMMARY

Add `ingress_hostname` to Openshift for route configuration.

Also renames `kubernetes_ingress_hostname` to `ingress_hostname` for easier configuration.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - Installer

##### ADDITIONAL INFORMATION

Maybe the change of `kubernetes_ingress_hostname` to `ingress_hostname` isn't worth the breaking change of variable name ?

2020-04-27 16:46 UTC, shanemcd commented on installer/inventory
> +# Ingress Configuratio
Missing an `n` here?

2020-04-27 16:46 UTC, shanemcd commented on installer/inventory
> +ingress_hostname=awx.example.org
Other default variables in this file are commented out. We should probably do that here too.

2020-04-27 16:47 UTC, shanemcd requested changes
I think I would like to keep the variable name the same, to prevent breaking current installs.

2020-05-01 20:04 UTC, ryanpetrello approved these changes
any more thoughts on this one @shanemcd ?

2020-08-19 21:40 UTC, ryanpetrello commented
It looks like this was effectively added via: 52712a0d9a4

2020-08-19 21:40 UTC, closed without merging