Make DNS search domain configurable for awx containers
ansible/awx pull request #651
Opened 2017-11-14 22:39 UTC by tumbl3w33d

related #646

##### SUMMARY
Implementation of feature requested by #646 (configurable search domain for containers).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
1.0.1.208
```

2017-11-15 19:57 UTC, matburt requested changes

2017-11-15 19:57 UTC, matburt commented on installer/inventory
> +# Container configuration
Possibly rename this to `Container networking configuration` and then in the future we can re-use this section if we had other related configurations.

2017-11-15 20:24 UTC, tumbl3w33d commented
Updated @matburt

2017-11-16 04:32 UTC, matburt approved these changes

2017-11-16 04:32 UTC, merged