Converts most of our route render prop usage to children
ansible/awx pull request #6639
Opened 2020-04-07 20:24 UTC by mabashian

##### SUMMARY
https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#upgrade-to-react-router-v51 is the basic gist.

There are a couple of places that I didn't touch:

1) index.jsx - There are some complicated use cases in here and I didn't want to go refactoring the whole thing
2) Inventories.jsx - This component is class based.  It'll be easier to make this change when we convert it to a functional component and can use hooks.
3) Templates.jsx - see Inventories.jsx.

##### ISSUE TYPE
 - Task

##### COMPONENT NAME
 - UI

2020-04-07 21:14 UTC, mabashian commented
Looks like there are some unit tests that need fixing in here

2020-04-08 12:37 UTC, jlmitch5 requested changes
just a few little things, looks awesome though, thanks for doing this!

2020-04-08 12:37 UTC, jlmitch5 commented on awx/ui_next/src/components/Breadcrumbs/Breadcrumbs.jsx
> +import { Link, Route, withRouter, useRouteMatch } from 'react-router-dom';
I think we should probably move from using withRoute

2020-04-08 12:37 UTC, jlmitch5 commented on awx/ui_next/src/components/Breadcrumbs/Breadcrumbs.jsx
> +const Breadcrumbs = ({ breadcrumbConfig, match }) => {
Also passing match...It'd be better to get what we need in Crumb using hooks I think

2020-04-08 12:37 UTC, jlmitch5 commented on awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroups.jsx
> +      <Route key="add" path="/inventories/inventory/:id/groups/add">
I'm pretty sure I updated these internal inventory ones to using children as opposed to render as part of my recently merged associate/disassociate host groups pr based on review feedback.  You might want to rebase.

2020-04-08 13:55 UTC, jlmitch5 approved these changes
looks good!

2020-04-08 14:49 UTC, merged