Add note about code sytle for ui_next
ansible/awx pull request #6684
Opened 2020-04-13 17:56 UTC by nixocio

Add note about code style for `ui_next`.

2020-04-13 17:57 UTC, nixocio commented on awx/ui_next/CONTRIBUTING.md
> +    - [Setting up .po files to give to translation team](#setting-up-po-files-to-give-to-translation-team)
For whatever reason my editor is modifying this block. Let me update this.

2020-04-13 18:31 UTC, marshmalien requested changes
Thanks for adding this to the docs!

2020-04-13 18:31 UTC, marshmalien commented on awx/ui_next/CONTRIBUTING.md
> +- We adopt the following code sytle guide:
Small spelling error `sytle`.

2020-04-13 21:21 UTC, marshmalien approved these changes

2020-04-13 22:18 UTC, jakemcdermott commented
regate

2020-04-14 13:16 UTC, marshmalien commented
regate

2020-04-14 18:05 UTC, merged