Inventory source list
ansible/awx pull request #6740
Opened 2020-04-17 17:29 UTC by AlexSCorey

##### SUMMARY
This addresses #6573.  It also adds tests.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
11.0
```

##### ADDITIONAL INFORMATION

2020-04-17 17:30 UTC, AlexSCorey commented on awx/ui_next/src/api/models/Inventories.js
> +    });
prettier made this change

2020-04-17 17:33 UTC, AlexSCorey commented on awx/ui_next/src/api/models/Inventories.js
> +    });
And this 1.  I can undo it if necessary.

2020-04-17 17:52 UTC, AlexSCorey commented on awx/ui_next/src/api/models/Inventories.js
> +      data: {
And this 1. I can undo it if necessary.

2020-04-17 19:30 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySouceSyncButton.test.jsx
> +import InventorySourceSycnButton from './InventorySourceSycnButton';
Spelling errors:
* Component `InventorySourceSycnButton` => `InventorySourceSyncButton`
* Test file `InventorySouceSyncButton.test.jsx` => `InventorySourceSyncButton.test.jsx`

2020-04-22 18:47 UTC, marshmalien requested changes

2020-04-22 18:47 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
> +              inventorySource.source = scLabel;
We should avoid mutating this data object if possible. Instead we could create a new "label" prop and update the source column via that prop.

2020-04-22 18:47 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.test.jsx
> +    await act(async () => {
This component doesn't perform any effects or state updates, so I don't think we need to mount it with `await act(async () `

2020-04-22 18:55 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.test.jsx
> +    jest.clearAllMocks();
We should unmount the component after we finish our assertions.

2020-04-22 19:04 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.test.jsx
> +    expect(wrapper.find('ToolbarAddButton').length).toBe(0);
We should clear the mocks and unmount the component here as well.

2020-04-22 19:28 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
> +                pluralizedItemName={i18n._(t`Inventory Source`)}
Inventory Sources?

2020-04-22 19:29 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.jsx
> +        pluralizedItemName={i18n._(t`Sources`)}
Inventory Sources?

2020-04-22 19:31 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.jsx
> +    <>
We could remove this fragment since this is only returning a single element.

2020-04-23 19:37 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceList.test.jsx
> +    // await sleep(5);
Can we remove this line?

2020-04-23 19:48 UTC, marshmalien commented on awx/ui_next/src/screens/Inventory/InventorySources/InventorySourceListItem.test.jsx
> +    act(() => {
I don't think we need `act()` to mount this component since it doesn't have effects or state updates.

2020-04-27 20:33 UTC, marshmalien approved these changes

2020-04-30 14:30 UTC, dsesami approved these changes
Looks solid. :heavy_check_mark:

2020-04-30 14:47 UTC, merged