Add support Prompt on Launch for Workflow Job Template
ansible/awx pull request #7176
Opened 2020-05-27 21:17 UTC by nixocio

Add support Prompt on Launch for Workflow Job Template

see: https://github.com/ansible/awx/issues/5819

2020-06-02 15:39 UTC, AlexSCorey requested changes
This is a really good start.  Most of the changes are just improvement/patterns the follow.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +  const [scmField, ,] = useField('scm_branch');
You don't need the commas at the end there.  That line can just be `const [scmField, ,scmHelpers] = useField('scm_branch');`.  See below  https://github.com/ansible/awx/pull/7176/files#diff-99aa1a47d9d5977839537f14e31fade6R157 for where the scmHelpers should be used.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +  const [inventory, setInventory] = useState(
This `useState` isn't necessary.  I believe this is done because the api expects an inventory id when you save, however the inventory look up needs the whole inventory object.  However, we can remove this line, and let formik have the whole inventory object, then pull out the inventory ID, just before we post it to the api in this file.  
 Actually, we are already doing that.
https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.jsx#L23and like we are doing here https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.jsx#L22

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +              setInventory(value);
You can remove this line

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +              inventoryHelpers.setValue(value.id);
send the whole inventory instead of just the id

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +            value={inventory}
the value becomes inventoryField

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +  const [, inventoryMeta, inventoryHelpers] = useField('inventory');
this becomes const `[inventoryField, inventoryMeta, inventoryHelpers] = useField('inventory');`

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +          {(inventoryMeta.touched || formikValues.ask_inventory_on_launch) &&
rather than using formikContext, which is a rather large object with all the formik data, above where your other `useFields` are do `const [askInventoryOnLaunchFIeld]=useField('ask_inventory_on_launch')`.  Then this line becomes `{(inventoryMeta.touched || askInventoryOnLaunchFIeld) &&`  and you no longer are having to use and keep track of the whole formik context.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +import { useField, withFormik, useFormikContext } from 'formik';
remove useFormikContext here.  I explain below a different want of reaching the same outcome, that follows are existing pattern a bit better.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +  const { values: formikValues } = useFormikContext();
remove this

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
> +    // Test FieldWithPrompt elements
This type of comment is helpful to me to know what is happening, but rather than leave a comment in the code that shares that lets make this a separate test.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +              scmField.onChange(event);
use setValue here as it imperatively sets the value for the field.  onChange is used for more general purposes.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +              limitField.onChange(event);
use setValue here as it imperatively sets the value for the field. onChange is used for more general purposes.

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
>            label={i18n._(t`Source Control Branch`)}
Title case this label

2020-06-02 15:39 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.jsx
> +  const [limitField, limitMeta] = useField('limit');
add limitHelpers https://github.com/ansible/awx/pull/7176/files#diff-99aa1a47d9d5977839537f14e31fade6R139

2020-06-03 21:13 UTC, AlexSCorey requested changes
This looks really good.  Just remove that 1 `.only` on that test and you will be good to go.

2020-06-03 21:13 UTC, AlexSCorey commented on awx/ui_next/src/screens/Template/shared/WorkflowJobTemplateForm.test.jsx
> +  test.only('test changes in FieldWithPrompt', async () => {
remove the `.only`

2020-06-03 21:19 UTC, AlexSCorey approved these changes
LGTM.  Well done!

2020-06-04 19:20 UTC, dsesami requested changes
some quick feedback: see https://github.com/ansible/awx/pull/7101

Inventory needs to be removable with an `x` on the chip if prompt on launch is enabled. The above PR shows how that is done, follow up with @keithjgrant to implement it similarly.

2020-06-08 18:06 UTC, dsesami approved these changes
looks good! I see that this is still marked as WIP. is there anything else you'd like to change? functionality _seems_ right.

2020-06-09 12:21 UTC, nixocio commented
I kept as `WIP` due to a few failing unit-tests, updating them now.

2020-06-09 18:38 UTC, merged