allow support for saml + 2-factor
ansible/awx pull request #721
Opened 2017-11-27 20:34 UTC by chrismeyersfsu

related to https://github.com/ansible/awx/issues/48

* python-social-auth has SOCIAL_AUTH_SAML_SECURITY_CONFIG, which is
forwarded to python-saml settings configuration. This commit exposes
SOCIAL_AUTH_SAML_SECURITY_CONFIG to configure tower in tower to allow users
to set requestedAuthnContext, which will disable the requesting of password
type auth from the idp. Thus, it's up to the idp to choose which auth to
use (i.e. 2-factor).

2017-11-27 20:37 UTC, wenottingham commented
As part of this, should we switch the default to "let the IdP decide"?

2017-11-28 14:46 UTC, chrismeyersfsu commented
Yep, done.

2017-11-29 14:34 UTC, wwitzel3 requested changes
I'd like to see some unit tests for the new field types.

2017-11-29 16:46 UTC, jangsutsr commented on awx/main/tests/unit/conf/test_fields.py
> +import pytest
There's `awx/mainconf/tests/unit/` available for hosting Tower Configuration tests.

2017-11-29 19:51 UTC, wwitzel3 approved these changes

2017-11-29 19:54 UTC, merged