Instance id fallback
ansible/awx pull request #7321
Opened 2020-06-10 21:09 UTC by jladdjr

When creating instance id refer to _list_ of hostvars. If first hostvar is not available, walk down list of hostvars until one is defined. This allows awx to be backwards compatible when forming instance id.

Fixes https://github.com/ansible/awx/issues/3461

2020-06-10 21:13 UTC, jladdjr commented
@AlanCoding - base on https://github.com/ansible/awx/issues/3461, looks like we should also update the settings for gce, is that right? And are there any others that you're aware of?

2020-06-10 21:57 UTC, AlanCoding commented
no, I think we should only be doing this for vmware, because we solved the other cases by other means. VMware, due to the sub-properties, is the only one we made an exception for where the hostvars keys changed. Because of that, there's no workaround for it.

2020-06-11 01:32 UTC, AlanCoding requested changes
passes testing 👍 

only remove the EC2 instance id change

2020-06-11 16:54 UTC, jladdjr commented
@AlanCoding reverted change to `EC2_INSTANCE_ID_VAR`

2020-06-11 18:30 UTC, AlanCoding approved these changes

2020-06-11 19:22 UTC, jladdjr commented
recheck

2020-06-11 21:32 UTC, jladdjr commented
I think this is in Zuul limbo. Reaching out to some folks to try to get this unstuck.

2020-06-11 21:49 UTC, merged