Adds application details view
ansible/awx pull request #7355
Opened 2020-06-16 19:01 UTC by AlexSCorey

##### SUMMARY
This addresses https://github.com/ansible/awx/issues/7236.  Adds support for Application Details view including delete functionality.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2020-06-16 at 2 59 12 PM](https://user-images.githubusercontent.com/39280967/84816400-3f701080-afe2-11ea-811a-930ee24f9e20.png)

2020-06-17 17:47 UTC, nixocio requested changes
I got this code locally. Feature seems to be working fine. Good job @AlexSCorey . Minor changes.

2020-06-17 17:47 UTC, nixocio commented on awx/ui_next/src/screens/Application/Application/Application.jsx
> +        <CardCloseButton linkTo="/teams" />
```suggestion
        <CardCloseButton linkTo="/applications" />
```

2020-06-17 17:47 UTC, nixocio commented on awx/ui_next/src/screens/Application/Application/Application.test.jsx
> +  organiation: 10,
```suggestion
  organization: 10,
```

2020-06-18 13:48 UTC, nixocio approved these changes

2020-06-23 17:52 UTC, dsesami approved these changes
Bit annoyed with the PF guidelines on capitalization, but approved nonetheless. Looks great!

2020-06-24 13:29 UTC, dsesami commented
regate

2020-06-24 13:31 UTC, dsesami commented
@AlexSCorey there is one linting issue to be fixed:

```

2020-06-23 17:55:52.195727 | static |
2020-06-23 17:55:52.196036 | static | /awx_devel/awx/ui_next/src/screens/Application/Application/Application.jsx
2020-06-23 17:55:52.196129 | static |   21:10  error  TabbedCardHeader not found in '../../../components/Card'  import/named
2020-06-23 17:55:52.196145 | static |
2020-06-23 17:55:52.196185 | static | ✖ 1 problem (1 error, 0 warnings)
```

2020-06-24 14:37 UTC, merged