Add feature to add Credential Type
ansible/awx pull request #7426
Opened 2020-06-23 21:25 UTC by nixocio

Add feature to add Credential Type.

See: https://github.com/ansible/awx/issues/7325

2020-06-26 19:28 UTC, dsesami approved these changes
Looks great!

2020-06-29 16:00 UTC, jlmitch5 requested changes
looks good!  just a quick rename of the yaml util fn

2020-06-29 16:00 UTC, jlmitch5 commented on awx/ui_next/src/util/yaml.test.js
> +});
nice tests

2020-06-29 16:00 UTC, jlmitch5 commented on awx/ui_next/src/util/yaml.js
> +export function parseVariableFields(variableField) {
can you rename to parseVariableField

2020-06-29 17:41 UTC, nixocio commented on awx/ui_next/src/util/yaml.js
> +export function parseVariableFields(variableField) {
@jlmitch5 updated per comment.

2020-06-29 18:34 UTC, jlmitch5 approved these changes

2020-06-29 18:54 UTC, merged