Adds Tokens List
ansible/awx pull request #7436
Opened 2020-06-24 17:14 UTC by AlexSCorey

##### SUMMARY
This addresses #7419.  This is the first PR to bring in Tokens to the new project.  The mock ups show a sync button, but there is no sync functionality, or sync button on this list on the old ui. Couple of things to consider about this list:
1)  Whether the tokens can be edited.  They can't in the old ui
2) How/whether to show a details view.  
3) This PR does not include add or edit functionality of a token.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI
##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2020-06-24 at 1 09 27 PM](https://user-images.githubusercontent.com/39280967/85601681-98f8c080-b61c-11ea-905c-a8c95a06971a.png)

2020-06-29 16:06 UTC, jlmitch5 approved these changes
looks great!

2020-06-29 16:06 UTC, jlmitch5 commented on awx/ui_next/src/screens/User/User.jsx
> +  if (me?.id === Number(match.params.id)) {
I would use Config here rather than pass down with props.

2020-06-29 20:26 UTC, dsesami requested changes
Currently, there's a bug if the token has an application associated with it.

1. In the old UI, make an application. Create a token, and then add the application to that token.
2. Visit the tokens list for the user in the new UI.

![Screenshot from 2020-06-29 16-25-30](https://user-images.githubusercontent.com/19942822/86052651-502e7680-ba25-11ea-8687-1bcda6444881.png)

2020-06-29 20:33 UTC, dsesami commented
we've confirmed that the above issue is because applications are marked as mandatory in the new UI when they are actually optional. setting it to optional should fix this.

2020-06-30 16:24 UTC, dsesami approved these changes

2020-06-30 16:51 UTC, merged