[WIP]Fix cli export
ansible/awx pull request #7460
Opened 2020-06-28 23:14 UTC by takezyou

##### SUMMARY

Bug fix export and import for AWX CLI.

related #7447 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - CLI

##### AWX VERSION

```
13.0.1
```

2020-06-29 13:28 UTC, jbradberry requested changes

2020-06-29 13:28 UTC, jbradberry commented on awxkit/awxkit/api/pages/inventory.py
> +    NATURAL_KEY = ('organization', 'hosts', 'groups', 'name')
Hosts and groups should not be part of the natural key here.  The natural key is supposed to be a (mostly) fixed minimal subset of the information of the object needed to uniquely look it up.

2020-06-29 13:28 UTC, jbradberry commented on awxkit/awxkit/api/pages/inventory.py
> +    NATURAL_KEY = ('group',)
I'm pretty sure 'group' isn't a field or related on the Group model.  You should check the Django models under the awx/ subtree of this repo to get a sense of what fields are used for the uniqueness constraint for this model.

2020-06-29 13:28 UTC, jbradberry commented on awxkit/awxkit/api/pages/inventory.py
> +    NATURAL_KEY = ('host',)
As with Groups, I don't believe 'host' is a field on Host.

2020-06-29 13:28 UTC, jbradberry commented on awxkit/awxkit/api/pages/inventory.py
> +    NATURAL_KEY = ('group',)
Also, I just noticed that this is on Groups.  The plural page type shouldn't get the natural key, only the singular version.

2020-06-29 17:51 UTC, jbradberry commented
I'm afraid that this latest change has moved further away from where things probably should be.  Here's what I think:

- [ ] `Host` and `Group` should be in `EXPORTABLE_DEPENDENT_OBJECTS`
- [ ] they should _not_ be in `EXPORTABLE_RESOURCES`
- [ ] they should be in `EXPORTABLE_RELATIONS`
- [ ] looking at awx/main/models these are both `unique_together` on 'name' plus 'inventory', these should be the fields used for the `natural_key`

This would export the objects only as part of the related objects on exported inventories, and would create them in-place on that inventory during import, plus hooking up the relationships between them.

With all of that said, though, I'm not sure what would need to be done about inventory sources, inventory scripts, and special inventories.  Maybe @chrismeyersfsu can comment about this?

2020-06-30 13:25 UTC, takezyou commented
This ed6d68c commit can import but `maximum recursion depth exceeded while calling a Python object`  error.

2020-06-30 16:10 UTC, ryanpetrello commented
Hey @takezyou,

Thanks for taking a stab at this.  When you're done tinkering, let's please squash all these commits into a single one - it looks like there was a lot of activity here.

2020-07-02 16:58 UTC, jladdjr commented
hi @takezyou - I tried kicking the tires on these changes and found that while I can now see hosts in my export, the import isn't restoring the hosts. So, looks like we may be missing the second half.

For reference, here's the new export data that I'm seeing:
![image](https://user-images.githubusercontent.com/4440360/86388379-919f6b80-bc49-11ea-8afd-e7e531e161c0.png)


> With all of that said, though, I'm not sure what would need to be done about inventory sources, inventory scripts, and special inventories. 

^ as @jbradberry mentioned, inventories do touch on several other resources, though. Maybe, as a first step, we could have a PR that covers inventory basics (inventories, groups, hosts), and then grow that to include scripts, credentials, venvs, smart inventories, etc. There's a lot of ground to cover here.

2020-07-02 19:53 UTC, jladdjr commented
@takezyou - TLDR: looks like issue w/ exporting / importing hosts is tied to the underlying export code itself, and not the changes made in this PR.

---

@jbradberry and I took a look at this and found that the export logic doesn't seem to be handling the case of hosts correctly. Here, specifically: https://github.com/ansible/awx/blob/devel/awxkit/awxkit/api/pages/api.py#L109-L114

The issue is that exported hosts -- like this one:

![image](https://user-images.githubusercontent.com/4440360/86403492-ad633b80-bc62-11ea-86e1-483c7907243e.png)

.. are missing a `"natural_key"` section. That section is a cue to the export code that the JSON block represents _an object that should be created_, instead of just being a reference to the object.

I think @jbradberry can explain this much better than I can, but from what I gathered, things seem tricky because of variations on how endpoints work; some allow creating resources and also associating resources, some are restricted to just creating the resource. Apparently, the inventory / host case falls into one category, while WFJTs and WFJTNs fall into the other. Sounds like the code block I mentioned had one case in mind, but not the other.

2020-07-04 16:21 UTC, takezyou commented
@jladdjr Thank you comment!
I was able to notice the same problem when I was debugging it.

> I think @jbradberry can explain this much better than I can, but from what I gathered, things seem tricky because of variations on how endpoints work; some allow creating resources and also associating resources, some are restricted to just creating the resource. Apparently, the inventory / host case falls into one category, while WFJTs and WFJTNs fall into the other. Sounds like the code block I mentioned had one case in mind, but not the other.

@jbradberry What do you think about this?

2020-07-08 18:59 UTC, jbradberry commented
@takezyou I have nothing further to add than what @jladdjr said.

2020-07-22 03:18 UTC, takezyou commented
@jbradberry Please review.

2020-07-23 17:13 UTC, jbradberry commented
@takezyou I think that the underlying issue needs to be addressed, rather than bolting on support on a case-by-case basis.

2020-10-12 15:28 UTC, jbradberry commented
As noted, solving this is trickier than the approach outlined above.  Closing this in favor of #8368.

2020-10-12 15:28 UTC, closed without merging