Adding hosts from smart inventories to dashboard count
ansible/awx pull request #7590
Opened 2020-07-09 14:57 UTC by john-westcott-iv

##### SUMMARY

On the dashboard (and likely other places) hosts which are included in smart inventories do not appear in counts. This change corrects the dashboard.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API
 
##### AWX VERSION

```
awx: 13.0.0
```

##### ADDITIONAL INFORMATION

Create a smart inventory.
Create a new user in a different org.
Give that user read permissions to the smart inventory.
Load the users dashboard. The hosts = 0 inventories = 1.

After this change hosts = <number of hosts in inventory>

```

```

2020-07-09 16:46 UTC, wenottingham commented on awx/api/views/__init__.py
> +                for host in inventory.hosts.filter(**{}).only(*['name']):
I defer to eng, but I'd be worried about performance here.

2020-07-10 14:23 UTC, ryanpetrello requested changes
In practice, smart inventory host calculation can be **very** slow, because users can define whatever (inperformant) query they like.  We're fairly aggressive about avoiding slow queries on the dashboard (it's gotten us into the trouble in the past performance-wise, because it's the first page users land on when they log in, and so a slow dashboard is both compounding, and _very_ noticeable), so I'm probably a 👎 on this idea.

2020-07-10 14:29 UTC, ryanpetrello commented
@john-westcott-iv 

We *do* have a feature that enables an automatic background build/calculation of smart inventories:

https://docs.ansible.com/ansible-tower/latest/html/userguide/inventories.html#smart-inventories

If you enable this, we keep around `SmartInventoryMembership` records.  But it's off by default, so it's probably not something we can rely on for accuracy cc @AlanCoding @chrismeyersfsu

2020-07-13 13:25 UTC, AlanCoding commented
IIRC, we changed things so that we update that on job runs, so it might not be horrendously inaccurate.

I kind of see how that approach might work, but I don't have much appetite for fixing that, and it would obfuscate the meaning of the count as well.

```
Create a smart inventory.
Create a new user in a different org.
Give that user read permissions to the smart inventory.
Load the users dashboard. The hosts = 0 inventories = 1.
```

But does that mean that the superuser will see 2 hosts in the count? That could be problematic for the user to interpret it. I would want to rewind this to the original issue that people report, and very likely solve it with new fields, instead of changing what existing fields represent.

2020-08-19 21:35 UTC, closed without merging