Add the ability to specify K8S/OCP credentials on a Job Template
ansible/awx pull request #7629
Opened 2020-07-15 21:38 UTC by ryanpetrello

see: https://github.com/ansible/awx/issues/5735

2020-07-15 21:38 UTC, ryanpetrello commented
```
bash-4.4$ cat /var/lib/awx/projects/k8s/example.yml
---

- hosts: all
  gather_facts: false
  tasks:
    - name: Get a list of all pods from any namespace
      k8s_info:
        kind: Pod
```

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/214912/87600664-051d9000-c6c2-11ea-92ea-430ca4237bb3.png">

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/214912/87600712-0949ad80-c6c2-11ea-9bf9-2d8e676e6a35.png">

2020-07-15 21:44 UTC, wenottingham commented
cc @geerlingguy - does the community.kubernetes collection take these same parameters?

2020-07-16 00:06 UTC, jakemcdermott approved these changes

2020-07-16 01:30 UTC, AlanCoding commented
I'm guessing that these are expected to work specifically because of the lookup plugin

https://github.com/ansible-collections/community.kubernetes/blob/6b28ef3c17449fdd34d0b51c3846278db80239c7/plugins/connection/kubectl.py#L130

which is a very very important plugin in the grand scheme of things...

2020-07-16 12:32 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
> +                .match(/^(machine|cloud|net|ssh|vault|kubernetes)$/)) {
I'd check myself but I'm running into an issue where my download speed drops to 40 kb/s while building the image locally and don't want to tie up my computer for 45 minutes:

![Screenshot from 2020-07-16 08-24-17](https://user-images.githubusercontent.com/9753817/87670496-cfb68800-c73d-11ea-8817-47f8e4471e71.png)

... so I'll just ask: Is the credential type displayed on the job launch credential prompt as well? If not we'll need to update some more code & you'd want to start here: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/prompt/steps/credential/prompt-credential.controller.js


We'll also want to check the form, job details, and prompt on the new UI.

2020-07-16 13:18 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
> +                .match(/^(machine|cloud|net|ssh|vault|kubernetes)$/)) {
ALRIGHT!!, I made it, finally :confetti_ball:

2020-07-16 13:19 UTC, jakemcdermott requested changes

2020-07-16 13:19 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
>          }));
![Screenshot from 2020-07-16 09-16-03](https://user-images.githubusercontent.com/9753817/87675426-5e7ad300-c745-11ea-82f9-1cccb9c5668e.png)

Icon missing on form, you can add it here: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/job_templates/multi-credential/multi-credential.partial.html#L22-L37

2020-07-16 13:37 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
> +                .match(/^(machine|cloud|net|ssh|vault|kubernetes)$/)) {
Icon is missing for prompts
![Screenshot from 2020-07-16 09-21-30](https://user-images.githubusercontent.com/9753817/87676870-1f4d8180-c747-11ea-88f1-b93bd8247a51.png)

That's rendered [here](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/prompt/steps/credential/prompt-credential.partial.html#L14) using `promptData.prompts.credentials`, which I _think_ ultimately comes from [here](https://github.com/ansible/awx/blob/devel/awx/ui/client/lib/components/relaunchButton/relaunchButton.component.js#L87)

2020-07-16 13:56 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
> +                .match(/^(machine|cloud|net|ssh|vault|kubernetes)$/)) {
We'll need to make sure the new option gets displayed on the multicredential select lookup in ui_next:
![cred_form](https://user-images.githubusercontent.com/9753817/87679688-7a34a800-c74a-11ea-8c49-a876515015dc.gif)

... which I presume to be something to be added [here](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/Lookup/CredentialLookup.jsx#L81)

2020-07-16 14:00 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
> +                .match(/^(machine|cloud|net|ssh|vault|kubernetes)$/)) {
We'll also need to make sure the new category is displayed on launch prompts in `ui_next`:
![cred_prompt](https://user-images.githubusercontent.com/9753817/87680207-1fe81700-c74b-11ea-9d8b-bfaf71cd3448.gif)

That code lives [here](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/LaunchPrompt/steps/CredentialsStep.jsx#L119)

2020-07-16 14:04 UTC, jakemcdermott commented on awx/ui/client/src/templates/job_templates/multi-credential/multi-credential-modal.directive.js
> +                .match(/^(machine|cloud|net|ssh|vault|kubernetes)$/)) {
JDetails for `ui_next` looks fine:
![cred_jdetails](https://user-images.githubusercontent.com/9753817/87680656-b1578900-c74b-11ea-8c50-144a781f251c.gif)

2020-07-16 14:21 UTC, geerlingguy commented
@wenottingham - Yes `K8S_AUTH_TOKEN` and `K8S_AUTH_API_KEY` work with the K8s modules. Note that I typically prefer using a `K8S_AUTH_KUBECONFIG` instead, but it depends on how the user can authenticate to the cluster and I know with at least some versions of OCP the credentials are structured differently than I'm used to with vanilla K8s clusters.

2020-07-16 15:25 UTC, ryanpetrello commented
@jakemcdermott here's my latest upload w/ the old UI:

![Kapture 2020-07-16 at 10 57 24](https://user-images.githubusercontent.com/214912/87686994-32fee500-c753-11ea-9910-38c28b6bc829.gif)

...and here's the new UI:

![Kapture 2020-07-16 at 11 24 22](https://user-images.githubusercontent.com/214912/87690050-f503c000-c756-11ea-8d66-afdfa1347ad7.gif)

2020-07-16 15:29 UTC, ryanpetrello commented
@jakemcdermott it _looks like_ the new UI doesn't currently have the validation support for "hey, you removed a required credential at prompt on launch, and you should replace it before continuing".  Do you see evidence otherwise?

2020-07-16 15:35 UTC, jakemcdermott commented
@ryanpetrello 
![beautiful](https://user-images.githubusercontent.com/9753817/87691257-64c67a80-c758-11ea-8891-d984eb9066e9.gif)

2020-07-16 15:37 UTC, jakemcdermott approved these changes

2020-07-16 15:41 UTC, ryanpetrello commented
@jakemcdermott I'm gonna add some tests, then will merge.

2020-07-16 23:34 UTC, jakemcdermott commented
![doit](https://user-images.githubusercontent.com/9753817/87732582-64030800-c79b-11ea-98c9-8c0605ef0f2e.gif)

2020-07-16 23:35 UTC, jakemcdermott approved these changes

2020-07-16 23:37 UTC, jakemcdermott commented
![doitt](https://user-images.githubusercontent.com/9753817/87732691-b80dec80-c79b-11ea-8440-c188bf717312.gif)

2020-07-17 16:43 UTC, elyezer approved these changes

2020-07-17 17:07 UTC, merged