Exposes created attribute via API for User django ORM
ansible/awx pull request #7635
Opened 2020-07-16 22:02 UTC by tchellomello

##### SUMMARY
Many of the API endpoints allow us to search by the `created` attribute, however, the `User` model (inherited from Django ORM) does not have the `created` by `date_joined`. 

So this patch allows users explore the API by filtering Users by date of creation. 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION

```
awx: 13.0.0
```

##### ADDITIONAL INFORMATION

**before**
```json
### API

# curl -k  -u api_user-L "https://tower.tatu.home/api/v2/users/?created__gt=2020-06-15T21:35:56.845726" 2>/dev/null| jq
{
  "detail": "User has no field named 'created'"
}

## cmd
>>> User.objects.get(username='admin')
<User: admin>
>>> User.objects.get(username='admin').created
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'User' object has no attribute 'created'
```

**after**
```json
### API

# curl -k  -u api_user-L "https://tower.tatu.home/api/v2/users/?created__gt=2020-06-15T21:35:56.845726" 2>/dev/null| jq
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "id": 6,
      "type": "user",
      "url": "/api/v2/users/6/",
      "related": {
        "teams": "/api/v2/users/6/teams/",
        "organizations": "/api/v2/users/6/organizations/",
        "admin_of_organizations": "/api/v2/users/6/admin_of_organizations/",
        "projects": "/api/v2/users/6/projects/",
        "credentials": "/api/v2/users/6/credentials/",
        "roles": "/api/v2/users/6/roles/",
        "activity_stream": "/api/v2/users/6/activity_stream/",
        "access_list": "/api/v2/users/6/access_list/",
        "tokens": "/api/v2/users/6/tokens/",
        "authorized_tokens": "/api/v2/users/6/authorized_tokens/",
        "personal_tokens": "/api/v2/users/6/personal_tokens/"
      },
      "summary_fields": {
        "user_capabilities": {
          "edit": true,
          "delete": true
        }
      },
      "created": "2020-06-16T21:10:06.503737Z",
      "username": "rider",
      "first_name": "rider",
      "last_name": "",
      "email": "rider@localhost",
      "is_superuser": false,
      "is_system_auditor": false,
      "ldap_dn": "",
      "last_login": null,
      "external_account": null,
      "auth": []
    }
  ]
}

### cmd
In [2]: User.objects.get(username='admin')                                                                                                                             
Out[2]: <User: admin>

In [3]: User.objects.get(username='admin').created                                                                                                                     
Out[3]: datetime.datetime(2020, 6, 1, 20, 57, 37, 325849, tzinfo=<UTC>)
```

2020-07-17 13:14 UTC, ryanpetrello requested changes
@tchellomello 

Would you add a test for this?

https://github.com/ansible/awx/blob/devel/awx/main/tests/functional/api/test_user.py

Thanks!

2020-07-17 20:19 UTC, tchellomello commented
@ryanpetrello added a test. I thought in creating another test using the `created__gt=<timestamp>` but I think the current one will cover the API and `cli` scenarios. Please let me know what you think. Thanks @ryanpetrello :+1:

2020-07-20 15:44 UTC, ryanpetrello approved these changes

2020-07-20 19:40 UTC, merged

2020-07-20 19:54 UTC, ryanpetrello commented
Thanks @tchellomello!