Adds support for toggling approval notifications on orgs and wfjts
ansible/awx pull request #7803
Opened 2020-08-03 19:32 UTC by mabashian

##### SUMMARY
link #6425 

Here it is in action:

<img width="1488" alt="Screen Shot 2020-08-03 at 3 29 38 PM" src="https://user-images.githubusercontent.com/9889020/89219668-36410000-d59e-11ea-96cf-46c10e5c2840.png">
<img width="1427" alt="Screen Shot 2020-08-03 at 3 29 53 PM" src="https://user-images.githubusercontent.com/9889020/89219669-37722d00-d59e-11ea-8707-df4b87944f38.png">

I needed to add the methods to the org/wfjt api models directly because not every model that consumes that mixin will have an `approvals` endpoint.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2020-08-10 23:44 UTC, jakemcdermott approved these changes

2020-08-20 16:36 UTC, dsesami requested changes
This has an issue that @jakemcdermott experienced with a similar list of toggles. Basically, if you toggle one item, it disables ALL the toggles and flashes them (even if there are 10 different, unrelated notifications on the page). This can be jarring visually to the user. Jake's approach was to make sure that only the row involving that particular notification was disabled during the animation.

2020-08-20 18:28 UTC, dsesami approved these changes

2020-08-20 18:38 UTC, dsesami commented
@mabashian will merge this after tests pass.

2020-08-20 20:23 UTC, merged