Remove showExpandCollapse prop from the DataListToolbar calls
ansible/awx pull request #7842
Opened 2020-08-05 22:11 UTC by nixocio

Remove showExpandCollapse prop from the DataListToolbar calls. This is
not an expected prop to be passed to this component.

Inside DataListToolbar.

```
  const showExpandCollapse = onCompact && onExpand;
```

In order to use this feature, `onCompact` and `onExpand` props should
be passed.

2020-08-05 22:12 UTC, nixocio commented
See: https://github.com/ansible/awx/blob/1c0dc1cccb19feb41d2d5c5fdfdb81647515efb8/awx/ui_next/src/components/DataListToolbar/DataListToolbar.jsx#L20

2020-08-06 13:40 UTC, jakemcdermott requested changes
:+1: Nice find

@nixocio Let's remove it from the associated unit test as well: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/DataListToolbar/DataListToolbar.test.jsx#L39

2020-08-06 15:02 UTC, nixocio commented
done @jakemcdermott.

2020-08-06 15:57 UTC, jakemcdermott approved these changes

2020-08-06 16:16 UTC, merged