Add Ad Hoc Commands
ansible/awx pull request #7905
Opened 2020-08-13 21:46 UTC by AlexSCorey

##### SUMMARY
This addresses #6603 for just Inventory Groups List.  It proposes a new workflow for the ad hoc commands so that we treat it more like prompt on launch. Talking with @trahman73 about the error handling of this feature we also introduce a new work flow for errors. We decided that because this feature is now in a wizard on top of a list that all of the content errors(ususally rendered inside a card on a page and not in a modal) would be rendered inside a modal.  The tooltips, while complete, could probably use an extra set of eyes. I modified them a bit, from the classic ui tooltips, so that they could be translated a bit easier and with more context.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION

![ad hoc](https://user-images.githubusercontent.com/39280967/90190256-af093e80-dd8c-11ea-9adb-f6c1e10ee54c.gif)

2020-08-13 22:14 UTC, trahman73 commented
Nice job @AlexSCorey I'll leave my UX review below.

All examples are on the mockups here:
https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-groups/
https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-groups-run/
https://tower-mockups.testing.ansible.com/patternfly/inventories/inventories-groups-run-creds/

- Move Run command button after Add button (Delete will be last)
- Sentence casing on the main button to read "Run command" 
- Change the wizard title from "Ad Hoc Commands" to "Run command" to match the action button
- Sentence case the left nav of the wizard to read "Machine credential"
- Remove the Machine credential heading with (?) from the second step of the wizard (the left nav is good enough here)

Thanks and please let me know if you have any questions on the above.

2020-08-14 16:20 UTC, AlexSCorey commented
> * Sentence casing on the main button to read "Run command"
> * Remove the Machine credential heading with (?) from the second step of the wizard (the left nav is good enough here)
> 
@trahman73 The main button is currently sentence cased.  As you saying that it should not be sentence cased?  Also, the heading on step 2 is just a standard label heading.  I can remove that, and, they can't launch the job until they select a credential so that asterisk isn't really necessary, but what about the tooltip?

2020-08-14 18:17 UTC, trahman73 commented
Disregard the main button comment as it is correct. We can remove the heading on the Machine credential step (including the tooltip) and disable launch until a credential is selected.

2020-08-17 14:08 UTC, mabashian commented
@AlexSCorey @trahman73 @wenottingham 

Was thinking a bit about the UX of the run command button and wanted to run an idea by y'all.  The current implementation matches up with the old UI in that the button is disabled until something is selected (group, host, etc).  This action pre-fills the limit with whatever has been selected.  I think that's great and we should keep that but I'm now wondering why that button is disabled until you select something.  The `limit` is not a required field so you could run an adhoc command against all the hosts/groups in the list without providing a limit.  Should we make this button enabled by default (maybe as long as there's at least one host/group in the list)?  Clicking the button without first selecting a host/group would just result in an empty limit, which is valid.

2020-08-17 14:11 UTC, mabashian commented
@AlexSCorey I think we should preselect a verbosity for the user on initial load.  Looks like this is the one that's selected in the old UI:

<img width="468" alt="Screen Shot 2020-08-17 at 10 11 32 AM" src="https://user-images.githubusercontent.com/9889020/90405658-11ef2400-e072-11ea-98fa-bac7a9e89a76.png">

2020-08-17 14:13 UTC, mabashian commented
@AlexSCorey this Arguments field actually isn't required:

<img width="879" alt="Screen Shot 2020-08-17 at 10 12 57 AM" src="https://user-images.githubusercontent.com/9889020/90405831-511d7500-e072-11ea-9cdd-65be868ba4dc.png">

2020-08-17 14:25 UTC, mabashian commented
@trahman73 @AlexSCorey I'm a little worried about using a tag-based approach for the limit pre-fill.  It feels like a mixture of two different UX flows (tags & an input).  Patterns within the limit are flexible and there's some syntactical sugar that's supported: https://docs.ansible.com/ansible/latest/user_guide/intro_patterns.html#common-patterns.  It looks like a user could still do something like that on the input side of the field but they wouldn't be able to do any modifications to the tagged hosts/groups.  I'm just wondering if it would be easier to understand as a single input.  Pre-filled hosts/groups would be separated by a colon or comma in the input string.

2020-08-17 15:00 UTC, trahman73 commented
@AlexSCorey I agree with @mabashian about keeping the Run command button active.
We can change the Limit field to a regular text input as per the additional feedback. I will update the mocks as well from the feedback so far.

2020-08-18 17:50 UTC, jlmitch5 reviewed
the kebabification of the action buttons looks good, just some key prop changes!

2020-08-18 17:50 UTC, jlmitch5 commented on awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
> +              key="add"
probably want a different key name

2020-08-18 17:50 UTC, jlmitch5 commented on awx/ui_next/src/screens/Inventory/InventoryGroups/InventoryGroupsList.jsx
> +          variant="danger"
probably want key prop here

2020-08-24 17:50 UTC, jlmitch5 approved these changes
looks good

2020-09-01 12:53 UTC, unlikelyzero commented
@one-t can you help us identify some test cases that would flesh out the UI.

2020-09-01 15:25 UTC, dsesami requested changes
Two issues:

1. In the legacy UI, the tooltip for Parameters changes dynamically based on what module is selected. It provides a link to the ansible documentation. The hyperlink is correct, but the ansible docs currently improperly redirect -- I'm going to file a separate issue for that. We should provide a link to the docs depending on which module is selected, though.
2. Follow these steps:
- Create an inventory with just one host, `localhost`. This is also the default Demo Inventory if you have that.
- Assign that host to Group1
- Launch any command against Group1. The simplest example is `ping`. In the old UI, this succeeds. In the new UI, I receive a FAILED result, giving me a usage message for `ping`, which implies that the command has syntax errors.

![Screenshot from 2020-09-01 11-24-28](https://user-images.githubusercontent.com/19942822/91872304-b8781f00-ec45-11ea-9fe8-0da0b07473b5.png)

The same `ping` against the same group works in the old UI:
![Screenshot from 2020-09-01 11-24-52](https://user-images.githubusercontent.com/19942822/91872340-c4fc7780-ec45-11ea-9aab-2e618360a90c.png)

2020-09-01 15:38 UTC, dsesami commented
Also, when linking to modules, I've been informed that the old UI uses an outdated link mechanism. Modules links should be formed like this: https://docs.ansible.com/ansible/latest/modules/ping_module.html

2020-09-01 20:17 UTC, AlexSCorey commented
> Two issues:
> 
> 1. In the legacy UI, the tooltip for Parameters changes dynamically based on what module is selected. It provides a link to the ansible documentation. The hyperlink is correct, but the ansible docs currently improperly redirect -- I'm going to file a separate issue for that. We should provide a link to the docs depending on which module is selected, though.
> 2. Follow these steps:
> 
> * Create an inventory with just one host, `localhost`. This is also the default Demo Inventory if you have that.
> * Assign that host to Group1
> * Launch any command against Group1. The simplest example is `ping`. In the old UI, this succeeds. In the new UI, I receive a FAILED result, giving me a usage message for `ping`, which implies that the command has syntax errors.
> 
> ![Screenshot from 2020-09-01 11-24-28](https://user-images.githubusercontent.com/19942822/91872304-b8781f00-ec45-11ea-9fe8-0da0b07473b5.png)
> 
> The same `ping` against the same group works in the old UI:
> ![Screenshot from 2020-09-01 11-24-52](https://user-images.githubusercontent.com/19942822/91872340-c4fc7780-ec45-11ea-9aab-2e618360a90c.png)

2020-09-09 14:22 UTC, AlexSCorey commented
recheck

2020-09-09 18:50 UTC, dsesami commented
this is almost ready -- all that's left is the hyperlinking to work properly in the tooltip for arguments.

2020-09-09 19:28 UTC, dsesami approved these changes

2020-09-09 19:53 UTC, dsesami commented
regate

2020-09-09 19:54 UTC, dsesami commented
recheck

2020-09-09 20:21 UTC, merged