Disables template and workflow template fields.
ansible/awx pull request #7975
Opened 2020-08-24 16:11 UTC by AlexSCorey

##### SUMMARY
This addresses #7973. It also addresses a bug where a user might temporarily not have labels while the label select component is doing its fetching and loading.  I did file a feature request with PF that would allow use to disable all child of `<InputGroup>` so that we would not have add styling to `<ChipHolder>` component in the template form. https://github.com/patternfly/patternfly-react/issues/4709

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2020-08-24 at 12 11 17 PM](https://user-images.githubusercontent.com/39280967/91068901-f0a6ae80-e602-11ea-9ee1-970e1a0789a6.png)
![Screen Shot 2020-08-24 at 12 11 02 PM](https://user-images.githubusercontent.com/39280967/91068905-f3090880-e602-11ea-8d24-b31582982bd6.png)

2020-08-25 16:15 UTC, jlmitch5 approved these changes
looks good, just a super small comment removal change

2020-08-25 16:15 UTC, jlmitch5 commented on awx/ui_next/src/components/Lookup/Lookup.jsx
> +          // css="background-color: #d2d2d2"
can you remove this comment

2020-09-01 13:05 UTC, unlikelyzero commented
Notes: this would be a great network server intercept to verify that no additional API calls are made that would ultimately end in a 403

2020-09-01 20:13 UTC, tiagodread requested changes
In the legacy UI, the fields: Inventory (and prompt on launch), project, playbook, Webhook service are disabled for Job templates.

![image](https://user-images.githubusercontent.com/12464858/91897898-57664080-ec71-11ea-8a4e-fe875d0982c6.png)
 
In the UI Next, Prompt on launch and Webhook service are enabled for edit, but when I try to save it I don’t have permission.

![limited_user](https://user-images.githubusercontent.com/12464858/91898419-102c7f80-ec72-11ea-81a7-415e25ed1da1.gif)

2020-09-01 20:36 UTC, tiagodread commented
You can also enable "Prompt on launch" for WFJT, but when you save, an error message is displayed:

![image](https://user-images.githubusercontent.com/12464858/91903383-8b456400-ec79-11ea-9313-74e6021fd07a.png)

2020-09-04 13:17 UTC, tiagodread commented
- Trying to select the options `Privilege Escalation Provisioning Callbacks Enable Webhook Concurrent Jobs Enable Fact Storage` the error message "You do not have permission to perform this action." is displayed:

![image](https://user-images.githubusercontent.com/12464858/92243316-b0afb900-ee97-11ea-983e-9f31995e52c4.png)
 @AlexSCorey should this inputs be enabled in this case?

2020-09-04 17:09 UTC, AlexSCorey commented
recheck

2020-09-04 18:48 UTC, AlexSCorey commented
recheck

2020-09-04 20:29 UTC, tiagodread approved these changes
Everything ok

2020-09-06 19:29 UTC, AlexSCorey commented
regate

2020-09-06 20:49 UTC, AlexSCorey commented
recheck

2020-09-06 21:26 UTC, merged