Adds cancel button to jobs list
ansible/awx pull request #7993
Opened 2020-08-25 17:55 UTC by mabashian

##### SUMMARY
link #7364 

<img width="1427" alt="Screen Shot 2020-08-25 at 1 54 32 PM" src="https://user-images.githubusercontent.com/9889020/91209972-8b25f100-e6da-11ea-83cf-ba513ed0863c.png">

![canceljob](https://user-images.githubusercontent.com/9889020/91210065-a98bec80-e6da-11ea-88e5-189721ecb4d2.gif)

This feature adds a cancel button next to the delete button on the jobs list.  This cancel button behaves like the delete button in that a user can select multiple jobs to cancel at one time.  Some general rules surrounding the button:

1) Button should be disabled until a user selects at least one job
2) Button should be disabled if user selects a job that they don't have the ability to cancel (summary_fields.user_capabilities.start is false)
3) API requests should not be made for jobs that are in a finished state.  A user can still select these rows but confirming a cancel will not actually send the request(s).  I confirmed this behavior with Taufique and Bill.

I also wanted to use the `copy` related endpoint provided on all of the job objects rather than having a big `switch` statement covering all of the different job types.  Since we didn't have anything that would support taking in an arbitrary endpoint I created `Related.js` in our models directory.  This model has generic methods covering GET/POST/DELETE/PUT/PATCH.  It doesn't inherit from the base model so I needed to pull the axios http instantiation out into something that could be consumed by more than one model.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2020-08-26 18:08 UTC, mabashian commented on awx/ui_next/src/components/JobList/JobListCancelButton.jsx
> +          {i18n.plural({
i18n.plural is no good -> see #8002 

Use low level i18n._ instead

2020-08-26 18:16 UTC, jakemcdermott requested changes
Looking good & works well. We dove into job-switching problem offline. Ultimately @mabashian and I decided on adding a util to select the job model given a `job` object as a way to avoid having to add a switch everywhere a job api is used.

2020-08-26 20:06 UTC, jakemcdermott approved these changes

2020-09-08 14:11 UTC, unlikelyzero commented
Tiago will be working on this one today

2020-09-09 16:01 UTC, tiagodread commented
@mabashian when I tried to cancel a running job using the Cancel button inside kebab (when the advanced search is enabled) nothing happens (the same occurred for delete button)

![cancel_button](https://user-images.githubusercontent.com/12464858/92623214-54380980-f29c-11ea-93da-be57eb2696f3.gif)

2020-09-10 21:32 UTC, tiagodread commented
recheck

2020-09-11 14:34 UTC, tiagodread approved these changes
Tests and stubs in place 👍🏽

2020-09-11 14:46 UTC, tiagodread commented
regate

2020-09-11 15:07 UTC, merged