Adds support for pending deletion on inventory list
ansible/awx pull request #8041
Opened 2020-08-28 18:31 UTC by mabashian

##### SUMMARY
link #7680 

This issue is a bit nuanced because it breaks from our normal delete pattern.  A couple of notes:

1) We're no longer refreshing the list after issuing successful delete requests.  This is because inventories are placed in a `pending_deletion` state after the delete request is processed.  Instead, we'll wait for a socket message that tells us that an inventory has been deleted.
2) We're now updating the `pending_deletion` field on inventory rows based on socket messages.
3) As stated in 1, we're now performing a refresh of the list only when we get a socket message saying that an inventory has been deleted.  This request should take pagination into account.
4) I added some warning text on the delete modal indicating that the inventory(ies) would be placed in a pending delete state.

List:

<img width="1446" alt="Screen Shot 2020-08-28 at 2 24 51 PM" src="https://user-images.githubusercontent.com/9889020/91603465-0980ce00-e93b-11ea-9068-d3b22f847e69.png">

Modal:

<img width="1115" alt="Screen Shot 2020-08-28 at 2 24 10 PM" src="https://user-images.githubusercontent.com/9889020/91603471-0d145500-e93b-11ea-9922-f06b7cb6bc01.png">

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2020-09-03 07:00 UTC, velzend commented
Nice feature...

2020-09-10 16:03 UTC, keithjgrant requested changes
Looks good, just a couple fixes

2020-09-10 16:03 UTC, keithjgrant commented on awx/ui_next/src/screens/Inventory/InventoryList/InventoryListItem.jsx
> +                onDoneLoading={() => setIsDisabled(false)}
These should be wrapped in useCallback to keep them hooks-safe (CopyButton references them in a useEffect)

2020-09-10 16:03 UTC, keithjgrant commented on awx/ui_next/src/screens/Inventory/InventoryList/useWsInventories.js
> +      }
A lot of nested if/else can be tricky to to follow. Maybe move part of this into a helper function(s), or maybe handle cases one at a time, returning out of this function when possible (so you don't need an `else`)?

2020-09-11 12:59 UTC, mabashian commented
@keithjgrant OK I flattened out those nested if/else's into individual cases.  If that's not what you were expecting then let me know and I'll try again.

I also came across a bug where new rows weren't fetched after copying an inventory _if_ an inventory source sync had finished before attempting to copy.  This was due to `id__in` being added to the query params.  I went ahead and fixed that in a separate commit to this PR.

2020-09-21 13:50 UTC, unlikelyzero commented
@dsesami this is ready for test

2020-09-21 18:41 UTC, keithjgrant approved these changes
looks great!

2020-09-25 19:24 UTC, dsesami commented
@mabashian this needs a rebase, then I can knock it out pretty quick.

2020-09-28 14:02 UTC, dsesami commented
I managed to crash the page with this console error: 
```Failed to load resource: the server responded with a status of 409 (Conflict)```

Recreate steps:
1. Fire up a JT that uses ansible/test-playbooks as its project. I used `ping-20.yml`, but any task that takes 5 seconds or more will do fine. 
2. Open two tabs. One tab will launch the JT, the other is the inventory view.
3. Launch the JT, then immediately try to delete the inventory while the Job is running. The page will crash.

2020-09-28 14:02 UTC, dsesami requested changes
see above comment

2020-09-29 15:39 UTC, dsesami commented
spoke with mike -- same bug as above, but with the details page's delete button instead of the list delete button.

2020-09-29 16:02 UTC, unlikelyzero commented
@dsesami @mabashian in that case, do you think we should move it out of this ticket into its own bug or address it right now in this PR?

2020-09-29 17:16 UTC, mabashian commented
@unlikelyzero @dsesami nah I can hopefully fix it pretty quickly.  If it gets messy then yea lets peel it out.

2020-09-29 19:47 UTC, dsesami approved these changes
Works great.

2020-09-29 20:07 UTC, merged