Notification Detail: show custom messages
ansible/awx pull request #8105
Opened 2020-09-08 21:08 UTC by keithjgrant

##### SUMMARY
Adds custom messages to the Notification Detail, if they have been customized. I also created an ArrayDetail component to clean up the display of multi-value details (such as Slack destination channels, Twilio destination numbers, etc)

Addresses #7877 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2020-09-10 13:00 UTC, unlikelyzero commented
@tiagodread I think you can start adding tests for this one even in it's current state

2020-09-14 14:27 UTC, tiagodread commented
@keithjgrant tests are written and once the PR receives dev review, I'll run the tests again and it can be merged.

2020-09-14 17:22 UTC, jakemcdermott requested changes

2020-09-14 17:22 UTC, jakemcdermott commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.jsx
> +            messages.workflow_approval.approved.message ||
```suggestion
            messages?.workflow_approval?.approved?.message ||
```

@keithjgrant 
`messages.workflow_approval` can be `null` so I think we need to check before referencing its properties or use optional chaining in the various places it is referenced:

![Screenshot from 2020-09-14 13-17-15](https://user-images.githubusercontent.com/9753817/93117496-f5ec9b80-f68c-11ea-94bc-3ef1e5739673.png)

![Screenshot from 2020-09-14 13-18-06](https://user-images.githubusercontent.com/9753817/93117563-0866d500-f68d-11ea-9ba2-55a556fabc66.png)

2020-09-14 17:22 UTC, jakemcdermott commented on awx/ui_next/src/screens/NotificationTemplate/shared/hasCustomMessages.js
> +      messages.workflow_approval.approved,
```suggestion
      messages?.workflow_approval?.approved,
```

2020-09-14 17:22 UTC, jakemcdermott commented on awx/ui_next/src/screens/NotificationTemplate/NotificationTemplateDetail/NotificationTemplateDetail.jsx
> +            messages.workflow_approval.approved.message ||
probably needed here as well: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/NotificationTemplate/shared/NotificationTemplateForm.jsx#L144-L170

2020-09-14 17:51 UTC, jakemcdermott commented on awx/ui_next/src/screens/NotificationTemplate/shared/hasCustomMessages.js
> +      messages.workflow_approval.approved,
probably needed here as well: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/NotificationTemplate/shared/NotificationTemplateForm.jsx#L144-L170

2020-09-14 22:41 UTC, jakemcdermott approved these changes

2020-09-14 23:36 UTC, jakemcdermott commented
After looking a bit further into the `null` `workflow_approval` field w/ @keithjgrant I'm starting to think this might be a slight data migration issue with pre-existing notification templates and the (more recently added) workflow approval feature. It's probably simpler to just handle the `null` in the ui at this point so that's what we're doing.

2020-09-15 13:33 UTC, tiagodread commented
@keithjgrant After clicking on the select all notifications on notification templates list isn’t possible to unselect items:

![chrome-capture (5)](https://user-images.githubusercontent.com/12464858/93216974-c4cca380-f73e-11ea-80f3-e8b17999ef15.gif)

2020-09-15 18:36 UTC, tiagodread approved these changes
Tests are written 👍🏽

2020-09-15 18:53 UTC, merged