Certs
ansible/awx pull request #8209
Opened 2020-09-22 21:04 UTC by rooftopcellist

##### SUMMARY

Overhaul of licensing in favor of using RH subscriptions model.  

![subscriptions-ui-flow](https://user-images.githubusercontent.com/11698892/93937342-9712cc00-fcf5-11ea-85a2-41ba9404568b.gif)

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API
 - UI
 - Installer

2020-09-24 17:16 UTC, mabashian commented on awx/ui/client/src/license/license.controller.js
> +            // What if I POST the file as a field in the License data JSON?
Still need this?

2020-09-24 17:18 UTC, mabashian commented on awx/ui_next/src/variables.js
> -export const BrandName = 'AWX';
Probably don't want to commit this change to devel

2020-09-24 18:11 UTC, jlmitch5 reviewed
Subscription should not be capitalized in these places

2020-09-24 18:11 UTC, jlmitch5 commented on awx/ui/client/src/license/license.partial.html
> +				<div class="License-helperText License-introText" ng-if="licenseMissing" translate>Welcome to Ansible Tower! Please complete the steps below to acquire a Subscription.</div>
sentence casing

2020-09-24 18:11 UTC, jlmitch5 commented on awx/ui/client/src/license/license.partial.html
> +									<translate>Please click the button below to visit Ansible's website to get a Tower Subscription.</translate>
sentence casing

2020-09-24 18:11 UTC, jlmitch5 commented on awx/ui/client/src/license/license.partial.html
> +									<translate>Provide your Red Hat or Satellite credentials below and you can choose from a list of your available Subscriptions.  If you are a Satellite user please specify the organization ID
sentence casing

2020-10-14 14:25 UTC, shanemcd requested changes
Overall looks pretty good. Just added a couple small notes on things we dont want to forget.

2020-10-14 14:25 UTC, shanemcd commented on awx/main/validators.py
> +    # TODO: replace with more actual robust logic here to allow for multiple certificates in one cert file (because this is how entitlements do)
This comment exists to make sure we dont forget about this.

2020-10-14 14:25 UTC, shanemcd commented on requirements/requirements_git.txt
> +git+https://github.com/candlepin/python-rhsm.git@python3-backport#egg=rhsm
We should fork this under the Ansible org.

2020-10-14 18:12 UTC, ryanpetrello commented on awx/main/utils/licensing.py
> +            license_setting = Setting.objects.filter(key='LICENSE').first()
Shouldn't this just be `settings.LICENSE` ?

2020-10-15 15:45 UTC, shanemcd commented
recheck

2020-10-22 15:12 UTC, closed without merging