Add execution environment list to Organizations
ansible/awx pull request #8337
Opened 2020-10-06 20:15 UTC by nixocio

Add execution environment list to Organizations

See: https://github.com/ansible/awx/issues/8210

2020-10-07 15:10 UTC, jakemcdermott approved these changes

2020-10-07 15:11 UTC, jakemcdermott approved these changes
Code lgtm and I pulled this down locally and did a bit of testing on the related list. Also lgtm!

2020-10-07 15:12 UTC, jakemcdermott commented on awx/ui_next/src/screens/Organization/OrganizationExecEnvList/OrganizationExecEnvListItem.jsx
> +              aria-label={i18n._(t`execution environment image`)}
Possibly need some sentence casing here? 
```suggestion
              aria-label={i18n._(t`Execution environment image`)}
```

2020-10-07 15:28 UTC, nixocio commented
@jakemcdermott, updated and rebased.

2020-10-12 14:05 UTC, dsesami requested changes
A few notes:
1. Sorting by Organization should be removed from this view. It is all the same organization.
2. Clicking the image link does not hyperlink anywhere. It should link to the EE details, and then the backlink should know how to go back to the list of EEs for that org, and not just back to the main list of EEs.

2020-10-12 18:43 UTC, nixocio commented
@dsesami, updated per your comments.

2020-10-12 20:53 UTC, shanemcd commented
recheck

2020-10-13 15:49 UTC, dsesami approved these changes
The hyperlink works, but the backlink needs to be "smarter". However, this is a problem throughout the application and is out of the scope of this PR.

2020-10-13 21:10 UTC, nixocio commented
regate

2020-10-13 21:35 UTC, merged