Fix integer/float errors in survey
ansible/awx pull request #8419
Opened 2020-10-20 17:30 UTC by keithjgrant

##### SUMMARY
Fix console errors for integer & float default values when setting up a template survey

addresses #8331 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

2020-10-20 17:47 UTC, jakemcdermott reviewed
lgtm, just a few nits & I think we should merge this.

2020-10-20 17:47 UTC, jakemcdermott commented on awx/ui_next/src/util/validators.jsx
> +    if (/^[0-9]*(\.[0-9]*)?$/.test(str)) {
Probably should also handle:
  - big numbers `/^[0-9]*(\.[0-9]*)?$/.test(String(999999999999999999999.9))`
  - negative numbers `/^[0-9]*(\.[0-9]*)?$/.test(String(-2.2))`

2020-10-20 17:47 UTC, jakemcdermott commented on awx/ui_next/src/util/validators.jsx
> +    console.log(value);
```suggestion
```

2020-10-20 17:54 UTC, jakemcdermott requested changes
lgtm, just a few nits & I think we should test/merge this.

2020-10-20 23:11 UTC, jakemcdermott approved these changes

2020-10-22 21:03 UTC, tiagodread commented
@keithjgrant I tried to create a float survey and got this result:

![survey](https://user-images.githubusercontent.com/12464858/96929422-796d8980-1490-11eb-9dbf-59d1f36c10d1.gif)

Also, try add one each survey type into JT, when you add Multiple choice option and try launch the JT the page crashes totally:

![survey1](https://user-images.githubusercontent.com/12464858/96929632-ccdfd780-1490-11eb-9740-ebef254156f3.gif)

2020-10-23 22:21 UTC, keithjgrant commented
> @keithjgrant I tried to create a float survey and got this result:

I get this error in the old UI as well... I think this should be filed as an API bug. It's not accepting `2` as a value

> Also, try add one each survey type into JT, when you add Multiple choice option and try launch the JT the page crashes totally:

Should be fixed now

2020-10-26 01:45 UTC, unlikelyzero commented
please check this issue at the same time https://github.com/ansible/awx/issues/8222

2020-10-26 13:47 UTC, unlikelyzero commented
@keithjgrant @tiagodread please check #8222 and also file the float bug against the API

2020-10-26 14:25 UTC, tiagodread commented
@keithjgrant I saw that the ui_next and old UI is passing the `default` as integer:

```
{
    "description": "",
    "name": "",
    "spec": [
        {
            "choices": "",
            "default": 2,
            "max": 1024,
            "min": 0,
            "new_question": true,
            "question_description": "",
            "question_name": "1.0+1.0",
            "required": true,
            "type": "float",
            "variable": "float"
        }
    ]
}
```

changing 2 to 2.0 the API can save successfully

2020-10-26 16:55 UTC, keithjgrant commented
JavaScript doesn't distinguish between 2 and 2.0. I might be able to send the string "2.0", but a string is definitely not a float

2020-10-26 16:57 UTC, keithjgrant commented
@tiagodread JavaScript doesn't distinguish between 2 and 2.0. I might be able to send the string "2.0", but a string is definitely not a float

2020-10-26 17:54 UTC, tiagodread commented
Open a new issue to fix only Float default value here https://github.com/ansible/awx/issues/8460

2020-10-26 17:56 UTC, tiagodread approved these changes
Good Job!
Tests covered by 5635

2020-10-26 18:14 UTC, merged