Merges 2 tool bar add buttons that use dropdowns
ansible/awx pull request #8430
Opened 2020-10-21 19:15 UTC by AlexSCorey

##### SUMMARY
this addresses #8361.  We had essentially duplicated components so this removes the 1 that was being used inside some of the Inventory tree in favor of the 1 inside of the components tree.  No functionality is impacted.
##### ISSUE TYPE

-enhancement

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2020-10-21 at 3 13 40 PM](https://user-images.githubusercontent.com/39280967/96771708-0ab8ff00-13b0-11eb-96a2-f8520e737358.png)

2020-10-21 19:32 UTC, unlikelyzero commented
@AlexSCorey please give us some time to update our tests to match this new layout

2020-10-22 15:15 UTC, jakemcdermott requested changes
Looked into this w/ @AlexSCorey 

Combining these components into one is a good direction to go in and I like this PR. :+1: 

We realized we probably don't need a configuration object or a generator function for the add button. Next steps will be to update the component such that it just accepts a list of DropDownItems that the caller can define explicitly (much like the standard PF DropDown component, which this wraps).

example here: https://github.com/jakemcdermott/awx/commit/9e4fb3c18617a276c4a792cca2ee10a93ff0227e

2020-10-23 13:31 UTC, jakemcdermott commented on awx/ui_next/package.json
> +    "test": "TZ='UTC' react-scripts test --watchAll=false",
```suggestion
    "test": "TZ='UTC' react-scripts test --coverage --watchAll=false",
```

2020-10-23 13:47 UTC, jakemcdermott commented on awx/ui_next/src/screens/Template/TemplateList/TemplateList.jsx
> +  const addWFTemplate = toTitleCase(i18n._(t`Add Job Template`));
```suggestion
  const addWFTemplate = toTitleCase(i18n._(t`Add Workflow Template`));
```

2020-10-23 13:53 UTC, jakemcdermott commented on awx/ui_next/src/components/AddDropDownButton/AddDropDownButton.test.jsx
@AlexSCorey 

Let's add a test to check the kebab-related behavior.

2020-10-23 13:55 UTC, jakemcdermott commented
@AlexSCorey This is looking great. Just a few more things to do and this will be ready for QE:

- Misc. small fixups (I left them as edit suggestions in the review comments)
- Need a test case for kebab-related behavior. This should help w/ test coverage considerably.
- Small merge conflict w/ TemplateList

2020-10-23 14:33 UTC, AlexSCorey commented on awx/ui_next/package.json
> +    "test": "TZ='UTC' react-scripts test --watchAll=false",
whoops, meant to remove that.

2020-10-26 13:15 UTC, unlikelyzero commented
@tiagodread will be starting on tests for this tomorrow

2020-10-26 15:00 UTC, jakemcdermott approved these changes

2020-10-26 19:43 UTC, tiagodread commented
Hey @AlexSCorey I found some places where we are using button inside kebab options:

**Job Templates:**

- Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97215814-b6dd5a00-17a3-11eb-811f-cab797505ce6.png)

- Access tab -> Add -> Users or team -> advanced search -> kebab -> empty (same happen in WFJT Node) 

![image](https://user-images.githubusercontent.com/12464858/97216158-2e12ee00-17a4-11eb-8ac0-0eaf7aeaaaa5.png)

**Credentials:**

- Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97216432-93ff7580-17a4-11eb-9284-078691212ce5.png)

**Projects:**

- Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97216573-d1640300-17a4-11eb-9fbf-2cbd4381e515.png)
- Notifications -> advanced search -> kebab -> empty

![image](https://user-images.githubusercontent.com/12464858/97216947-50593b80-17a5-11eb-8446-11892ccde77c.png)

**Inventories**

- Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217162-9f06d580-17a5-11eb-90ac-605fd0cdcdcb.png)

- Groups tab -> advanced search -> kebab -> delete

![image](https://user-images.githubusercontent.com/12464858/97217287-cfe70a80-17a5-11eb-808a-ba9770aa70d0.png)

**Hosts**

- Groups tabs -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217542-353afb80-17a6-11eb-9b13-7004181f235e.png)

**Organizations**

- Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217676-674c5d80-17a6-11eb-9d6f-bf4910f75b0f.png)

**Teams**

- Access tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97217936-babeab80-17a6-11eb-8c37-f8e1b0475f0b.png)

- Roles tab -> advanced search -> kebab -> Add

![image](https://user-images.githubusercontent.com/12464858/97218035-e04bb500-17a6-11eb-85ab-c82d9c91c3c5.png)

**Instance groups**

- Instance tab -> advanced search -> kebab -> Associate
![image](https://user-images.githubusercontent.com/12464858/97218200-230d8d00-17a7-11eb-89dd-28b3f92e43e2.png)

2020-10-26 21:14 UTC, AlexSCorey commented
> Hey @AlexSCorey I found some places where we are using button inside kebab options:
I think all of these issues should be documented and tracked in https://github.com/ansible/awx/issues/8237.

2020-10-27 18:23 UTC, tiagodread commented
Moved above items to 8237.

@AlexSCorey I added a test case where the user can add only a job template (a normal user with project admin) on devel the dropdown button shows only one option "Add job template" (correct) on this branch I can see both options JT and WFJT we have 2 failing ui tests.

2020-10-27 18:59 UTC, tiagodread approved these changes
👍🏽

2020-10-27 19:22 UTC, merged