Move to rhel8 PG10 container for persistent PG
ansible/awx pull request #8431
Opened 2020-10-21 21:31 UTC by wenottingham

Merge in updated liveness checks from upstream template

##### SUMMARY

Needs testing.

2020-10-21 23:09 UTC, shanemcd approved these changes
I _think_ this should be fine since we just skip deploying the db if the postgres service already exists.

2020-10-22 14:39 UTC, ryanpetrello approved these changes

2020-10-22 20:42 UTC, shanemcd requested changes

2020-10-22 20:42 UTC, shanemcd commented on installer/roles/kubernetes/templates/postgresql-persistent.yml.j2
> +          image: registry.access.redhat.com/rhel8/postgresql-10
Please change to `registry.redhat.io`

2020-10-22 20:44 UTC, shanemcd commented on installer/roles/kubernetes/tasks/main.yml
> +            IMAGE=registry.access.redhat.com/rhel-8/postgresql-10
Here too

2020-10-22 21:09 UTC, shanemcd approved these changes

2020-10-22 21:38 UTC, merged