Add feature to associate teams to users
ansible/awx pull request #8463
Opened 2020-10-26 21:02 UTC by nixocio

Add feature to associate teams to users

See: https://github.com/ansible/awx/issues/7130

2020-10-28 14:11 UTC, AlexSCorey commented
During advanced search the toolbar buttons should be dropdown items, not buttons 
![Screen Shot 2020-10-28 at 10 08 49 AM](https://user-images.githubusercontent.com/39280967/97447161-a644f500-1905-11eb-92cb-39a23706ca33.png)

2020-10-28 14:11 UTC, AlexSCorey commented
I don't think we need the row item label for `Organization` here 
![Screen Shot 2020-10-28 at 10 10 01 AM](https://user-images.githubusercontent.com/39280967/97447471-f3c16200-1905-11eb-8253-3344e1a86ea6.png)

2020-10-28 14:25 UTC, AlexSCorey commented
this is weird. Looks like it is also on Organization so probably an issue with search.  (https://github.com/ansible/awx/issues/8474)
![weird filter](https://user-images.githubusercontent.com/39280967/97448274-dfca3000-1906-11eb-9333-d84ea3b19077.gif)

2020-10-28 14:28 UTC, AlexSCorey commented
Signed in as a Normal User the Add button is activated when it shouldn't be.
![normal user](https://user-images.githubusercontent.com/39280967/97449605-3d12b100-1908-11eb-8e00-82a8d0609dd9.gif)

2020-10-28 14:34 UTC, AlexSCorey commented on awx/ui_next/src/screens/User/UserTeams/UserTeamList.test.jsx
> +      wrapper = mountWithContexts(
Why are you using `<Route>` here?

2020-10-28 14:39 UTC, AlexSCorey requested changes
in UserTeamList you will want to add a test to be sure that you are properly associating a team, and then updating the list. Same thing for disassociate.

2020-10-28 23:34 UTC, nixocio commented on awx/ui_next/src/screens/User/UserTeams/UserTeamList.test.jsx
> +      wrapper = mountWithContexts(
Removed.

2020-10-28 23:39 UTC, nixocio commented
Thanks for your review @AlexSCorey. Updated per comments.

> During advanced search the toolbar buttons should be dropdown items, not buttons

https://github.com/ansible/awx/issues/8237

There is an issue tracking this problem - it was not introduced by this PR.

2020-10-30 14:14 UTC, tiagodread commented
@nixocio I Tried to click on Add button but it doesn’t appear

2020-10-30 14:18 UTC, nixocio commented
Thanks @tiagodread, updating.

2020-11-02 20:10 UTC, nixocio commented
hey @AlexSCorey, do you have any more comments?

2020-11-03 21:33 UTC, tiagodread commented
Hey @nixocio after making a search for teams -> closing the modal -> Clicking on Associate the modal opens with the old search state, we are not resetting the state of the modal

![modal](https://user-images.githubusercontent.com/12464858/98042888-17ebda00-1e03-11eb-84d2-3b6e80f75c3e.gif)

2020-11-03 22:46 UTC, nixocio commented
> Hey @nixocio after making a search for teams -> closing the modal -> Clicking on Associate the modal opens with the old search state, we are not resetting the state of the modal
> 
> ![modal](https://user-images.githubusercontent.com/12464858/98042888-17ebda00-1e03-11eb-84d2-3b6e80f75c3e.gif)

@tiagodread, this issue was not introduced by this PR, but I added a fix here as well.

The same behavior was present in other screens using the `AssociateModal`. Thanks!

2020-11-04 14:14 UTC, AlexSCorey approved these changes
This looks good to me.  You've addressed all of my concerns. Good work!

2020-11-04 17:20 UTC, tiagodread commented
When a user is associated to a team and then navigate to this user -> teams tab and try to disassociate that team nothing happens

![teams](https://user-images.githubusercontent.com/12464858/98143963-8d5db600-1ea8-11eb-8645-aca682206b4b.gif)

2020-11-10 21:06 UTC, nixocio commented
@tiagodread, the last reported issue was addressed. Please, take another look.

2020-11-11 13:55 UTC, tiagodread commented
@nixocio now we can successfully associate and disassociate teams to users, great job!!!

My only concern about it is that if you try to associate/disassociate a ton of teams it'll take long time to complete all xhr requests specially for slow connections. 
![teams](https://user-images.githubusercontent.com/12464858/98819793-16766f00-240c-11eb-902c-c4d104694cda.gif)

A suggestion could be disable the buttons Associate/Disassociate until these xhr requests finish or something different to indicates that something is happening in background, what do you think about it ?

2020-11-12 17:15 UTC, nixocio commented
> @nixocio now we can successfully associate and disassociate teams to users, great job!!!
> 
> My only concern about it is that if you try to associate/disassociate a ton of teams it'll take long time to complete all xhr requests specially for slow connections.
> ![teams](https://user-images.githubusercontent.com/12464858/98819793-16766f00-240c-11eb-902c-c4d104694cda.gif)
> 
> A suggestion could be disable the buttons Associate/Disassociate until these xhr requests finish or something different to indicates that something is happening in background, what do you think about it ?

Hey @tiagodread, that is a valid point. There is an issue tracking related work here https://github.com/ansible/awx/issues/4212, I added a comment for delete/disassociating actions as well.

2020-11-12 17:27 UTC, tiagodread approved these changes
Great Job Kersom 🎉

2020-11-12 18:21 UTC, merged