Show access tab when credential does not belong to a team
ansible/awx pull request #8776
Opened 2020-12-07 16:10 UTC by nixocio

Credential access tab should be shown when cred doesn't belong to an organization.

Also, update unit-tests to reflect change.

See: https://github.com/ansible/awx/issues/7708

2020-12-10 15:10 UTC, AlexSCorey reviewed
This looks good to me. It would be great if you could convert `AddResourceRole.jsx` to a functional component.  This will help get this file more in line with our conventions, and it will help with the Lingui upggrade in the near future.

2020-12-10 15:11 UTC, AlexSCorey approved these changes
This looks good to me. I'm approving, but It would be great if you could convert `AddResourceRole.jsx` to a functional component.  This will help get this file more in line with our conventions, and it will help with the Lingui upggrade in the near future.

2020-12-10 16:07 UTC, AlexSCorey requested changes
There is a loading bug here.  If you are on the access tab and navigate to the details view you will see the loading screen 2x and duplicate api calls.  https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.jsx#L81.  make this line ` }, [credentialId, credential_type.id])` and that should solve the problem

2020-12-10 22:51 UTC, nixocio commented
> There is a loading bug here. If you are on the access tab and navigate to the details view you will see the loading screen 2x and duplicate api calls. https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Credential/CredentialDetail/CredentialDetail.jsx#L81. make this line ` }, [credentialId, credential_type.id])` and that should solve the problem

Updated.

2020-12-11 20:14 UTC, nixocio commented
hey @AlexSCorey, if necessary lets convert this component to functional in another PR.

2020-12-11 20:20 UTC, AlexSCorey approved these changes
Looks good.

2020-12-14 15:17 UTC, AlexSCorey commented
duplicate issue https://github.com/ansible/awx/issues/8842

2021-01-07 22:33 UTC, one-t commented
Hey, @nixocio - just want to make sure I have the idea right on this one. 

AKit Steps: create a `credential` with no `organization` association, (i.e. owned by a user)
Test Steps:
* This user goes to the `Details` page for this `Credential`
* This user can see the `Access` tab
* This user can access the `Access` tab
* This user is able to see the `Add` button

Is this correct?

Thanks!

2021-01-08 14:35 UTC, nixocio commented
hey @one-t, yeah.  But we can verify a few more steps.

From now on the `Access` tab is always visible on `Credentials`.

1. If the credential does not have an organization then you can only select user(s) when adding new roles.

Once the user click the `Add` button on `Access` tab the user should just see the `Users` option to add access.

![image](https://user-images.githubusercontent.com/9053044/104026604-2c967680-5194-11eb-9d5a-7f45504d12ec.png)

2. If the credential does have an organization then you can select user(s) or team(s) when adding new roles

Once the user click the `Add` button on `Access` tab the user should just see the `Users` and `Teams` option to add access.

![image](https://user-images.githubusercontent.com/9053044/104026859-8ac35980-5194-11eb-8b04-21ceeda6ef80.png)

Thanks!

2021-01-08 14:38 UTC, nixocio commented
@one-t, also be aware of this other bug https://github.com/ansible/awx/issues/8707.

Re-testing this I could not remove an organization from a credential. I will address this other 🐛 in another PR.

2021-01-08 17:13 UTC, one-t commented
Thanks, for the confirmation, @nixocio ! I'll add those steps along with some related stubs

2021-01-08 18:43 UTC, one-t commented
It looks like the Users and Teams buttons are missing Aria labels here- I'm still pretty new to UI testing so I may be mistaken in looking for them.  If they are supposed to be there, do you want to add them as part of this PR or a different one?

2021-01-08 19:37 UTC, nixocio commented
> It looks like the Users and Teams buttons are missing Aria labels here- I'm still pretty new to UI testing so I may be mistaken in looking for them. If they are supposed to be there, do you want to add them as part of this PR or a different one?

Hey @one-t, I added the `aria-label`.

2021-01-11 14:50 UTC, unlikelyzero commented
@one-t one more: adding the credential to an org removes this tab

2021-01-12 17:24 UTC, unlikelyzero commented
covered in https://github.com/ansible/tower-qa/pull/5841

2021-01-12 18:27 UTC, unlikelyzero commented
regate

2021-01-12 18:46 UTC, merged