Fixes missing credential types and makes credential field a type ahead
ansible/awx pull request #9116
Opened 2021-01-20 16:03 UTC by AlexSCorey

##### SUMMARY
This resolves #8944.  It calls the api to get up to 400 credential types and turns the credential type field into a drop down.  The mock ups call for the credential type field to be a look up, but prior to this PR it was a drop down and I believe continuing with the drop down, and adding typeahead functionality is the right direction to go instead of using a look up.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
##### ADDITIONAL INFORMATION
![Screen Shot 2021-01-20 at 11 02 22 AM](https://user-images.githubusercontent.com/39280967/105201555-061af880-5b0f-11eb-989f-cd50ca631c58.png)

2021-01-20 16:12 UTC, jakemcdermott approved these changes

2021-01-21 12:47 UTC, unlikelyzero commented
This will require some changes to the e2e tests, a net new test for this typeahead functionality, and a visual test for this new component

2021-01-28 16:18 UTC, sezanzeb commented
I checked out at your branch and pulled the new commits from devel in

```
git status
On branch 8944-CredTypeLookup
Your branch is ahead of 'credentialtypefix/8944-CredTypeLookup' by 151 commits.
```

ran the installation playbook

```
ansible-playbook -i inventory install.yml -e @vars.yml
```

but the credential type input is still only a dropdown without a text input, and "Source Control" is still hidden. Did I miss something?

2021-02-06 23:09 UTC, unlikelyzero requested changes
@AlexSCorey We executed all the tests [here](https://github.com/ansible/tower-qa/pull/5949#pullrequestreview-584889643)

Unfortunately, we do not have a usable locator like a unique id

2021-02-09 22:11 UTC, one-t commented
Hey, @AlexSCorey - A couple things we found that need addressing

If the name of the credential is long it can extend off of the page.  (@tiagodread also suggested pinging @trahman73 about what approach to take here)
![image](https://user-images.githubusercontent.com/28987580/107433958-ed36af00-6ade-11eb-9e05-49367d761473.png)

After choosing a credential type, the menu stays open until you click outside of it. Since it's not a multiple selection it should collapse as soon as you choose the credential.
![stays-open](https://user-images.githubusercontent.com/28987580/107434500-b3b27380-6adf-11eb-9f72-626f0d269b8a.gif)

2021-02-09 22:53 UTC, trahman73 commented
We would have to truncate after a sane limit to avoid the credential name to break the layout of the page. I also agree with the desired behavior of the menu collapsing for single select options.

2021-02-10 20:36 UTC, AlexSCorey commented
@unlikelyzero I've fixed the truncating issues

2021-02-11 00:12 UTC, unlikelyzero approved these changes

2021-02-11 00:21 UTC, one-t commented
regate

2021-02-11 04:02 UTC, merged

2021-02-11 13:15 UTC, sezanzeb commented
pulled in latest devel, still not a type ahead field.

This is of incredible importance to us, please tell me what I am supposed to do to get this updated form

2021-02-11 13:53 UTC, unlikelyzero commented
@sezanzeb hey, that sort of question usually goes to the [AWX Community forum](https://groups.google.com/g/awx-project) so that we can identify common issues outside of individual PRs.

2021-02-11 14:18 UTC, sezanzeb commented
https://groups.google.com/g/awx-project/c/i0CkKms__L4