Mark start node for translation
ansible/awx pull request #9344
Opened 2021-02-17 20:13 UTC by mabashian

##### SUMMARY
link #5990 

Start node with various text lengths:

<img width="1110" alt="Screen Shot 2021-02-17 at 2 38 22 PM" src="https://user-images.githubusercontent.com/9889020/108262233-a70eca80-7132-11eb-8e34-55c4cdaacae9.png">
<img width="1051" alt="Screen Shot 2021-02-17 at 2 37 53 PM" src="https://user-images.githubusercontent.com/9889020/108262235-a7a76100-7132-11eb-95c8-1d834922bfa1.png">
<img width="1089" alt="Screen Shot 2021-02-17 at 2 37 18 PM" src="https://user-images.githubusercontent.com/9889020/108262236-a7a76100-7132-11eb-8d60-bac45c4a788c.png">

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

2021-02-17 20:29 UTC, AlexSCorey commented
lets remove start from https://github.com/ansible/awx/blob/40cf4ff2090e4bc8816b05963bd76b665ed3ecd1/awx/ui_next/.eslintrc#L82

2021-02-17 21:13 UTC, jakemcdermott approved these changes

2021-02-17 21:13 UTC, jakemcdermott commented on awx/ui_next/src/screens/Template/WorkflowJobTemplateVisualizer/VisualizerLink.jsx
> +    ref.current.parentNode.insertBefore(ref.current, startNode);
I think remember translation being tricky for workflow nodes (?) in the old ui - glad to have found an approach here :+1:

2021-02-17 21:14 UTC, jakemcdermott approved these changes
I think remember translation being tricky for workflow nodes (?) in the old ui - glad to have found an approach here +1

2021-02-18 16:41 UTC, AlexSCorey requested changes
See https://github.com/ansible/awx/pull/9344#issuecomment-780833299

2021-03-02 13:31 UTC, unlikelyzero commented
@mabashian this will just need 🟢 from the e2e tests

2021-03-03 15:56 UTC, AlexSCorey approved these changes
Looks good to me

2021-03-15 13:56 UTC, unlikelyzero commented
Unit test coverage is great! Marking this issue as needs_test and pending_translations so that we can test when real translations land

2021-03-15 14:17 UTC, merged