Removes test coverage flag locally in favor of running that in zuul
ansible/awx pull request #9347
Opened 2021-02-17 21:03 UTC by AlexSCorey

##### SUMMARY
This removes the unit test command `--coverage` in package.json that generates the coverage report after test are completed.  Instead, we decided to generate that report in zuul when creating/updated PRs.  Also updates ReadME

##### ISSUE TYPE
 - tooling

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION

2021-02-17 21:10 UTC, jakemcdermott approved these changes

2021-02-17 21:10 UTC, jakemcdermott commented on awx/ui_next/README.md
> +# start the tests and get the coverage report after the tests have completed
```suggestion

# start the tests and get the coverage report after the tests have completed
```

2021-02-17 23:23 UTC, jakemcdermott commented
recheck

2021-02-18 13:02 UTC, jakemcdermott requested changes

2021-02-18 13:02 UTC, jakemcdermott commented on Makefile
> +	$(NPM_BIN) run --prefix awx/ui_next test "TZ='UTC' react-scripts test -- --coverage --watchAll=false",
```suggestion
	$(NPM_BIN) run --prefix awx/ui_next test -- --coverage --watchAll=false
```

2021-02-18 13:11 UTC, jakemcdermott approved these changes

2021-02-18 13:27 UTC, unlikelyzero commented
@AlexSCorey let's sync on a common makefile command for instrumentation as a part of this PR. I've got one here: https://gist.githubusercontent.com/unlikelyzero/2278deca3ce441a23b12494027c850a8/raw/09805fbec33cd5dd431ee800615719e53a98d8f2/Makefile

2021-02-18 13:51 UTC, merged