added survey_spec to JobTemplate model
ansible/awx pull request #9362
Opened 2021-02-19 03:45 UTC by pnhowe

##### SUMMARY
added "survey_spec" to the fields of the JobTemplate model, this enables the awx cli to be able to upload survey specs.

related #8464

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
17.0.1
```

##### ADDITIONAL INFORMATION
This is a PR to implement the change as mentioned in "CLI import of surveys does not work #8464", there was a request for a PR, so here it is.  I have tried it out my self and it seems to function as it should.

2021-02-22 17:05 UTC, ryanpetrello requested changes
Hey @pnhowe,

Thanks for this PR.  While this is simple, it's probably the wrong approach w/ the current API.  There's a survey-spec specific API endpoint `/api/v2/job_templates/N/survey_spec/` that implements a bunch of survey-specific validation; the CLI probably needs code to interface with that for managing the survey spec.

2021-02-22 17:42 UTC, pnhowe commented
Not the PR you were looking for eh @ryanpetrello ;-)  ... While pushing those changes in I also noticed "JobTemplateWithSpecSerializer", which seems to be JobTemplateSerializer plus the survey_spec, was this another way to modify the spec that the API designers had in mind?  Anything we can do to light a fire under the CLI wizards to get the CLI updated to use a better interface?

2021-02-22 18:58 UTC, ryanpetrello commented
> light a fire under the CLI wizards to get the CLI updated to use a better interface

Find them more hours in a day 😄

2021-05-18 14:44 UTC, jbradberry commented
Closing this, since we need to approach the issue a bit differently.

2021-05-18 14:44 UTC, closed without merging

2022-06-10 23:28 UTC, earchibald-lv commented
OK, this is closed.

Will we EVER be able to at least **read** the survey spec without hacking the CLI? This is ridiculous.

2022-06-14 17:47 UTC, jbradberry commented
@earchibald-lv it's admittedly a bit of a workaround, but reading and writing of `survey_spec` is supported using the `awx import` and `awx export` sub-commands.