build images on non-Darwin platforms using Buildkit
ansible/awx pull request #9385
Opened 2021-02-22 21:09 UTC by ryanpetrello

https://docs.docker.com/develop/develop-images/build_enhancements/

@shanemcd how does this make you feel?

2021-02-22 22:51 UTC, shanemcd commented on Makefile
> +	$(COMPOSE_BUILDENV) docker build -t ansible/awx_devel \
```suggestion
	DOCKER_BUILDKIT=1 docker build -t ansible/awx_devel \
```

2021-02-22 22:51 UTC, shanemcd commented on Makefile
> +COMPOSE_BUILDENV ?= $(shell [[ "$OSTYPE" == "darwin"* ]] && echo "" || echo "DOCKER_BUILDKIT=1")
```suggestion

```

2021-02-22 22:51 UTC, shanemcd requested changes
I tested w/ Docker Desktop and BuildKit works fine there.

2021-02-22 22:54 UTC, shanemcd approved these changes

2021-02-23 14:52 UTC, ryanpetrello commented
regate

2021-02-23 15:20 UTC, merged