Add Execution Environments into a few screens
ansible/awx pull request #9394
Opened 2021-02-23 19:57 UTC by nixocio

Add EE to follow screens:

* Job Template
* Organization
* Project
* Workflow Job Template

Also, add a new lookup component - ExecutionEnvironmentLoookup.

See: https://github.com/ansible/awx/issues/9189

2021-02-23 20:01 UTC, nixocio commented
hey @jakemcdermott, I will address inventory source in another PR.

2021-02-24 15:37 UTC, jakemcdermott commented
@nixocio I see some extra commits in the PR -  It might need a rebase or a different base branch.

2021-02-24 15:37 UTC, jakemcdermott requested changes
@nixocio I see some extra commits in the PR - It might need a rebase or a different base branch.

2021-02-24 17:55 UTC, jakemcdermott approved these changes

2021-02-24 17:55 UTC, jakemcdermott commented on awx/ui_next/src/screens/Template/shared/JobTemplateForm.jsx
> +          organizationId={projectData?.organization}
Nice!

2021-02-24 18:15 UTC, merged