I18n devel translations
ansible/awx pull request #9689
Opened 2021-03-25 00:41 UTC by rooftopcellist

##### SUMMARY

First round of translations for ui_next.  I have also included:
* necessary changes to import fr, nl, es, zh, and also add them to the catalog.  
* fixed a syntax error that was keeping strings from compiling.  

##### ISSUE TYPE

 - Feature

##### COMPONENT NAME

 - Translations

##### AWX VERSION

```
devel
```

2021-03-25 17:07 UTC, jakemcdermott approved these changes
lgtm - if all layers of tests are happy, I am happy

2021-03-25 17:07 UTC, jakemcdermott commented on awx/ui_next/src/App.jsx
> +  const catalogs = { en, es, fr, ja, nl, zh };
:+1: yep

2021-04-08 13:09 UTC, rooftopcellist commented
recheck

2021-04-20 14:09 UTC, AlexSCorey requested changes, later dismissed
There have been some significant changes in the way we set up ling ui in App.jsx and our syntax for marking strings for translation. Please rebase this PR to get the new way we set up I18n.

The new syntax for making strings for translation is ``` t`string` ```

2021-04-20 15:00 UTC, rooftopcellist commented
Thanks for the heads up @AlexSCorey , I've rebased this PR.  There were some more recent extracted strings (still untranslated) in devel.  This PR may remove some of them, that is OK because when we go to push new strings to the translation team, we will get the newest strings available at that time.

2021-04-20 20:59 UTC, rooftopcellist commented
CI is passing now.  Thanks for the help @AlexSCorey !

2021-04-20 22:07 UTC, jakemcdermott approved these changes

2021-04-20 22:07 UTC, jakemcdermott commented on awx/ui_next/src/App.jsx
> -import zh from './locales/zh/messages';
:+1: 

nice :)

2021-04-20 22:09 UTC, jakemcdermott approved these changes

2021-04-20 22:09 UTC, jakemcdermott commented on awx/ui_next/src/App.jsx
> -  const catalogs = { en, es, fr, ja, nl, zh };
:+1: 
nice :)

2021-04-21 15:00 UTC, merged