[WIP]project: Add last job status as for feedback feature.
ansible/awx pull request #9931
Opened 2021-04-16 16:28 UTC by seiwailai

##### SUMMARY
Related to #9872 

Add last job status as for project sync feedback feature. When users clicked the `sync` button on the project page, `last job status` will eventually update the status to `Pending`, `Waiting`, `Running`, and final result (`Successful`, `Cancelled`, `Failed`, `Error`). The implementation requires the WebSocket connection to ensure synchronous status update.

In particular, the `last job status` is similar to the functionality of `status` in the project list (`status` in `ProjectListItem.jsx`). More specifically, the `last job status` accompanied by a job link that allowing the user to navigate to the job output page. Besides, there is also the tooltip that allowing the user to view the information related to the most recent sync, covering information like `JOB ID`, `STATUS`, `FINISHED`.

The rationale of having the `last job status` instead of redirection or toast notification is that:
1. User has choices on whether to redirect to the job output. If the user wishes to navigate to job output, he/she can click the link. Besides, the user might have other projects to be synced right after the current project and he/she may want to proceed back to the project list page instead of the job output page. If we implement force redirection, it would take a longer time to navigate to the project list page.
2. The status update on `last job status` is fundamentally similar to toast notification where the user can immediately be notified if he/she already clicked the `sync` button to launch the job.

Nevertheless, this PR requires further discussion. Any comments are welcomed!

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI
 
1. `awx/ui_next/src/screens/Project/Project.jsx`
2. `awx/ui_next/src/screens/Project/Project.jsx` - Added websocket implementation
3. `awx/ui_next/src/screens/Project/ProjectDetail/ProjectDetail.jsx`

##### AWX VERSION

```
awx: 19.0.0
```

##### ADDITIONAL INFORMATION

In case if users spam the sync button, we will need to ensure the fluent UI on the most recent sync tooltip and last job status. Thus, we would not want to update our last job status to `Pending` if there is a current running job.

For instance, we clicked sync for a particular project twice. 
1. For the first sync, our last job status should immediately change to `Pending`, then `Waiting`, then `Running`, then result (which are `Successful`, `Failed`, `Error`, `Cancelled`).
2. For the second sync, if we have a running job, we should not update our UI to `Pending`, otherwise our most recent sync tooltip UI will lose our current running job and we cannot navigate to the job link through the link provided by `last job status` tooltip.

**Issue of `sync` button click spam**
Ideally, we should prevent any spamming on the `sync` button using backend logic to reduce overload on the server as we already have a similar running project. Together with backend logic, we can disable the sync button right after we start to sync a project.

However, if we only disable `sync` through the frontend, this seems insecure as people with bad intentions might able to change the button disable attribute.

**After**
![project_sync_feedback](https://user-images.githubusercontent.com/67208821/115053818-1f66f180-9f12-11eb-9970-55adfce6abf9.gif)

2021-04-19 12:38 UTC, nixocio commented
@seiwailai when this PR is ready, please, add the label `needs_review`.

2021-04-19 13:34 UTC, seiwailai commented
> Thanks for your PR. Is it ready to be reviewed?

Yup, this is ready for review

2021-04-19 15:36 UTC, AlexSCorey commented on awx/ui_next/src/screens/Project/useWsProject.js
> +      // running and waiting jobs, we should not update our UI to `Pending`,
```suggestion
      // running or waiting jobs, we should not update our UI to `Pending`,
```

2021-04-19 15:36 UTC, AlexSCorey commented on awx/ui_next/src/screens/Project/useWsProject.js
> +      // running and waiting jobs, we should not update our UI to `Pending`,
We should also disable the sync button

2021-04-19 15:38 UTC, AlexSCorey requested changes
I really like this!  Just a couple of minor changes.  We should probably add some tests as well.

2021-04-19 18:47 UTC, seiwailai commented on awx/ui_next/src/screens/Project/useWsProject.js
> +      // running and waiting jobs, we should not update our UI to `Pending`,
> I really like this! Just a couple of minor changes. We should probably add some tests as well.

@AlexSCorey Thanks for your review, will make changes and add tests as soon as possible!

2021-04-19 22:02 UTC, jakemcdermott commented
recheck

2021-04-22 14:16 UTC, mabashian commented
@AlexSCorey is this just waiting for a re-review?

2021-04-26 11:10 UTC, seiwailai commented
@AlexSCorey @nixocio @jakemcdermott Ready for review!

2021-04-27 13:29 UTC, AlexSCorey approved these changes
Good well done!  Thanks for doing this.

2021-04-28 19:43 UTC, tiagodread requested changes
Hey @seiwailai thanks for adding all this context, this is awesome!
We have the same issue with the sync button span on the Project list, do you mind disabling the sync button on Project list as well?

2021-04-29 06:35 UTC, seiwailai commented
> Hey @seiwailai thanks for adding all this context, this is awesome!
> We have the same issue with the sync button span on the Project list, do you mind disabling the sync button on Project list as well?

@tiagodread Sure thing!

2021-04-29 07:54 UTC, seiwailai commented
> Hey @seiwailai thanks for adding all this context, this is awesome!
> We have the same issue with the sync button span on the Project list, do you mind disabling the sync button on Project list as well?

@tiagodread This is after changes for the project list!

![project_list_sync_button](https://user-images.githubusercontent.com/67208821/116518675-24a94080-a903-11eb-94e4-694dfe1712a3.gif)

2021-04-29 14:34 UTC, tiagodread commented
@seiwailai trying to create a project when I hit the save button the page is crashing:

![chrome-capture (9)](https://user-images.githubusercontent.com/12464858/116559708-17765c80-a8d7-11eb-9053-67ee1257024d.gif)
![image](https://user-images.githubusercontent.com/12464858/116559702-16ddc600-a8d7-11eb-866b-ea05e8539e3b.png)

2021-04-30 19:45 UTC, seiwailai commented
@tiagodread I've added the conditional statement on rendering job status UI to solve the crash after project creation. Thank you for your comment!

**Newly-created project on sync**
![add_project_on_sync](https://user-images.githubusercontent.com/67208821/116746348-ef9a0c80-aa2e-11eb-8950-beda4d828815.gif)

**Project on sync**
![project_on_sync](https://user-images.githubusercontent.com/67208821/116746380-fa54a180-aa2e-11eb-839e-4472a9bad2c0.gif)

**Project list on sync**
![project_list_on_sync](https://user-images.githubusercontent.com/67208821/116746402-03de0980-aa2f-11eb-9c73-62c519432000.gif)

2021-05-03 13:07 UTC, tiagodread approved these changes
Verified that:
- The user can create projects
- The sync button is disabled while the sync is running and the tooltip is displayed
- The user can click on the `Last Job Status` and navigate to the `Source Control Update` for the current project.
- All e2e tests are 🟢

2021-05-03 13:28 UTC, merged