Fixes object rendered on dom in aria-label
ansible/awx pull request #9958
Opened 2021-04-20 16:04 UTC by AlexSCorey

##### SUMMARY
This addresses #9910. Aria-labels that use `<Plural/>` won't work properly.  In this case I used aria-labelledby and passed it the id of the button.  I tested it with a screen reader and that fixed it.  I also fixed some `JobListCancelButton` tooltips

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

##### ADDITIONAL INFORMATION
![Screen Shot 2021-04-20 at 11 59 49 AM](https://user-images.githubusercontent.com/39280967/115428267-39355c80-a1d0-11eb-86c4-b740da239c10.png)

2021-04-20 16:18 UTC, jakemcdermott requested changes

2021-04-20 16:18 UTC, jakemcdermott commented on awx/ui_next/src/components/JobList/JobListCancelButton.jsx
> +              )}
```suggestion
              {cannotCancelPermissions.join(',').map(text => <strong>{text}</strong>)}
```

You'll want to use [`join`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join) for this kind of problem. 

![Screenshot from 2021-04-20 12-13-15](https://user-images.githubusercontent.com/9753817/115430383-50754980-a1d2-11eb-8da2-4f7cc1d48139.png)

2021-04-20 16:18 UTC, jakemcdermott commented on awx/ui_next/src/components/JobList/JobListCancelButton.jsx
> +              )}
```suggestion
{cannotCancelNotRunnning.join(',').map(text => <strong>{text}</strong>)}
```

2021-04-20 16:22 UTC, jakemcdermott commented on awx/ui_next/src/components/JobList/JobListCancelButton.jsx
> +              )}
Actually, nevermind. This won't work for what we're doing here.

2021-04-20 16:23 UTC, jakemcdermott approved these changes

2021-04-21 16:59 UTC, unlikelyzero commented
@AlexSCorey this may have some pretty serious consequences for the UI Tests. We unfortunately focused too much on aria-labels in the beginning. I personally spent 3 weeks removing all the aria-labels from the visual tests. I would expect the same amount of effort here

2021-04-21 19:48 UTC, AlexSCorey commented
@unlikelyzero I think the issue is actually quite unique because we don't have many, and this this might be the only place, where we use lingui's `<Plural/>` to generate an aria label, which was causing the issue

2021-04-21 20:10 UTC, AlexSCorey commented
clean cypress test except for 1 failure that doesn't look related [cypress tests](https://dashboard.cypress.io/projects/ui2mq7/runs?branches=%5B%7B%22label%22%3A%229910-PluralAriaLabel%22%2C%22suggested%22%3Afalse%2C%22value%22%3A%229910-PluralAriaLabel%22%7D%5D&committers=%5B%5D&flaky=%5B%5D&page=1&status=%5B%5D&tags=%5B%5D&timeRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D)

2021-04-22 13:17 UTC, tiagodread approved these changes
The original issue was fixed, e2e tests are good.

2021-04-22 13:45 UTC, merged