Fixes bug where workflow approvals page would crash if deleted username was referenced
ansible/awx pull request #9988
Opened 2021-04-22 13:59 UTC by mabashian

##### SUMMARY
link #9163 

The tooltip on the status labels for completed workflow approvals attempts to show the username of the user that acted on it.  If that user has been deleted then the key is not present in the object.  This would cause the page to crash.

To fix this, I conditionally show a different string when the username is not available.  If a user wants to see which deleted user acted on the approval they'll have to go to the activity stream.

<img width="474" alt="Screen Shot 2021-04-22 at 9 59 23 AM" src="https://user-images.githubusercontent.com/9889020/115727254-6eb58380-a351-11eb-96e4-85d38213ab85.png">

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

2021-04-22 20:16 UTC, AlexSCorey requested changes
Looks good.  Small changes.

2021-04-22 20:16 UTC, AlexSCorey commented on awx/ui_next/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.jsx
> +            ? i18n._(
Remove the `i18n._` here in favor of  ```t`string` ```

If you can get rid of the `i18n` object and `withI18n` in this file as well that would be good to do.

2021-04-22 20:16 UTC, AlexSCorey commented on awx/ui_next/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.jsx
> +            : i18n._(
same

2021-04-22 20:16 UTC, AlexSCorey commented on awx/ui_next/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.jsx
> +            ? i18n._(
same

2021-04-22 20:16 UTC, AlexSCorey commented on awx/ui_next/src/screens/WorkflowApproval/shared/WorkflowApprovalStatus.jsx
> +            : i18n._(
same

2021-05-03 15:04 UTC, mabashian commented
@AlexSCorey I think I got all those cleaned up for ya

2021-05-03 16:13 UTC, tiagodread commented
@mabashian could you rebase this one?

2021-05-10 16:29 UTC, tiagodread commented
@mabashian could you rebase this one?

2021-05-10 19:18 UTC, one-t commented
Just mentioning here, this PR may resolve some issues we're seeing with YOLO runs that include API tests. These seem to leave behind orphaned objects that cause the page to crash.

I'll see if I can figure out the exact reproducer(s). We want the UI to handle this but we also don't want orphaned objects floating around in the DB.

2021-05-10 19:53 UTC, one-t commented
Ok, I've confirmed, the exact situation is this:
1) Create a workflow job template with an approval node
2) Create a user with the rights to approve
3) Launch workflow job and approve as the user
4) Delete the user
5) Page fails to render as described in the related issue.

I don't think any changes will be needed for the API tests, we already don't clean up jobs.

2021-05-10 20:05 UTC, one-t commented
Confirmed, this does fix the issue and the page now renders when the approving user is deleted.

2021-05-11 01:23 UTC, one-t approved these changes
Jenkins run demonstrated that this fixes our issue with the API tests leaving behind orphaned approvals. :shipit:

2021-05-11 01:24 UTC, one-t commented
!regate

2021-05-13 20:41 UTC, AlexSCorey approved these changes
Looks good well done!

2021-05-14 13:17 UTC, merged